# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-22 22:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copyediting', '0002_auto_20170711_1203'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='copyeditassignment',
            unique_together=set([]),
        ),
    ]
