# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-20 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copyediting', '0006_auto_20200117_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorreview',
            name='files_updated',
            field=models.ManyToManyField(blank=True, to='core.File', verbose_name='files_updated'),
        ),
    ]
