# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-08 11:05
from __future__ import unicode_literals

from django.db import migrations

from utils import migration_utils


def replace_author_review_setting(apps, schema_editor):
    values_to_replace = [
        '{{journal.site_url}}{{ url }}',
        '{{request.journal.site_url}}{{ url }}',
        '{{ copyedit_review_url }}'
    ]

    migration_utils.update_translated_settings(
        setting_name='copyeditor_notify_author',
        group_name='email',
        values_to_replace=values_to_replace,
        replacement_value="{{ author_copyedit_url }}",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('copyediting', '0007_auto_20210120_1145'),
    ]

    operations = [
        migrations.RunPython(replace_author_review_setting,
                             reverse_code=migrations.RunPython.noop),
    ]
