# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-09-23 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copyediting', '0008_fix_copyeditor_notify_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='copyeditassignment',
            options={'ordering': ('assigned',)},
        ),
    ]
