# Generated by Django 4.2.11 on 2024-09-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_alter_accountrole_options'),
        ('copyediting', '0009_copyeditassignment_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copyeditassignment',
            name='copyeditor_files',
            field=models.ManyToManyField(blank=True, related_name='copyeditor_files', to='core.file'),
        ),
    ]
