__copyright__ = "Copyright 2017 Birkbeck, University of London"
__author__ = "Martin Paul Eve & Andy Byers"
__license__ = "AGPL v3"
__maintainer__ = "Birkbeck Centre for Technology and Publishing"


from django.urls import path
from django.urls import re_path

from review import views
from review.const import EditorialDecisions

urlpatterns = [
    path("", views.home, name="review_home"),
    path("unassigned/", views.unassigned, name="review_unassigned"),
    path(
        "unassigned/article/<int:article_id>/",
        views.unassigned_article,
        name="review_unassigned_article",
    ),
    path(
        "unassigned/article/<int:article_id>/projected_issue/",
        views.add_projected_issue,
        name="review_projected_issue",
    ),
    re_path(
        r"^unassigned/article/(?P<article_id>\d+)/assign/(?P<editor_id>\d+)/type/(?P<assignment_type>[-\w.]+)/$",
        views.assign_editor,
        name="review_assign_editor",
    ),
    re_path(
        r"^unassigned/article/(?P<article_id>\d+)/assign/(?P<editor_id>\d+)/type/(?P<assignment_type>[-\w.]+)/"
        r"move/review/$",
        views.assign_editor_move_to_review,
        name="review_assign_editor_and_move_to_review",
    ),
    path(
        "unassigned/article/<int:article_id>/unassign/<int:editor_id>/",
        views.unassign_editor,
        name="review_unassign_editor",
    ),
    path(
        "unassigned/article/<int:article_id>/notify/<int:editor_id>/",
        views.assignment_notification,
        name="review_assignment_notification",
    ),
    path(
        "unassigned/article/<int:article_id>/move/review/",
        views.move_to_review,
        name="review_move_to_review",
    ),
    path(
        "article/<int:article_id>/crosscheck/",
        views.view_ithenticate_report,
        name="review_crosscheck",
    ),
    re_path(
        r"^article/(?P<article_id>\d+)/move/(?P<decision>accept|decline|undecline)/$",
        views.review_decision,
        name="review_decision",
    ),
    path(
        "article/<int:article_id>/summary/",
        views.unassigned_article,
        name="review_summary",
    ),
    path("article/<int:article_id>/", views.in_review, name="review_in_review"),
    path(
        "article/<int:article_id>/round/<int:round_id>/delete/",
        views.delete_review_round,
        name="review_delete_review_round",
    ),
    path(
        "article/<int:article_id>/round/<int:round_id>/files/add/",
        views.add_files,
        name="review_add_files",
    ),
    path(
        "article/<int:article_id>/round/<int:round_id>/files/<int:file_id>/remove/",
        views.remove_file,
        name="review_remove_file",
    ),
    path(
        "article/<int:article_id>/review/add/",
        views.add_review_assignment,
        name="review_add_review_assignment",
    ),
    path(
        "article/<int:article_id>/review/<int:review_id>/notify/",
        views.notify_reviewer,
        name="review_notify_reviewer",
    ),
    path(
        "article/<int:article_id>/review/<int:review_id>/view/",
        views.view_review,
        name="review_view_review",
    ),
    path(
        "article/<int:article_id>/review/<int:review_id>/answer/<int:answer_id>/",
        views.edit_review_answer,
        name="review_edit_review_answer",
    ),
    path(
        "article/<int:article_id>/review/<int:review_id>/edit/",
        views.edit_review,
        name="review_edit_review",
    ),
    path(
        "article/<int:article_id>/review/<int:review_id>/delete/",
        views.delete_review,
        name="review_delete_review",
    ),
    path(
        "article/<int:article_id>/review/<int:review_id>/withdraw/",
        views.withdraw_review,
        name="review_withdraw_review",
    ),
    path(
        "article/<int:article_id>/review/<int:review_id>/reset/",
        views.reset_review,
        name="review_reset_review",
    ),
    path(
        "article/<int:article_id>/review/<int:review_id>/rate/",
        views.rate_reviewer,
        name="review_rate_reviewer",
    ),
    re_path(
        r"article/(?P<article_id>\d+)/review/(?P<review_id>\d+)/reminder/(?P<reminder_type>request|accepted)/",
        views.send_review_reminder,
        name="review_send_reminder",
    ),
    path(
        "article/<int:article_id>/revisions/request/",
        views.request_revisions,
        name="review_request_revisions",
    ),
    path(
        "article/<int:article_id>/revisions/<int:revision_id>/notify/",
        views.request_revisions_notification,
        name="request_revisions_notification",
    ),
    path(
        "article/<int:article_id>/revisions/<int:revision_id>/edit/",
        views.edit_revision_request,
        name="edit_revision_request",
    ),
    path(
        "article/<int:article_id>/revisions/<int:revision_id>/",
        views.do_revisions,
        name="do_revisions",
    ),
    path(
        "article/<int:article_id>/revisions/<int:revision_id>/update/file/<int:file_id>",
        views.replace_file,
        name="revisions_replace_file",
    ),
    path(
        "article/<int:article_id>/revisions/<int:revision_id>/upload/file/",
        views.upload_new_file,
        name="revisions_upload_new_file",
    ),
    path(
        "article/<int:article_id>/revisions/<int:revision_id>/view/",
        views.view_revision,
        name="view_revision",
    ),
    path(
        "article/<int:article_id>/decision/draft/",
        views.draft_decision,
        name="review_draft_decision",
    ),
    path(
        "article/<int:article_id>/decision/draft/<int:draft_id>/",
        views.edit_draft_decision,
        name="review_edit_draft_decision",
    ),
    path(
        "article/<int:article_id>/decision/draft/<int:draft_id>/action/",
        views.manage_draft,
        name="review_manage_draft",
    ),
    path(
        "article/<int:article_id>/decision/draft/text/",
        views.draft_decision_text,
        name="review_draft_decision_text",
    ),
    path("requests/", views.review_requests, name="review_requests"),
    path(
        "requests/<int:assignment_id>/accept/",
        views.accept_review_request,
        name="accept_review",
    ),
    path(
        "requests/<int:assignment_id>/decline/",
        views.decline_review_request,
        name="decline_review",
    ),
    path(
        "requests/<int:assignment_id>/decline/suggest/",
        views.suggest_reviewers,
        name="suggest_reviewers",
    ),
    path(
        "requests/<int:assignment_id>/thanks/",
        views.thanks_review,
        name="thanks_review",
    ),
    path(
        "requests/<int:assignment_id>/annotation/",
        views.hypothesis_review,
        name="hypothesis_review",
    ),
    path("requests/<int:assignment_id>/", views.do_review, name="do_review"),
    path(
        "requests/<int:assignment_id>/upload_file/",
        views.upload_review_file,
        name="upload_review_file",
    ),
    path(
        "author/<int:article_id>/",
        views.author_view_reviews,
        name="review_author_view",
    ),
    path(
        "editor/<int:article_id>/file_download/<int:file_id>/",
        views.editor_article_file,
        name="editor_file_download",
    ),
    path(
        "reviewer/<int:assignment_id>/file_download/<int:file_id>/",
        views.reviewer_article_file,
        name="review_file_download",
    ),
    re_path(
        r"^review/(?P<assignment_id>\d+)/review_attachment/(?P<file_uuid>[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}(?:\.[a-zA-Z0-9]+)?)/$",
        views.review_attachment_download,
        name="review_attachment_download",
    ),
    path(
        "reviewer/<int:assignment_id>/file_download/all/",
        views.review_download_all_files,
        name="review_download_all_files",
    ),
    re_path(
        r"^article/(?P<article_id>\d+)/decision/(?P<decision>{decision_options})/access_denied/$".format(
            decision_options="|".join(decision.value for decision in EditorialDecisions)
        ),
        views.review_warning,
        name="review_warning",
    ),
    # Review forms
    path("manager/forms/", views.review_forms, name="review_review_forms"),
    path(
        "manager/form/<int:form_id>/",
        views.edit_review_form,
        name="edit_review_form",
    ),
    path(
        "manager/form/<int:form_id>/preview/",
        views.preview_form,
        name="preview_form",
    ),
    path(
        "manager/form/<int:form_id>/order_elements/",
        views.order_review_elements,
        name="order_review_elements",
    ),
    path(
        "manager/form/<int:form_id>/element/<int:element_id>/",
        views.edit_review_form,
        name="edit_review_form_element",
    ),
    path(
        "article/<int:article_id>/decision_helper/",
        views.decision_helper,
        name="decision_helper",
    ),
    path(
        "article/<int:article_id>/csv-import/",
        views.upload_reviewers_from_csv,
        name="upload_reviewers_from_csv",
    ),
    # Review Sharing
    path(
        "article/<int:article_id>/share/",
        views.editor_share_reviews,
        name="editor_share_reviews",
    ),
    path(
        "article/<int:article_id>/share/reviewer/",
        views.reviewer_share_reviews,
        name="reviewer_share_reviews",
    ),
    path(
        "article/<int:article_id>/share/download/<int:review_id>/",
        views.reviewer_shared_review_download,
        name="reviewer_shared_review_download",
    ),
]
