# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-21 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20180207_1525'),
        ('proofing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proofingtask',
            name='proofed_files',
            field=models.ManyToManyField(to='core.File'),
        ),
    ]
