# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-21 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20180207_1525'),
        ('proofing', '0002_proofingtask_proofed_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='typesetterproofingtask',
            name='files',
            field=models.ManyToManyField(to='core.File'),
        ),
    ]
