# Generated by Django 2.2 on 2019-05-08 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proofing', '0003_typesetterproofingtask_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proofingassignment',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proofing_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proofingtask',
            name='round',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proofing.ProofingRound'),
        ),
    ]
