[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "Janeway"
version = "1.8.0"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "Django>=5.2",
]

[project.optional-dependencies]
dev = [
    "ruff==0.16.4",
]

[tool.ruff]
line-length = 88 # Matches ruff and black formatting
target-version = "py311"
include = ["src/**/*.py"]
exclude = [
    "src/__pycache__",
    "src/static",
    "src/media",
    "src/files",
    "src/plugins",
    "src/ebooklib",
    "src/foundationform",
    "src/transform/cassius",
]
[tool.tox]
env_list = ["py311", "py312", "py313", "py314"]
[tool.tox.testenv]
commands = [
    "python src/manage.py test"
]
[tool.tox.testenv.deps]
list = ["Django~=5.2.17", "file:requirements.txt"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true
