# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-17 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typesettask',
            name='due',
            field=models.DateField(null=True),
        ),
    ]
