# Generated by Django 3.2.16 on 2023-03-17 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_auto_20200529_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionassignment',
            name='accepted_by_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.typesettask'),
        ),
    ]
