# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-04-03 21:19
from __future__ import unicode_literals

from django.db import migrations


def update_handshake_url(apps, schema_editor):
    WorkflowElement = apps.get_model("core", "WorkflowElement")

    updates = [
        {'from': 'typesetting_article', 'to': 'typesetting_articles'},
    ]

    for update in updates:
        elements_to_update = WorkflowElement.objects.filter(
            handshake_url=update.get('from')
        )
        for element_to_update in elements_to_update:
            element_to_update.handshake_url = update.get('to')
            element_to_update.save()


class Migration(migrations.Migration):

    dependencies = [
        ('typesetting', '0006_auto_20200227_1051'),
    ]

    operations = [
        migrations.RunPython(
            update_handshake_url,
            reverse_code=migrations.RunPython.noop
        ),
    ]
