# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-16 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typesetting', '0007_typesettingassignment_cancelled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleyproofing',
            options={'ordering': ('assigned', 'accepted', 'pk')},
        ),
        migrations.AlterField(
            model_name='galleyproofing',
            name='annotated_files',
            field=models.ManyToManyField(blank=True, to='core.File'),
        ),
        migrations.AlterField(
            model_name='galleyproofing',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='galleyproofing',
            name='proofed_files',
            field=models.ManyToManyField(blank=True, to='core.Galley'),
        ),
    ]
