# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-04-03 21:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('typesetting', '0008_auto_20200316_1231'),
        ('typesetting', '0007_update_handshake_url'),
    ]

    operations = [
    ]
