# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-31 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cron', '0003_auto_20171121_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='template_name',
            field=models.CharField(
                help_text="The name of the email template. "
                          "If it does not exist, you will be "
                          "asked to create it. "
                          "Should have no spaces.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='type',
            field=models.CharField(choices=[('review', 'Review (Invited)'), ('accepted-review', 'Review (Accepted)'), ('revisions', 'Revision')], max_length=100),
        ),
        migrations.AlterField(
            model_name='sentreminder',
            name='type',
            field=models.CharField(choices=[('review', 'Review (Invited)'), ('accepted-review', 'Review (Accepted)'), ('revisions', 'Revision')], max_length=100),
        ),
    ]
