# Generated by Django 2.2 on 2019-05-08 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cron', '0003_auto_20171121_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crontask',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='submission.Article'),
        ),
    ]
