# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-14 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cron', '0004_auto_20210831_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentreminder',
            name='reminder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cron.Reminder'),
        ),
    ]
