__copyright__ = "Copyright 2017 Birkbeck, University of London"
__author__ = "Martin Paul Eve & Andy Byers"
__license__ = "AGPL v3"
__maintainer__ = "Birkbeck Centre for Technology and Publishing"


from django.urls import path
from django.urls import re_path

from repository import views

urlpatterns = [
    path("dashboard/", views.repository_dashboard, name="repository_dashboard"),
    path(
        "dashboard/<int:preprint_id>/",
        views.repository_author_article,
        name="repository_author_article",
    ),
    re_path(
        r"^dashboard/(?P<preprint_id>\d+)/action/(?P<action>correction|version|metadata_correction)/$",
        views.repository_submit_update,
        name="repository_submit_update",
    ),
    path("about/", views.repository_about, name="repository_about"),
    path("search/", views.repository_search, name="repository_search"),
    re_path(
        r"^search/(?P<search_term>.*)/$",
        views.repository_search,
        name="repository_search_with_term",
    ),
    path(
        "view/<int:preprint_id>/",
        views.repository_preprint,
        name="repository_preprint",
    ),
    path("view/<int:preprint_id>/pdf/", views.repository_pdf, name="repository_pdf"),
    path(
        "object/<int:preprint_id>/download/<int:file_id>/",
        views.repository_file_download,
        name="repository_file_download",
    ),
    path("list/", views.repository_list, name="repository_list"),
    path(
        "list/subjects/",
        views.repository_subject_list,
        name="repository_subject_list",
    ),
    path(
        "list/<int:subject_id>/",
        views.redirect_old_subject,
        name="repository_list_subject",
    ),
    path("editors/", views.preprints_editors, name="preprints_editors"),
    path("submit/start/", views.repository_submit, name="repository_submit"),
    path("submit/info/", views.repository_info, name="repository_info"),
    path(
        "submit/<int:preprint_id>/",
        views.repository_info,
        name="repository_submit_with_id",
    ),
    path(
        "submit/<int:preprint_id>/authors/",
        views.repository_authors,
        name="repository_authors",
    ),
    re_path(
        r"^submit/(?P<preprint_id>\d+)/authors/delete/(?P<redirect_string>[-\w]+)/$",
        views.repository_delete_author,
        name="repository_delete_author",
    ),
    path(
        "submit/<int:preprint_id>/authors/order/",
        views.preprints_author_order,
        name="preprints_author_order",
    ),
    path(
        "submit/<int:preprint_id>/files/",
        views.repository_files,
        name="repository_files",
    ),
    path(
        "submit/<int:preprint_id>/review/",
        views.repository_review,
        name="repository_review",
    ),
    path("manager/", views.preprints_manager, name="preprints_manager"),
    path(
        "manager/<int:preprint_id>/",
        views.repository_manager_article,
        name="repository_manager_article",
    ),
    path(
        "manager/<int:preprint_id>/edit/metadata/",
        views.repository_edit_metadata,
        name="repository_edit_metadata",
    ),
    path(
        "manager/<int:preprint_id>/edit/authors/<int:author_id>/",
        views.repository_edit_author,
        name="repository_edit_authors",
    ),
    path(
        "manager/<int:preprint_id>/add/author/",
        views.repository_edit_author,
        name="repository_add_author",
    ),
    path(
        "manager/<int:preprint_id>/author/order/",
        views.reorder_preprint_authors,
        name="repository_manager_order_authors",
    ),
    path(
        "manager/<int:preprint_id>/author/delete/",
        views.delete_preprint_author,
        name="repository_manager_delete_author",
    ),
    path(
        "manager/submission-types/",
        views.submission_type_list,
        name="submission_type_list",
    ),
    path(
        "manager/submission-types/create/",
        views.edit_submission_type,
        name="create_submission_type",
    ),
    path(
        "manager/submission-types/<int:pk>/edit/",
        views.edit_submission_type,
        name="edit_submission_type",
    ),
    path(
        "manager/submission-types/<int:pk>/delete/",
        views.delete_submission_type,
        name="delete_submission_type",
    ),
    # Review
    path(
        "manager/reviewers/",
        views.manage_reviewers,
        name="repository_manage_reviewers",
    ),
    path(
        "manager/<int:preprint_id>/review/",
        views.list_reviews,
        name="repository_list_reviews",
    ),
    path(
        "manager/<int:preprint_id>/review/new/",
        views.manage_review,
        name="repository_new_review",
    ),
    path(
        "manager/<int:preprint_id>/review/<int:review_id>/detail/",
        views.review_detail,
        name="repository_review_detail",
    ),
    path(
        "manager/<int:preprint_id>/review/<int:review_id>/notify/",
        views.notify_reviewer,
        name="repository_notify_reviewer",
    ),
    path(
        "manager/<int:preprint_id>/review/<int:review_id>/edit_comment/",
        views.edit_review_comment,
        name="repository_edit_review_comment",
    ),
    re_path(
        r"^review/(?P<review_id>\d+)/access_code/(?P<access_code>[0-9a-f-]+)/$",
        views.submit_review,
        name="repository_submit_review",
    ),
    re_path(
        r"^review/(?P<review_id>\d+)/access_code/(?P<access_code>[0-9a-f-]+)/download/$",
        views.download_review_file,
        name="repository_download_review_file",
    ),
    path(
        "manager/<int:preprint_id>/download/<int:file_id>/",
        views.repository_download_file,
        name="repository_download_file",
    ),
    path(
        "manager/<int:preprint_id>/notification/",
        views.repository_notification,
        name="repository_notification",
    ),
    path(
        "manager/<int:preprint_id>/log/",
        views.repository_preprint_log,
        name="repository_preprint_log",
    ),
    path(
        "manager/comments/",
        views.repository_manager_comment_list,
        name="repository_manager_comment_list",
    ),
    path(
        "manager/comments/<int:preprint_id>/",
        views.repository_manager_comment_list,
        name="repository_manager_comment_list_filtered",
    ),
    path(
        "manager/comments/reviewed/",
        views.repository_manager_comment_list,
        {"show_reviewed": True},
        name="repository_manager_comment_list_reviewed",
    ),
    path(
        "manager/comments/<int:preprint_id>/reviewed/",
        views.repository_manager_comment_list,
        {"show_reviewed": True},
        name="repository_manager_comment_list_filtered_reviewed",
    ),
    path(
        "manager/<int:preprint_id>/supp_files/",
        views.manage_supplementary_files,
        name="repository_manage_supplementary_files",
    ),
    path(
        "manager/<int:preprint_id>/supp_files/new/",
        views.new_supplementary_file,
        name="repository_new_supplementary_files",
    ),
    path(
        "manager/<int:preprint_id>/supp_files/order/",
        views.order_supplementary_files,
        name="repository_order_supplementary_files",
    ),
    path(
        "manager/<int:preprint_id>/supp_files/delete/",
        views.delete_supplementary_file,
        name="repository_delete_supplementary_files",
    ),
    path("manager/licenses/", views.repository_licenses, name="repository_licenses"),
    path("manager/subjects/", views.repository_subjects, name="repository_subjects"),
    path(
        "manager/subjects/delete/",
        views.repository_delete_subject,
        name="repository_delete_subject",
    ),
    path(
        "manager/subjects/<int:subject_id>/",
        views.repository_subjects,
        name="repository_subjects_with_id",
    ),
    path(
        "manager/rejected/",
        views.repository_rejected_submissions,
        name="repository_rejected_submissions",
    ),
    path(
        "manager/orphans/",
        views.orphaned_preprints,
        name="preprints_orphaned_preprints",
    ),
    path("manager/versions/", views.version_queue, name="version_queue"),
    path("wizard/", views.repository_wizard, name="repository_wizard"),
    re_path(
        r"^wizard/repository/(?P<short_name>[-\w]+)/step/(?P<step>\d+)/$",
        views.repository_wizard,
        name="repository_wizard_with_id",
    ),
    path("manager/fields/", views.repository_fields, name="repository_fields"),
    path(
        "manager/fields/delete/",
        views.repository_delete_field,
        name="repository_delete_field",
    ),
    path(
        "manager/fields/order/",
        views.repository_order_fields,
        name="repository_order_fields",
    ),
    path(
        "manager/fields/<int:field_id>/",
        views.repository_fields,
        name="repository_fields_with_id",
    ),
    path(
        "manager/<int:preprint_id>/send_to_journal/",
        views.send_preprint_to_journal,
        name="repository_send_to_a_journal",
    ),
    path(
        "manager/<int:preprint_id>/send_to_journal/<int:journal_id>/",
        views.send_preprint_to_journal,
        name="repository_send_to_journal",
    ),
    path(
        "manager/recommendations/",
        views.list_review_recommendations,
        name="repository_list_review_recommendations",
    ),
    path(
        "manager/recommendations/create/",
        views.manage_review_recommendation,
        name="repository_create_review_recommendation",
    ),
    path(
        "manager/recommendations/<int:recommendation_id>/edit/",
        views.manage_review_recommendation,
        name="repository_edit_review_recommendation",
    ),
    # Popup email
    path(
        "email/user/<int:user_id>/preprint/<int:preprint_id>/",
        views.send_user_email,
        name="send_user_email_preprint",
    ),
    re_path(
        r"^hierarchy/(?P<rou_code>[\w-]+)/$",
        views.rou_hierarchy_view,
        name="rou_hierarchy",
    ),
    path(
        "hierarchy/",
        views.rou_hierarchy_view,
        name="rou_hierarchy",
    ),
    re_path(
        r"^(?P<rou_code>[\w-]+)/$",
        views.repository_home,
        name="repository_home_by_rou",
    ),
    re_path(
        r"^(?P<rou_code>[\w-]+)/list$",
        views.preprints_by_rou,
        name="repository_preprints_by_rou",
    ),
]
