on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v4

      - name: Set up python environments
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install all dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --src lib/ -r requirements.txt -r dev-requirements.txt

      - name: Check code formatting with Ruff
        run: |
          echo "Running formatting check..."
          ruff format --check .
          echo "Formatting check completed."

      - name: Run Django unit tests
        run: |
          export DB_VENDOR=sqlite
          echo "Running unit tests"
          python src/manage.py test
          echo "Test run completed."

