# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-08 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0019_auto_20171130_1115'),
        ('metrics', '0003_auto_20170921_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='altmetric',
            name='pid',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='altmetric',
            unique_together=set([('article', 'source', 'pid')]),
        ),
    ]
