# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-05 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0004_auto_20180308_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleaccess',
            name='country',
            field=models.CharField(default='OTHER', max_length=6),
            preserve_default=False,
        ),
    ]
