# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-27 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_merge_20190405_1549'),
        ('metrics', '0004_auto_20180308_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleaccess',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Country'),
        ),
    ]
