# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-18 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0007_auto_20191115_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlelink',
            name='issue',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='articlelink',
            name='volume',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
