# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-19 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0007_articlelink_booklink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlelink',
            name='year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='booklink',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
