# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-11 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0008_auto_20191119_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='altmetric',
            name='pid',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='articlelink',
            name='issue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='articlelink',
            name='journal_issn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='articlelink',
            name='volume',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
