# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-08-21 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0002_auto_20200820_1400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-posted', 'pk')},
        ),
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ('-started', 'pk')},
        ),
        migrations.AddField(
            model_name='thread',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
