# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-08-11 11:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discussion', '0004_auto_20200925_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='posters',
            field=models.ManyToManyField(blank=True, related_name='posters', to=settings.AUTH_USER_MODEL),
        ),
    ]
