# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-27 15:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='press',
            name='password_length',
            field=models.PositiveIntegerField(default=12, validators=[django.core.validators.MinValueValidator(9)]),
        ),
        migrations.AddField(
            model_name='press',
            name='password_number',
            field=models.BooleanField(default=False, help_text='If set, passwords must include one number.'),
        ),
        migrations.AddField(
            model_name='press',
            name='password_upper',
            field=models.BooleanField(default=False, help_text='If set, passwords must include one upper case.'),
        ),
    ]
