# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0002_auto_20170813_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='press',
            name='carousel_news_items',
            field=models.ManyToManyField(blank=True, null=True, to='comms.NewsItem'),
        ),
    ]
