# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 12:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0002_auto_20170727_1504'),
        ('press', '0003_auto_20170829_1501'),
    ]

    operations = [
    ]
