# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 08:34
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import press.models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0004_merge_20170908_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='press',
            name='enable_preprints',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='press',
            name='default_carousel_image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/ajrbyers/Code/janeway/src/media'), upload_to=press.models.cover_images_upload_path),
        ),
        migrations.AlterField(
            model_name='press',
            name='favicon',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/ajrbyers/Code/janeway/src/media'), upload_to=press.models.cover_images_upload_path),
        ),
        migrations.AlterField(
            model_name='press',
            name='password_reset_text',
            field=models.TextField(blank=True, default='<p>Dear {{ reset_token.account.full_name }},<br><br>A password reset for your account has been requested. You can reset your password at the following link:</p><p><a href="{{ request.press_base_url }}{% url \'core_reset_password\' reset_token.token %}">{{ request.press_base_url }}{% url \'core_reset_password\' reset_token.token %}</a><br><br>{{request.press.name}}</p>', null=True),
        ),
        migrations.AlterField(
            model_name='press',
            name='registration_text',
            field=models.TextField(blank=True, default='<p>Dear {{ user.full_name }}<br><br>Thank you for registering for {{ request.press.name }}. You can confirm your account at the following link:</p><p><br><a href="{{ request.press_base_url }}{% url \'core_confirm_account\' user.confirmation_code %}">{{ request.press_base_url }}{% url \'core_confirm_account\' user.confirmation_code %}</a><br>{{request.press.name}}</p>', null=True),
        ),
    ]
