# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0005_auto_20170929_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='press',
            name='preprints_about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
