# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 12:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('press', '0008_auto_20171005_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='press',
            name='preprint_editors',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
