# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0010_presssetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='press',
            name='preprint_editors',
        ),
    ]
