# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0011_remove_press_preprint_editors'),
    ]

    operations = [
        migrations.AddField(
            model_name='presssetting',
            name='is_boolean',
            field=models.BooleanField(default=False),
        ),
    ]
