# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0017_auto_20171114_1502'),
        ('press', '0013_press_preprint_decline'),
    ]

    operations = [
        migrations.AddField(
            model_name='press',
            name='homepage_preprints',
            field=models.ManyToManyField(to='submission.Article', blank=True),
        ),
        migrations.AddField(
            model_name='press',
            name='random_homepage_preprints',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='press',
            name='preprint_decline',
            field=models.TextField(blank=True, default='<p>Dear {{ article.owner.full_name }},</p><p>Unfortunately we have decided not to publish your preprint.</p><p>Regards,</p><p>{{ request.press.name }} Team</p>', null=True),
        ),
    ]
