# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-08 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0014_auto_20171127_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='press',
            name='theme',
            field=models.CharField(default='default', max_length=255),
        ),
    ]
