# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-19 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0015_auto_20180208_1442'),
        ('press', '0015_press_tracking_code'),
    ]

    operations = [
    ]
