# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-16 11:44
from __future__ import unicode_literals

import core.file_system
from django.db import migrations, models
import press.models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0016_merge_20180319_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='press',
            name='default_carousel_image',
            field=models.ImageField(blank=True, null=True, storage=core.file_system.JanewayFileSystemStorage(), upload_to=press.models.cover_images_upload_path),
        ),
        migrations.AlterField(
            model_name='press',
            name='favicon',
            field=models.ImageField(blank=True, null=True, storage=core.file_system.JanewayFileSystemStorage(), upload_to=press.models.cover_images_upload_path),
        ),
    ]
