# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-23 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0017_auto_20181116_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='press',
            name='domain',
            field=models.CharField(default='www.example.com', max_length=255, unique=True),
        ),
    ]
