# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-20 22:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0019_auto_20181218_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='press',
            name='password_length',
            field=models.PositiveIntegerField(default=6, validators=[django.core.validators.MinValueValidator(6)]),
        ),
    ]
