# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-29 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0020_auto_20190319_1555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='press',
            options={'verbose_name_plural': 'presses'},
        ),
    ]
