# Generated by Django 2.2 on 2019-05-08 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0021_auto_20190329_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='press',
            name='carousel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='press', to='carousel.Carousel'),
        ),
        migrations.AlterField(
            model_name='press',
            name='thumbnail_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='press_thumbnail_image', to='core.File', verbose_name='Press Logo'),
        ),
    ]
