# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-18 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0021_auto_20190329_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='press',
            name='disable_journals',
            field=models.BooleanField(default=False, help_text='If enabled, the journals page will no longer render.'),
        ),
    ]
