# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-22 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0021_auto_20190329_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='press',
            name='order_journals_alphabetically',
            field=models.BooleanField(default=True),
        ),
    ]
