# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-11 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0020_auto_20190220_1443'),
        ('press', '0021_auto_20190329_1202'),
    ]

    operations = [
    ]
