# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-29 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0023_auto_20210721_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='press',
            name='theme',
            field=models.CharField(default='OLH', max_length=255),
        ),
    ]
