# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-14 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0024_update_press_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='press',
            name='password_reset_text',
            field=models.TextField(blank=True, default='<p>Dear {{ reset_token.account.full_name }},<br><br>A password reset for your account has been requested. You can reset your password at the following link:</p><p><a href="{% site_url \'core_reset_password\' reset_token.token %}">{% site_url \'core_reset_password\' reset_token.token %}</a><br><br>{{request.press.name}}</p>', null=True),
        ),
        migrations.AlterField(
            model_name='press',
            name='preprint_publication',
            field=models.TextField(blank=True, default='<p>Dear {{ article.owner.full_name }},</p><p>Your preprint has been published on {{ request.press.name }}. It is now available on our <a href="{% site_url \'preprints_article\' article.pk %}">website</a>.</p><p>Regards,</p><p>{{ request.press.name }} Team</p>', null=True),
        ),
        migrations.AlterField(
            model_name='press',
            name='registration_text',
            field=models.TextField(blank=True, default='<p>Dear {{ user.full_name }}<br><br>Thank you for registering for {{ request.press.name }}. You can confirm your account at the following link:</p><p><br><a href="{% site_url \'core_confirm_account\' user.confirmation_code %}">{% site_url \'core_confirm_account\' user.confirmation_code %}</a><br>{{request.press.name}}</p>', null=True),
        ),
    ]
