# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-11 15:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0025_auto_20200814_1433'),
        ('press', '0024_auto_20210729_0908'),
    ]

    operations = [
    ]
