# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-01-07 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0026_merge_20210811_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='press',
            name='domain',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
