# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-03-08 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0027_auto_20220107_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='press',
            name='description',
            field=models.TextField(blank=True, help_text='This will appear in web search results and on social media when the press URL is shared', null=True, verbose_name='Publisher description'),
        ),
        migrations.AlterField(
            model_name='press',
            name='footer_description',
            field=models.TextField(blank=True, help_text='Additional HTML for the press footer.', null=True, verbose_name='Footer text'),
        ),
    ]
