# Generated by Django 3.2.20 on 2023-11-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0031_press_journal_footer_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='press',
            name='description',
            field=models.TextField(blank=True, default='', help_text='This will appear in web search results and on social media when the press URL is shared', verbose_name='Publisher description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='press',
            name='footer_description',
            field=models.TextField(blank=True, default='', help_text='Additional HTML for the press footer.', verbose_name='Footer text'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='press',
            name='journal_footer_text',
            field=models.TextField(blank=True, default='', help_text='Text that will appear in the footer of every journal, to display publisher address or other essential info. ', verbose_name='Journal footer text'),
            preserve_default=False,
        ),
    ]
