# Generated by Django 3.2.20 on 2024-02-01 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0031_staffgroup_staffgroupmember'),
        ('press', '0032_auto_20231116_1057'),
    ]

    operations = [
    ]
