# Generated by Django 3.2.20 on 2024-03-12 09:22

import core.model_utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0032_auto_20231116_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='press',
            name='description',
            field=core.model_utils.JanewayBleachField(blank=True, help_text='This will appear in web search results and on social media when the press URL is shared', verbose_name='Publisher description'),
        ),
        migrations.AlterField(
            model_name='press',
            name='footer_description',
            field=core.model_utils.JanewayBleachField(blank=True, help_text='Additional HTML for the press footer.', verbose_name='Footer text'),
        ),
        migrations.AlterField(
            model_name='press',
            name='journal_footer_text',
            field=core.model_utils.JanewayBleachField(blank=True, help_text='Text that will appear in the footer of every journal, to display publisher address or other essential info. ', verbose_name='Journal footer text'),
        ),
        migrations.AlterField(
            model_name='press',
            name='password_reset_text',
            field=core.model_utils.JanewayBleachField(blank=True, default='<p>Dear {{ reset_token.account.full_name }},<br><br>A password reset for your account has been requested. You can reset your password at the following link:</p><p><a href="{% site_url \'core_reset_password\' reset_token.token %}">{% site_url \'core_reset_password\' reset_token.token %}</a><br><br>{{request.press.name}}</p>', null=True),
        ),
        migrations.AlterField(
            model_name='press',
            name='preprint_decline',
            field=core.model_utils.JanewayBleachField(blank=True, default='<p>Dear {{ article.owner.full_name }},</p><p>Unfortunately we have decided not to publish your preprint.</p><p>Regards,</p><p>{{ request.press.name }} Team</p>', null=True),
        ),
        migrations.AlterField(
            model_name='press',
            name='preprint_publication',
            field=core.model_utils.JanewayBleachField(blank=True, default='<p>Dear {{ article.owner.full_name }},</p><p>Your preprint has been published on {{ request.press.name }}. It is now available on our <a href="{% site_url \'preprints_article\' article.pk %}">website</a>.</p><p>Regards,</p><p>{{ request.press.name }} Team</p>', null=True),
        ),
        migrations.AlterField(
            model_name='press',
            name='preprint_start',
            field=core.model_utils.JanewayBleachField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='press',
            name='preprint_submission',
            field=core.model_utils.JanewayBleachField(blank=True, default='<p>Dear {{ article.owner.full_name }},</p><p>Thank you for your preprint submission. Our Preprint Editor has been notified and will review it before making a decision.</p><p>Regards,</p><p>{{ request.press.name }} Team</p>', null=True),
        ),
        migrations.AlterField(
            model_name='press',
            name='preprints_about',
            field=core.model_utils.JanewayBleachField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='press',
            name='registration_text',
            field=core.model_utils.JanewayBleachField(blank=True, default='<p>Dear {{ user.full_name }}<br><br>Thank you for registering for {{ request.press.name }}. You can confirm your account at the following link:</p><p><br><a href="{% site_url \'core_confirm_account\' user.confirmation_code %}">{% site_url \'core_confirm_account\' user.confirmation_code %}</a><br>{{request.press.name}}</p>', null=True),
        ),
    ]
