# Generated by Django 3.2.20 on 2024-05-06 09:04

import core.model_utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0033_merge_20240201_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffgroup',
            name='press',
            field=models.ForeignKey(default=core.model_utils.default_press_id, on_delete=django.db.models.deletion.CASCADE, to='press.press'),
        ),
    ]
