# Generated by Django 3.2.20 on 2024-03-15 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0033_auto_20240312_0922'),
        ('press', '0033_merge_20240201_1108'),
    ]

    operations = [
    ]
