# Generated by Django 4.2.16 on 2025-01-30 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0035_alter_staffgroup_press'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='press',
            name='password_reset_text',
        ),
        migrations.RemoveField(
            model_name='press',
            name='registration_text',
        ),
    ]
