# Generated by Django 4.2.11 on 2024-06-13 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0034_alter_staffgroup_press'),
        ('press', '0035_alter_staffgroup_press'),
    ]

    operations = [
    ]
