# Generated by Django 4.2.20 on 2025-09-26 09:53

import core.model_utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("press", "0036_remove_press_password_reset_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="press",
            name="allow_journal_a11y_info",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, journals can have their own accessibility information as well.",
                verbose_name="Allow Journal Accessibility Information",
            ),
        ),
        migrations.AddField(
            model_name="press",
            name="ally_info",
            field=core.model_utils.JanewayBleachField(
                blank=True,
                help_text="This is information about the accessiblity of user-content.  It will appear on the accessibility page under the press name.",
                verbose_name="Press Accessibility Information",
            ),
        ),
    ]
