# Generated by Django 4.2.22 on 2025-09-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("press", "0036_remove_press_password_reset_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="press",
            name="order_journals_az",
            field=models.BooleanField(
                default=False,
                help_text="Whether to order journals A-Z by journal name and ignore manually set sequence. Does not work for translated journal names.",
                verbose_name="Order journals A-Z",
            ),
        ),
    ]
