# Generated by Django 2.2 on 2019-05-08 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('featured', '0002_auto_20170711_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredarticle',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
