# Generated by Django 3.2.16 on 2023-01-20 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('featured', '0002_auto_20170711_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredarticle',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
