# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewformelement',
            name='default_visibility',
            field=models.BooleanField(default=True, help_text='If true, this setting will be availableto the author automatically, if false it willbe hidden to the author by default.'),
        ),
    ]
