# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-30 13:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_reviewassignment_display_review_file'),
        ('review', '0003_auto_20180614_1039'),
    ]

    operations = [
    ]
