# Generated by Django 2.2 on 2019-05-08 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_merge_20180716_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewassignment',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='review.ReviewForm'),
        ),
        migrations.AlterField(
            model_name='reviewassignment',
            name='review_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.File'),
        ),
        migrations.AlterField(
            model_name='reviewassignment',
            name='review_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='review.ReviewRound'),
        ),
        migrations.AlterField(
            model_name='reviewassignmentanswer',
            name='element',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='review.ReviewFormElement'),
        ),
    ]
