# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-01 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_auto_20200529_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewformelement',
            name='help_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
