# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-07 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_null_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewform',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
