# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-13 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0011_reviewassignment_permission_to_make_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewassignment',
            name='display_public',
            field=models.BooleanField(default=False, help_text='Whether this review should be publicly displayed.'),
        ),
    ]
