# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-31 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0012_auto_20210330_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decisiondraft',
            name='closed',
        ),
        migrations.AlterField(
            model_name='decisiondraft',
            name='decision',
            field=models.CharField(choices=[('accept', 'Accept Without Revisions'), ('minor_revisions', 'Minor Revisions Required'), ('major_revisions', 'Major Revisions Required'), ('reject', 'Reject')], max_length=100),
        ),
    ]
