# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-17 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0016_auto_20210510_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revisionrequest',
            name='date_requested',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
