# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-13 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0016_auto_20210510_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewassignment',
            name='display_public',
            field=models.BooleanField(default=False, help_text='Whether this review should be publicly displayed.'),
        ),
        migrations.AddField(
            model_name='reviewassignment',
            name='permission_to_make_public',
            field=models.BooleanField(default=False,
                                      help_text='This journal has a policy of sharing reviews openly alongside the published article to aid in transparency. If you give permission here and the article is published, your name and review will be visible.'),
        ),
        migrations.AlterField(
            model_name='revisionrequest',
            name='date_requested',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
