# Generated by Django 3.2.16 on 2023-01-20 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_auto_20230120_1546'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0017_reviewassignment_display_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decisiondraft',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='decisiondraft',
            name='section_editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_section_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reviewassignment',
            name='review_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.file'),
        ),
        migrations.AlterField(
            model_name='reviewassignment',
            name='review_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='review.reviewround'),
        ),
        migrations.AlterField(
            model_name='reviewerrating',
            name='rater',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='revisionaction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='revisionrequest',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
