# Generated by Django 3.2.16 on 2023-05-18 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0018_auto_20230120_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewform',
            name='slug',
        ),
    ]
