# Generated by Django 3.2.16 on 2023-05-10 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0019_auto_20230418_1113'),
        ('review', '0019_decision_decline_rewording'),
    ]

    operations = [
    ]
