# Generated by Django 3.2.16 on 2023-05-23 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0019_remove_reviewform_slug'),
        ('review', '0020_merge_20230510_1129'),
    ]

    operations = [
    ]
