# Generated by Django 4.2.16 on 2024-12-04 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('submission', '0084_remove_article_jats_article_type_and_more'),
        ('review', '0023_auto_20240312_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorAssignmentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editor_type', models.CharField(choices=[('editor', 'Editor'), ('section-editor', 'Section Editor')], max_length=20)),
                ('notified', models.BooleanField(default=False)),
                ('date_requested', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_due', models.DateField(null=True)),
                ('date_accepted', models.DateTimeField(blank=True, null=True)),
                ('date_declined', models.DateTimeField(blank=True, null=True)),
                ('date_complete', models.DateTimeField(blank=True, null=True)),
                ('date_reminded', models.DateField(blank=True, null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission.article')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('editor_assignment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='review.editorassignment')),
                ('requesting_editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requesting_editor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
