# Generated by Django 3.2.20 on 2024-05-08 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0023_auto_20240506_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorassignmentrequest',
            name='requesting_editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requesting_editor', to=settings.AUTH_USER_MODEL),
        ),
    ]
