# Generated by Django 4.2.20 on 2025-04-25 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0023_auto_20240312_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frozenreviewformelement',
            name='width',
        ),
        migrations.RemoveField(
            model_name='reviewformelement',
            name='width',
        ),
    ]
