# Generated by Django 4.2.22 on 2025-08-29 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0108_workflowlog_user"),
        ("review", "0024_remove_frozenreviewformelement_width_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewAssignmentAnswerFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "edited",
                    models.BooleanField(
                        default=False,
                        help_text="This file is an edit, rather than the original answer",
                    ),
                ),
                (
                    "answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="review.reviewassignmentanswer",
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="review_attchments",
                        to="core.file",
                    ),
                ),
            ],
            options={
                "unique_together": {("answer", "edited")},
            },
        ),
    ]
