# Generated by Django 4.2.20 on 2025-12-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0024_remove_frozenreviewformelement_width_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revisionrequest',
            name='actions',
            field=models.ManyToManyField(blank=True, to='review.revisionaction'),
        ),
    ]
