# Generated by Django 3.2.20 on 2024-05-08 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0024_editorassignmentrequest_requesting_editor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='editorassignmentrequest',
            unique_together=set(),
        ),
    ]
