# Generated by Django 4.2.11 on 2024-06-13 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0023_auto_20240312_0922'),
        ('review', '0025_alter_editorassignmentrequest_unique_together'),
    ]

    operations = [
    ]
