# Generated by Django 4.2.29 on 2026-06-03 22:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0025_alter_revisionrequest_actions"),
        ("review", "0025_reviewassignmentanswerfile"),
    ]

    operations = []
