# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-19 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
        ('journal', '0002_auto_20170711_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='pinned_articles',
            field=models.ManyToManyField(related_name='pinned_articles', to='submission.Article'),
        ),
    ]
