# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-29 23:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0019_auto_20171130_1115'),
        ('journal', '0006_auto_20171115_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleordering',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='submission.Section'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='journal',
            name='current_issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_issue', to='journal.Issue'),
        ),
        migrations.AlterUniqueTogether(
            name='articleordering',
            unique_together=set([('article',)]),
        ),
    ]
