# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-08 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_auto_20171115_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='current_issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_issue', to='journal.Issue'),
        ),
    ]
