# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-29 23:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0019_auto_20171130_1115'),
        ('journal', '0007_auto_20180129_2342'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='articleordering',
            unique_together=set([('article', 'issue', 'section')]),
        ),
    ]
