# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-08 14:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_auto_20180208_1225'),
        ('journal', '0008_auto_20180129_2352'),
    ]

    operations = [
    ]
