# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-09 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_merge_20180208_1443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articleordering',
            options={'ordering': ('order', 'section')},
        ),
        migrations.AlterModelOptions(
            name='sectionordering',
            options={'ordering': ('order', 'section')},
        ),
        migrations.AddField(
            model_name='journal',
            name='contact_info',
            field=models.TextField(blank=True, null=True, verbose_name='Contact Information'),
        ),
    ]
