# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-16 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0010_auto_20180709_1207'),
        ('journal', '0010_auto_20180412_1544'),
    ]

    operations = [
    ]
