# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-24 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0011_merge_20180716_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
