# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-08 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0012_auto_20180824_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='nav_collections',
            field=models.BooleanField(default=False),
        ),
    ]
