# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-13 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0013_journal_nav_collections'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='disable_metrics_display',
            field=models.BooleanField(default=False),
        ),
    ]
