# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-15 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0015_auto_20181108_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='full_width_navbar',
            field=models.BooleanField(default=False),
        ),
    ]
