# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-20 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0017_file_fields_for_the_last_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='disable_html_downloads',
            field=models.BooleanField(
                default=False,
                help_text='Used to disable download links for HTML files on the Article page.',
            ),
        ),
    ]
