# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-29 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0018_journal_disable_html_downloads'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='view_pdf_button',
            field=models.BooleanField(default=False, help_text='Enables a "View PDF" link on article pages.'),
        ),
    ]
