# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-08 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0020_journal_is_secure'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='enable_correspondence_authors',
            field=models.BooleanField(default=True),
        ),
    ]
