# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-11 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_merge_20190201_1533'),
        ('journal', '0022_journal_is_conference'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueGalley',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.File')),
                ('issue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='journal.Issue')),
            ],
        ),
    ]
