# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-04 09:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0023_issuegalley'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuegalley',
            name='issue',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='galley', to='journal.Issue'),
        ),
    ]
