# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-21 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0024_auto_20190304_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='guest_editors',
        ),
    ]
