# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-21 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0026_auto_20190321_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='guest_editors',
            new_name='editors',
        ),
    ]
