# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-04 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0026_journal_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='display_issue_number',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='display_issue_title',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='display_issue_volume',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='display_issue_year',
            field=models.BooleanField(default=True),
        ),
    ]
