# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-05 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0027_auto_20190404_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
