# Generated by Django 2.2 on 2019-05-08 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0028_auto_20190405_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='carousel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal', to='carousel.Carousel'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='press_image_override',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='press_image_override', to='core.File'),
        ),
    ]
