# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-03 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import journal.models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0034_migrate_issue_types'),
        ('core', '0037_journal_xsl_files'),

        
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='xsl',
            field=models.ForeignKey(default=journal.models.default_xsl, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.XSLFile'),
            preserve_default=False,
        ),
    ]
