# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-16 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import journal.models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0036_set_default_xslt'),
        ('core', '0038_xslt_1-3-8')
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='xsl',
            field=models.ForeignKey(default=journal.models.default_xsl, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.XSLFile'),
        ),
    ]
