# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-28 08:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import journal.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_journal_xsl_files'),
        ('journal', '0037_auto_20200116_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='xsl',
            field=models.ForeignKey(default=journal.models.default_xsl, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='default_xsl', to='core.XSLFile'),
        ),
    ]
