# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-22 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0041_auto_20200422_1048'),
        ('journal', '0037_auto_20200116_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission.Article')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Issue')),
            ],
        ),
    ]
