# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-22 10:52
from __future__ import unicode_literals

from django.db import migrations

migrate_join_table_data = """
INSERT INTO journal_issuearticle (article_id,issue_id,is_primary)
  SELECT article_id, issue_id, FALSE
  FROM journal_issue_articles
"""


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0038_issuearticle'),
    ]

    operations = [
        migrations.RunSQL(migrate_join_table_data)
    ]
