# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-01 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0038_auto_20200428_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='disable_front_end',
            field=models.BooleanField(default=False),
        ),
    ]
