# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-22 13:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0039_copy_issue_articles_m2m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='articles',
        ),
    ]
