# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-22 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0041_auto_20200422_1048'),
        ('journal', '0040_remove_issue_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='articles',
            field=models.ManyToManyField(through='journal.IssueArticle', to='submission.Article'),
        ),
    ]
