# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-15 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0040_auto_20200805_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='short_description',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
