# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-22 13:09
from __future__ import unicode_literals

from django.db import migrations


def copy_primary_issues(apps, schema_editor):
    IssueArticles = apps.get_model('journal', 'IssueArticle')

    for ia in IssueArticles.objects.all():
        if ia.article.primary_issue and ia.article.primary_issue == ia.issue:
                ia.is_primary = True
                ia.save()


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0041_issue_articles'),
    ]

    operations = [
        migrations.RunPython(copy_primary_issues,
                             reverse_code=migrations.RunPython.noop),
    ]
