# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-10 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0041_issue_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='contact_info_cy',
            field=models.TextField(blank=True, null=True, verbose_name='Contact Information'),
        ),
        migrations.AddField(
            model_name='journal',
            name='contact_info_de',
            field=models.TextField(blank=True, null=True, verbose_name='Contact Information'),
        ),
        migrations.AddField(
            model_name='journal',
            name='contact_info_en',
            field=models.TextField(blank=True, null=True, verbose_name='Contact Information'),
        ),
        migrations.AddField(
            model_name='journal',
            name='contact_info_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Contact Information'),
        ),
    ]
