# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-29 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0043_auto_20210518_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='contact_info_nl',
            field=models.TextField(blank=True, null=True, verbose_name='Contact Information'),
        ),
    ]
