# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-21 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0044_journal_contact_info_nl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='is_remote',
            field=models.BooleanField(default=False, help_text='When enabled, the journal is marked as not hosted in Janeway.'),
        ),
    ]
