# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-09-20 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0045_auto_20210721_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='use_domain_mode',
            field=models.BooleanField(default=False),
        ),
    ]
