# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-01-10 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0046_auto_20210922_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='code',
            field=models.SlugField(blank=True, help_text="An optional alphanumeric code (Slug) used to generate a verbose  url for this issue. e.g: 'winter-special-issue'.", max_length=999, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='issue',
            unique_together=set([('journal', 'code')]),
        ),
    ]
