# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-01-10 10:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0046_auto_20210922_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='code',
            field=models.CharField(blank=True, help_text="An optional alphanumeric code used to generate a verbose  url for this issue. e.g: 'winter-special-issue'.", max_length=999, null=True, validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-Z0-9-_]+$', 32))]),
        ),
        migrations.AlterUniqueTogether(
            name='issue',
            unique_together=set([('journal', 'code')]),
        ),
    ]
