# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-01-10 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0047_issue_code'),
        ('journal', '0047_auto_20220107_1212'),
    ]

    operations = [
    ]
