# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-21 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0049_auto_20220303_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
