# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-29 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0050_issue_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='The journal is no longer publishing. This is only used as part of the journal metadata.'),
        ),
    ]
