# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-30 09:41
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils.translation import ugettext
from django.utils.safestring import mark_safe


def save_issue_display_title(apps, schema_editor):
    Issue = apps.get_model("journal", "Issue")
    for issue_obj in Issue.objects.all():
        if issue_obj.issue_type.code != 'issue':
            issue_obj.display_title = issue_obj.issue_title
        else:
            journal = issue_obj.journal
            volume = issue = year = issue_title = article_number = page_numbers = ''

            if journal.display_issue_volume and issue_obj.volume:
                volume = ugettext("Volume") + " {}".format(issue_obj.volume)
            if journal.display_issue_number and issue_obj.issue and issue_obj.issue != "0":
                issue = ugettext("Issue") + " {}".format(issue_obj.issue)
            if journal.display_issue_year and issue_obj.date:
                year = "{}".format(issue_obj.date.year)
            if journal.display_issue_title:
                issue_title = issue_obj.issue_title

            issue_title_parts = [volume, issue, year, issue_title]
            issue_obj.display_title = mark_safe(" &bull; ".join((filter(None, issue_title_parts))))
        issue_obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0050_issue_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='display_title',
            field=models.CharField(blank=True, editable=False, max_length=300),
        ),
        migrations.RunPython(save_issue_display_title, reverse_code=migrations.RunPython.noop),
    ]
