# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-30 09:41
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils.translation import ugettext
from django.utils.safestring import mark_safe


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0050_issue_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='cached_display_title',
            field=models.CharField(null=True, blank=True, editable=False, help_text='Autogenerated cache of the display format of an issue title', max_length=300),
        ),
    ]
