# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-13 14:36
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils.translation import ugettext
from django.utils.safestring import mark_safe


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0051_journal_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedpubcheckitems',
            name='select_open_reviews',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='issue',
            name='cached_display_title',
            field=models.CharField(null=True, blank=True, editable=False, help_text='Autogenerated cache of the display format of an issue title', max_length=300),
        ),
        migrations.AddField(
            model_name='issue',
            name='doi',
            field=models.CharField(blank=True, help_text='The DOI (not URL) to be registered for the issue when registering articles that are part of this issue. If you have enabled issue autoregistration in your settings, this field should not be entered manually.', max_length=255, null=True, verbose_name='DOI'),
        ),
    ]
