# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-13 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0051_journal_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedpubcheckitems',
            name='select_open_reviews',
            field=models.BooleanField(default=False),
        ),
    ]
