# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-09-08 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0052_issue_display_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='doi',
            field=models.CharField(blank=True, help_text='The DOI (not URL) to be registered for the issue when registering articles that are part of this issue. If you have enabled issue autoregistration in your settings, this field should not be entered manually.', max_length=255, null=True, verbose_name='DOI'),
        ),
    ]
