# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-10 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0054c_auto_20220811_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='carousel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal', to='carousel.Carousel'),
        ),
    ]
