# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-11 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0054c_auto_20220811_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='isbn',
            field=models.CharField(blank=True, help_text='An ISBN is relevant for non-serial collections such as conference proceedings', max_length=28, null=True, verbose_name='ISBN'),
        ),
    ]
