# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-01-18 12:21
from __future__ import unicode_literals

import core.file_system
import core.model_utils
from django.db import migrations, models
import journal.models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0055_issue_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='display_issue_doi',
            field=models.BooleanField(default=True),
        ),
    ]
