# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-02-08 12:33
from __future__ import unicode_literals

import core.file_system
import core.model_utils
from django.db import migrations, models
import journal.models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0056_display_issue_doi'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='contact_info_en_us',
            field=models.TextField(blank=True, null=True, verbose_name='Contact Information'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='cover_image',
            field=core.model_utils.SVGImageField(blank=True, help_text='Image representing the cover of a printed issue or volume', null=True, storage=core.file_system.JanewayFileSystemStorage(), upload_to=journal.models.cover_images_upload_path),
        ),
    ]
