# Generated by Django 3.2.16 on 2023-03-17 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0057_auto_20230208_1233'),
        ('journal', '0057_verbose_names_20230301_1914'),
    ]

    operations = [
    ]
