# Generated by Django 3.2.19 on 2023-08-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0060_alter_journal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='cached_display_title_cy',
            field=models.CharField(blank=True, editable=False, help_text='Autogenerated cache of the display format of an issue title', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='cached_display_title_de',
            field=models.CharField(blank=True, editable=False, help_text='Autogenerated cache of the display format of an issue title', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='cached_display_title_en',
            field=models.CharField(blank=True, editable=False, help_text='Autogenerated cache of the display format of an issue title', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='cached_display_title_en_us',
            field=models.CharField(blank=True, editable=False, help_text='Autogenerated cache of the display format of an issue title', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='cached_display_title_fr',
            field=models.CharField(blank=True, editable=False, help_text='Autogenerated cache of the display format of an issue title', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='cached_display_title_nl',
            field=models.CharField(blank=True, editable=False, help_text='Autogenerated cache of the display format of an issue title', max_length=300, null=True),
        ),
    ]
