# Generated by Django 3.2.20 on 2024-02-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0061_auto_20230816_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='display_issues_grouped_by_decade',
            field=models.BooleanField(default=False, help_text='When enabled the issue page will group and display issues by decade.'),
        ),
    ]
