# Generated by Django 3.2.20 on 2024-03-12 09:22

import core.model_utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0061_auto_20230816_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue_description',
            field=core.model_utils.JanewayBleachField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='contact_info',
            field=core.model_utils.JanewayBleachField(blank=True, null=True, verbose_name='Contact Information'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='contact_info_cy',
            field=core.model_utils.JanewayBleachField(blank=True, null=True, verbose_name='Contact Information'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='contact_info_de',
            field=core.model_utils.JanewayBleachField(blank=True, null=True, verbose_name='Contact Information'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='contact_info_en',
            field=core.model_utils.JanewayBleachField(blank=True, null=True, verbose_name='Contact Information'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='contact_info_en_us',
            field=core.model_utils.JanewayBleachField(blank=True, null=True, verbose_name='Contact Information'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='contact_info_fr',
            field=core.model_utils.JanewayBleachField(blank=True, null=True, verbose_name='Contact Information'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='contact_info_nl',
            field=core.model_utils.JanewayBleachField(blank=True, null=True, verbose_name='Contact Information'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='description',
            field=core.model_utils.JanewayBleachField(blank=True, null=True, verbose_name='Journal Description'),
        ),
        migrations.AlterField(
            model_name='prepublicationchecklistitem',
            name='text',
            field=core.model_utils.JanewayBleachField(),
        ),
        migrations.AlterField(
            model_name='presetpublicationcheckitem',
            name='text',
            field=core.model_utils.JanewayBleachField(),
        ),
    ]
