# Generated by Django 3.2.20 on 2024-03-27 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0062_auto_20240312_0922'),
        ('journal', '0062_journal_display_issues_grouped_by_decade'),
    ]

    operations = [
    ]
