# Generated by Django 3.2.20 on 2024-05-01 14:24

import core.model_utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0064_journal_default_editorial_team_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuetype',
            name='custom_plural',
            field=core.model_utils.JanewayBleachCharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issuetype',
            name='pretty_name',
            field=core.model_utils.JanewayBleachCharField(max_length=255),
        ),
    ]
