# Generated by Django 4.2.11 on 2024-08-21 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0079_merge_20240602_1739'),
        ('journal', '0065_prepub_send_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('title_en_us', models.CharField(blank=True, max_length=255, null=True)),
                ('title_fr', models.CharField(blank=True, max_length=255, null=True)),
                ('title_de', models.CharField(blank=True, max_length=255, null=True)),
                ('title_nl', models.CharField(blank=True, max_length=255, null=True)),
                ('title_cy', models.CharField(blank=True, max_length=255, null=True)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.journal')),
            ],
        ),
        migrations.CreateModel(
            name='TopicOrdering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.issue')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission.section')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.topic')),
            ],
        ),
    ]
