# Generated by Django 4.2.15 on 2025-01-31 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0066_issue_type_bleach_20240507_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixedpubcheckitems',
            name='select_render_galley',
        ),
        migrations.AddField(
            model_name='fixedpubcheckitems',
            name='preview_article',
            field=models.BooleanField(default=False),
        ),
    ]
