# Generated by Django 4.2.15 on 2025-01-22 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0066_issue_type_bleach_20240507_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixedpubcheckitems',
            old_name='select_render_galley',
            new_name='preview_article',
        ),
    ]
