# Generated by Django 4.2.11 on 2024-08-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0066_topic_topicordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='public_submissions',
            field=models.BooleanField(default=True),
        ),
    ]
