# Generated by Django 4.2.15 on 2024-11-28 10:27

import core.model_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0066_issue_type_bleach_20240507_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='cached_display_title_es',
            field=models.CharField(blank=True, editable=False, help_text='Autogenerated cache of the display format of an issue title', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='contact_info_es',
            field=core.model_utils.JanewayBleachField(blank=True, null=True, verbose_name='Contact Information'),
        ),
    ]
