# Generated by Django 4.2.20 on 2025-07-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0067_issue_cached_display_title_es_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="cached_display_title_a11y",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Autogenerated cache of the accessible display format of an issue title",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="cached_display_title_a11y_cy",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Autogenerated cache of the accessible display format of an issue title",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="cached_display_title_a11y_de",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Autogenerated cache of the accessible display format of an issue title",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="cached_display_title_a11y_en",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Autogenerated cache of the accessible display format of an issue title",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="cached_display_title_a11y_en_us",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Autogenerated cache of the accessible display format of an issue title",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="cached_display_title_a11y_es",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Autogenerated cache of the accessible display format of an issue title",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="cached_display_title_a11y_fr",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Autogenerated cache of the accessible display format of an issue title",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="cached_display_title_a11y_nl",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Autogenerated cache of the accessible display format of an issue title",
                max_length=300,
                null=True,
            ),
        ),
    ]
