# Generated by Django 4.2.21 on 2025-07-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0067_issue_cached_display_title_es_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="journal",
            options={"ordering": ("sequence",)},
        ),
        migrations.AddField(
            model_name="journal",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("archived", "Archived"),
                    ("coming_soon", "Coming soon"),
                    ("test", "Test"),
                ],
                default="active",
                max_length=20,
                verbose_name="Publishing status",
            ),
        ),
    ]
