# Generated by Django 4.2.22 on 2025-09-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0068_issue_cached_display_title_a11y_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="journal",
            options={"ordering": ("sequence",)},
        ),
        migrations.AddField(
            model_name="journal",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("archived", "Archived"),
                    ("coming_soon", "Coming soon"),
                    ("test", "Test"),
                ],
                default="active",
                max_length=20,
                verbose_name="Publishing status",
            ),
        ),
    ]
