# Generated by Django 4.2.20 on 2025-09-08 14:51

import core.model_utils
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0068_issue_cached_display_title_a11y_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="journal_a11y_info",
            field=core.model_utils.JanewayBleachField(
                blank=True,
                help_text="This is information about the accessibility of user-content. It will appear on the accessibility page under the journal name.",
                null=True,
                verbose_name="Journal Accessibility Information",
            ),
        ),
    ]
