# Generated by Django 4.2.29 on 2026-06-20 10:14

from django.db import migrations, models


def move_is_archived_to_journal_status(apps, schema_editor):
    Journal = apps.get_model("journal.Journal")
    Journal.objects.filter(is_archived=True).update(status="archived")


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0069_alter_journal_options_journal_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journal",
            name="is_archived",
            field=models.BooleanField(
                default=False,
                help_text="The 'is_archived' field is deprecated. Use 'journal.status' instead.",
            ),
        ),
        migrations.RunPython(
            move_is_archived_to_journal_status,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
