# Generated by Django 4.2.29 on 2026-09-24 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0070_move_journal_is_archived_to_journal_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="issue_article_grouping",
            field=models.CharField(
                choices=[
                    ("section", "Section"),
                    ("topic", "Topic"),
                    ("section_topic", "Section, then topic"),
                    ("topic_section", "Topic, then section"),
                    ("ungrouped", "Ungrouped"),
                ],
                default="section",
                help_text="Controls the headings under which articles are listed on the issue page. Topics can be managed from the Manager page.",
                max_length=20,
                verbose_name="Group issue articles by",
            ),
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("title_en", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "title_en_us",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("title_fr", models.CharField(blank=True, max_length=255, null=True)),
                ("title_de", models.CharField(blank=True, max_length=255, null=True)),
                ("title_nl", models.CharField(blank=True, max_length=255, null=True)),
                ("title_cy", models.CharField(blank=True, max_length=255, null=True)),
                ("title_es", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "public_submissions",
                    models.BooleanField(
                        default=True,
                        help_text="When enabled, authors can select this topic during submission",
                        verbose_name="Open for submissions",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="journal.journal",
                    ),
                ),
            ],
            options={
                "ordering": ("title", "pk"),
            },
        ),
        migrations.CreateModel(
            name="TopicOrdering",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=1)),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="journal.issue"
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="journal.topic"
                    ),
                ),
            ],
            options={
                "ordering": ("order", "topic"),
                "unique_together": {("topic", "issue")},
            },
        ),
    ]
