# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-21 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0002_auto_20170816_1050'),
        ('carousel', '0002_auto_20170711_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='news_articles',
            field=models.ManyToManyField(blank=True, to='comms.NewsItem'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='mode',
            field=models.CharField(choices=[('off', 'Off'), ('latest', 'Latest Articles'), ('news', 'Latest News'), ('selected-articles', 'Selected Articles'), ('mixed', 'Latest Articles and News'), ('mixed-selected', 'Selected Articles and News')], default='Latest', max_length=200),
        ),
    ]
