# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0011_auto_20170921_0937'),
        ('identifiers', '0003_brokendoi_journal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brokendoi',
            name='journal',
        ),
        migrations.AddField(
            model_name='brokendoi',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='submission.Article'),
            preserve_default=False,
        ),
    ]
