# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-15 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

def migrate_current_crossref_deposit_identifiers(apps, schema_editor):
    CrossrefDeposit = apps.get_model("identifiers", "CrossrefDeposit")
    for crossref_deposit in CrossrefDeposit.objects.all():
        if crossref_deposit.identifier:
            crossref_deposit.identifiers.add(crossref_deposit.identifier)

class Migration(migrations.Migration):

    dependencies = [
        ('identifiers', '0006_crossrefdeposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='crossrefdeposit',
            name='deposit',
            field=models.TextField(blank=True, help_text='The deposit document with rendered XML for the DOI batch.', null=True),
        ),
        migrations.AddField(
            model_name='crossrefdeposit',
            name='identifiers',
            field=models.ManyToManyField(to='identifiers.Identifier'),
        ),
        migrations.AlterField(
            model_name='crossrefdeposit',
            name='identifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deposit_identifier', to='identifiers.Identifier'),
        ),
        migrations.RunPython(migrate_current_crossref_deposit_identifiers, reverse_code=migrations.RunPython.noop),
    ]
