# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-10 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('identifiers', '0007_crossrefdeposit_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crossrefdeposit',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
