# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-10 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identifiers', '0008_auto_20200310_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='crossrefdeposit',
            name='queued',
            field=models.BooleanField(default=False),
        ),
    ]
