# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-13 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identifiers', '0009_crossrefdeposit_queued'),
    ]

    operations = [
        migrations.AddField(
            model_name='crossrefdeposit',
            name='polling_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
