# Generated by Django 4.2.29 on 2026-06-03 22:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("identifiers", "0010_alter_identifier_id_type"),
        ("identifiers", "0010_auto_20231107_1750"),
    ]

    operations = []
