# Generated by Django 4.2.20 on 2026-04-29 15:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("identifiers", "0010_alter_identifier_id_type"),
        ("identifiers", "0010_auto_20231107_1750"),
    ]

    operations = []
