# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-29 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identifiers", "0011_merge_20260603_2206"),
    ]

    operations = [
        migrations.AlterField(
            model_name="identifier",
            name="id_type",
            field=models.CharField(
                choices=[
                    ("doi", "DOI"),
                    ("uri", "URI Path"),
                    ("pubid", "Publisher ID"),
                    ("openalex", "OpenAlex ID"),
                    ("arxiv", "ArXiv ID"),
                    ("preprintid", "Preprint ID"),
                    ("protonid", "IOP Proton ID"),
                ],
                max_length=300,
            ),
        ),
    ]
