__copyright__ = "Copyright 2026 Birkbeck, University of London"
__author__ = "Open Library of Humanities"
__license__ = "AGPL v3"
__maintainer__ = "Open Library of Humanities"


from django.urls import re_path

from screening import views


urlpatterns = [
    re_path(
        r"^$",
        views.screening_list,
        name="screening_list",
    ),
    re_path(
        r"^article/(?P<article_id>\d+)/$",
        views.screening_article,
        name="screening_article",
    ),
    re_path(
        r"^article/(?P<article_id>\d+)/round/add/$",
        views.add_screening_round,
        name="add_screening_round",
    ),
    re_path(
        r"^article/(?P<article_id>\d+)/round/(?P<round_id>\d+)/assign/$",
        views.add_screening_assignment,
        name="add_screening_assignment",
    ),
    re_path(
        r"^article/(?P<article_id>\d+)/assignment/(?P<assignment_id>\d+)/notify/$",
        views.screening_assignment_notification,
        name="screening_assignment_notification",
    ),
    re_path(
        r"^requests/$",
        views.screening_requests,
        name="screening_requests",
    ),
    re_path(
        r"^request/(?P<assignment_id>\d+)/accept/$",
        views.accept_screening_request,
        name="accept_screening_request",
    ),
    re_path(
        r"^request/(?P<assignment_id>\d+)/decline/$",
        views.decline_screening_request,
        name="decline_screening_request",
    ),
    re_path(
        r"^assignment/(?P<assignment_id>\d+)/$",
        views.do_screening,
        name="do_screening",
    ),
    re_path(
        r"^assignment/(?P<assignment_id>\d+)/thanks/$",
        views.screening_thanks,
        name="screening_thanks",
    ),
    re_path(
        r"^article/(?P<article_id>\d+)/move/next/$",
        views.move_to_next_stage,
        name="screening_move_to_next_stage",
    ),
    re_path(
        r"^article/(?P<article_id>\d+)/revisions/request/$",
        views.request_screening_revisions,
        name="request_screening_revisions",
    ),
    re_path(
        r"^revisions/(?P<revision_id>\d+)/do/$",
        views.do_screening_revisions,
        name="do_screening_revisions",
    ),
    re_path(
        r"^revisions/(?P<revision_id>\d+)/$",
        views.view_screening_revision,
        name="view_screening_revision",
    ),
    re_path(
        r"^manager/pool/$",
        views.screening_pool,
        name="screening_pool",
    ),
    re_path(
        r"^manager/forms/$",
        views.screening_forms,
        name="screening_forms",
    ),
    re_path(
        r"^manager/forms/(?P<form_id>\d+)/$",
        views.edit_screening_form,
        name="edit_screening_form",
    ),
    re_path(
        r"^manager/forms/(?P<form_id>\d+)/element/(?P<element_id>\d+)/$",
        views.edit_screening_form,
        name="edit_screening_form_element",
    ),
    re_path(
        r"^manager/checklist-templates/$",
        views.screening_checklist_templates,
        name="screening_checklist_templates",
    ),
    re_path(
        r"^manager/checklist-templates/(?P<template_id>\d+)/$",
        views.edit_screening_checklist_template,
        name="edit_screening_checklist_template",
    ),
    re_path(
        r"^manager/checklist-templates/(?P<template_id>\d+)/item/(?P<item_id>\d+)/$",
        views.edit_screening_checklist_template,
        name="edit_screening_checklist_template_item",
    ),
    re_path(
        r"^checklist-item/(?P<item_id>\d+)/toggle/$",
        views.toggle_checklist_item,
        name="toggle_checklist_item",
    ),
    re_path(
        r"^checklist-item/(?P<item_id>\d+)/comment/$",
        views.save_checklist_item_comment,
        name="save_checklist_item_comment",
    ),
    re_path(
        r"^article/(?P<article_id>\d+)/checklist/switch/$",
        views.switch_checklist_template,
        name="switch_checklist_template",
    ),
    re_path(
        r"^article/(?P<article_id>\d+)/assignment/(?P<assignment_id>\d+)/edit/$",
        views.edit_screening_assignment,
        name="edit_screening_assignment",
    ),
    re_path(
        r"^article/(?P<article_id>\d+)/assignment/(?P<assignment_id>\d+)/withdraw/$",
        views.withdraw_screening_assignment,
        name="withdraw_screening_assignment",
    ),
    re_path(
        r"^article/(?P<article_id>\d+)/assignment/(?P<assignment_id>\d+)/reset/$",
        views.reset_screening_assignment,
        name="reset_screening_assignment",
    ),
    re_path(
        r"^article/(?P<article_id>\d+)/assignment/(?P<assignment_id>\d+)/report/$",
        views.view_screening_report,
        name="view_screening_report",
    ),
]
