FROM birkbeckctp/janeway:latest

ADD ./src /vol/janeway/src
ADD ./requirements.txt /vol/janeway/requirements.txt
ADD ./dev-requirements.txt /vol/janeway/dev-requirements.txt
ADD ./jenkins/entrypoint.sh /vol/janeway/entrypoint.sh

WORKDIR /vol/janeway

RUN pip3 install -r requirements.txt --src /tmp/src
RUN pip3 install -r dev-requirements.txt --src /tmp/src

ENV DB_VENDOR=sqlite

ENTRYPOINT ["./entrypoint.sh"]
