# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 09:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170816_0851'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsitem',
            options={},
        ),
        migrations.RemoveField(
            model_name='newsitem',
            name='body',
        ),
        migrations.RemoveField(
            model_name='newsitem',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='newsitem',
            name='end_display',
        ),
        migrations.RemoveField(
            model_name='newsitem',
            name='large_image_file',
        ),
        migrations.RemoveField(
            model_name='newsitem',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='newsitem',
            name='posted',
        ),
        migrations.RemoveField(
            model_name='newsitem',
            name='posted_by',
        ),
        migrations.RemoveField(
            model_name='newsitem',
            name='sequence',
        ),
        migrations.RemoveField(
            model_name='newsitem',
            name='start_display',
        ),
        migrations.RemoveField(
            model_name='newsitem',
            name='title',
        ),
    ]
