# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 11:33
from __future__ import unicode_literals

import uuid

from django.db import migrations


def fix_uuids(apps, schema_editor):
    Account = apps.get_model('core', 'Account')

    for account in Account.objects.all():
        account.uuid = uuid.uuid4()
        account.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170925_1129'),
    ]

    operations = [
        migrations.RunPython(fix_uuids),
    ]
