# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20170925_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='enable_public_profile',
            field=models.BooleanField(default=False, help_text='If enabled, your basic profile will be available to the public.'),
        ),
    ]
