# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_account_enable_public_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galley',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='submission.Article'),
        ),
    ]
