# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-07 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0019_auto_20171130_1115'),
        ('core', '0011_auto_20171010_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission.Article')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.WorkflowElement')),
            ],
        ),
    ]
