# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-08 07:29
from __future__ import unicode_literals
#from django.db import models
from django.db import migrations


def addfield(name):
    return {
        'sql': "ALTER TABLE django_site ADD COLUMN %s VARCHAR(255)" % name,
        'reverse_sql': "ALTER TABLE django_site DROP COLUMN %s" % name,
        # wish this worked :(
        # https://docs.djangoproject.com/en/1.11/ref/migration-operations/#runsql
        # 'state_operations': [migrations.AddField('django.contrib.sites.Site', name, models.CharField(max_length=255))]
    }


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20180207_1525'),
    ]

    operations = [
        # TODO: Currently causing issues where these already exist
        # migrations.RunSQL(**addfield("folder_name")),
        # migrations.RunSQL(**addfield("subdomains"))
    ]
