# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-17 11:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_supplementaryfile'),
        ('core', '0014_workflowelement_jump_url'),
    ]

    operations = [
    ]
