# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-17 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_merge_20180417_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplementaryfile',
            name='doi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
