# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-16 11:23
from __future__ import unicode_literals

import core.file_system
import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20180417_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, storage=core.file_system.JanewayFileSystemStorage(), upload_to=core.models.profile_images_upload_path),
        ),
    ]
