# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-23 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0017_file_fields_for_the_last_time'),
        ('core', '0019_adds_DomainAlias_journal_FK'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domainalias',
            name='site_id',
        ),
    ]
