# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-19 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_domainalias_is_secure'),
        ('core', '0019_set_default_news_items'),
    ]

    operations = [
    ]
