# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-29 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_fix_journal_base_url_from_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(max_length=300, null=True, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(max_length=300, null=True, verbose_name='Last name'),
        ),
    ]
