# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-01 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20190201_1015'),
        ('core', '0024_auto_20190129_1647'),
    ]

    operations = [
    ]
