# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-12 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_merge_20190201_1533'),
        ('core', '0025_fix_bad_journal_urls_in_template'),
    ]

    operations = [
    ]
