# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-15 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0024_auto_20190304_0916'),
        ('core', '0028_fix_bad_email_urls'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settingvalue',
            options={},
        ),
        migrations.AlterField(
            model_name='settingvalue',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.Journal'),
        ),
        migrations.AlterUniqueTogether(
            name='settingvalue',
            unique_together=set([('journal', 'setting')]),
        ),
    ]
