# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-25 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_rename_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='institution',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Institution'),
        ),
    ]
