# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-05 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_adds_default_case_for_setting_value'),
        ('core', '0029_rename_setting'),
    ]

    operations = [
    ]
