# Generated by Django 2.2 on 2019-05-08 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hvad.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_merge_20190405_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingvalue',
            name='_hvad_query',
            field=hvad.fields.SingleTranslationObject('core.SettingValue', 'core.SettingValueTranslation'),
        ),
        migrations.AlterField(
            model_name='account',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='settingvaluetranslation',
            name='master',
            field=hvad.fields.MasterKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.SettingValue'),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
