# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-07 11:12
from __future__ import unicode_literals

from django.db import migrations
from django.db import connection
from django.db.utils import OperationalError

from utils.logger import get_logger

logger = get_logger(__name__)


def drop_sites_tables(apps, schema_editor):
    try:
        with connection.cursor() as cursor:
            cursor.execute('DROP TABLE django_site;')
            logger.debug('Django Site table dropped.')
    except OperationalError:
        logger.debug('Django Site table not found.')


def delete_sites_migrations(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute("DELETE FROM django_migrations WHERE app = 'sites';")
        logger.debug('Deleting migrations for sites app.')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_merge_20190405_1549'),
    ]

    run_before = [
        ('sites', '0001_initial'),
        ('socialaccount', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(drop_sites_tables,
                             reverse_code=migrations.RunPython.noop),
        migrations.RunPython(delete_sites_migrations,
                             reverse_code=migrations.RunPython.noop),
    ]
