# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-20 12:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_update_revision_assignment_email'),
        ('core', '0034_update_handshake_urls'),
    ]

    operations = [
    ]
