# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-08-25 09:51
from __future__ import unicode_literals

from django.db import migrations


def lower_all_usernames(apps, schema_editor):
    Account = apps.get_model('core', 'Account')
    accounts = Account.objects.all()

    for account in accounts:
        account.username = account.username.lower()
        account.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_fix_reminder_name_description'),
    ]

    operations = [
        migrations.RunPython(
            lower_all_usernames,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
