# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-08-25 09:51
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.postgres.operations import CITextExtension


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20200825_1051'),
    ]

    operations = [CITextExtension()]
