# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-10 11:40
from __future__ import unicode_literals

import core.model_utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_install_ci_extension_pg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=core.model_utils.PGCaseInsensitiveEmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
    ]
