# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-21 13:59
from __future__ import unicode_literals

from django.db import migrations


def delete_settings(apps, schema_editor):
    Setting = apps.get_model('core', 'Setting')
    Setting.objects.filter(
        group__name='email',
        name='review_request_sent',
    ).delete()


def remove_link_form_production_complete(apps, schema_editor):
    SettingValueTranslation = apps.get_model('core', 'SettingValueTranslation')

    settings = SettingValueTranslation.objects.filter(
        master__setting__name='production_complete',
        master__setting__group__name='email',
    )

    for setting in settings:
        setting.value = setting.value.replace(
            '<p>This article is now in the Proofing workflow: {{ proofing_list_url }}.</p>',
            '',
        )
        setting.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_fix_url_emails'),
    ]

    operations = [
        migrations.RunPython(
            delete_settings,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            remove_link_form_production_complete,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
