# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-17 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_auto_20210217_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingvalue',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
