# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-17 16:16
from __future__ import unicode_literals

from django.db import migrations


def migrate_settings(apps, schema_editor):
    SettingValue = apps.get_model('core', 'SettingValue')
    SettingValueTranslation = apps.get_model('core', 'SettingValueTranslation')

    translations = SettingValueTranslation.objects.all()

    for translation in translations:
        setting = SettingValue.objects.get(pk=translation.master_id)
        setattr(setting, 'value_{}'.format(translation.language_code), translation.hvad_value)
        setting.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_auto_20210217_1602'),
    ]

    operations = [
        # noop for reverse as we're not actually deleting the data from SectionTranslation
        migrations.RunPython(migrate_settings, reverse_code=migrations.RunPython.noop),
    ]
