# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-28 08:11
from __future__ import unicode_literals
import os

from django.core.files.base import ContentFile
from django.db import migrations
from django.conf import settings

OLD_LABEL = "Janeway default"
NEW_LABEL = "Janeway default (1.3.8)"
LATEST_LABEL = "Janeway default (latest)"
COMMENTS = """
Changes from v1.3.8:
    - Adds support for glossing
    - Changes line endings to Unix
    - Renders DOIs as URLs on mixed-citation elements
"""


def upgrade(apps, schema_editor):
    """ Installs the latest default XSLT preserving the previous one

    Only runs if the previous version XSLT was installed.
    If it was, it relabels it (the old label had no version), installs
    the new one and swaps any journals using the old default to use the
    new.
    """
    XSLFile = apps.get_model("core", "XSLFile")
    Galley = apps.get_model("core", "Galley")
    Journal = apps.get_model("journal", "Journal")
    try:
        old_default = XSLFile.objects.get(label=OLD_LABEL)
        old_default.label = NEW_LABEL
        old_default.save()
    except XSLFile.DoesNotExist:
        # Handle migration being rerun
        try:
            old_default = XSLFile.objects.get(label=NEW_LABEL)
        except XSLFile.DoesNotExist:
            old_default = None
    xsl_path = os.path.join(settings.BASE_DIR, "transform/xsl/default.xsl")
    with open(xsl_path, 'rb') as f:
        xsl_file = ContentFile(f.read())
        xsl_file.name = "default.xsl"

        new_default, c = XSLFile.objects.get_or_create(
            label=LATEST_LABEL,
            defaults={
                "comments": COMMENTS,
                "file": xsl_file,
            },
        )
    journals = Journal.objects.all()
    for journal in journals:
        if journal.xsl == old_default:
            journal.xsl = new_default
            journal.save()
    Galley.objects.filter(xsl_file=old_default).update(xsl_file=new_default)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_fix_review_accept_acknowledgement_url'),
        ('journal', '0041_issue_short_description'),
    ]

    operations = [
        migrations.RunPython(upgrade, reverse_code=migrations.RunPython.noop)
    ]
