# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-13 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_auto_20210513_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='name_cy',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='name_de',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='name_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='name_fr',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='role_cy',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='role_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='role_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='role_fr',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
