# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-24 09:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_auto_20210607_1100'),
        ('core', '0051_auto_20210513_1206'),
    ]

    operations = [
    ]
