# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-29 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_merge_20210624_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='name_nl',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='role_nl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='editorialgroup',
            name='description_nl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='editorialgroup',
            name='name_nl',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='settingvalue',
            name='value_nl',
            field=models.TextField(blank=True, null=True),
        ),
    ]
