# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-29 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_auto_20210629_0641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settingvaluetranslation',
            options={'managed': False},
        ),
    ]
