# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-09-01 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_auto_20210729_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='label',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Label'),
        ),
    ]
