# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-09-20 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0025_repository_use_domain_mode'),
        ('core', '0055_auto_20210920_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainalias',
            name='repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repository.Repository'),
        ),
    ]
