# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-04 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_auto_20210913_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='galley',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
