# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-05 09:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_xslt_1-4-0'),
        ('core', '0057_auto_20211004_1130'),
    ]

    operations = [
    ]
