# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-01-07 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_remove_display_about_on_submissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainalias',
            name='domain',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
