# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-01-10 19:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_auto_20220107_1208'),
        ('core', '0061_auto_20220109_1800'),
    ]

    operations = [
    ]
