# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-01 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_fix_review_accept_ack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='institution',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Institution'),
        ),
    ]
