# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-18 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_auto_20220202_1426'),
        ('core', '0064_auto_20220216_1213'),
    ]

    operations = [
    ]
