# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-15 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_merge_20220223_1229'),
        ('core', '0065_merge_20220218_1347'),
    ]

    operations = [
    ]
