# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-27 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_xslt_1-4-1'),
        ('core', '0064_auto_20220201_1038'),
    ]

    operations = [
    ]
