# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-23 10:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_xslt_1-4-2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='text',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file', to=settings.CORE_FILETEXT_MODEL),
        ),
    ]
