# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-07-14 11:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_auto_20220630_1608'),
    ]

    operations = [
    ]
