# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-08-15 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_fix_editorial_images_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='suffix',
            field=models.CharField(
                blank=True,
                verbose_name='Name suffix',
                max_length=300,
                null=True,
            ),
        ),
    ]
