# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-04 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_xslt_1-4-3'),
        ('core', '0076_remove_old_setting'),
    ]

    operations = [
    ]
