# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-12-19 21:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    def forwards_func(apps, schema_editor):
        Role = apps.get_model("core", "Role")
        new_role = Role.objects.create(
            name='Journal Manager',
            slug='journal-manager',
        )

    def reverse_func(apps, schema_editor):
        Role = apps.get_model("core", "Role")
        new_role = Role.objects.filter(
            name='Journal Manager',
            slug='journal-manager',
        ).delete()

    dependencies = [
        ('core', '0077_merge_20221004_1031'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
