# Generated by Django 3.2.16 on 2023-01-24 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_add_journal_manager_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='editable_by',
            field=models.ManyToManyField(blank=True, help_text='Determines who can edit this setting based on their assigned roles.', to='core.Role'),
        ),
    ]
