# Generated by Django 3.2.16 on 2023-03-17 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_add_journal_manager_role'),
        ('core', '0078_auto_20230120_1546'),
        ('core', '0079_auto_20230208_1233'),
    ]

    operations = [
    ]
