# Generated by Django 3.2.16 on 2023-01-24 15:03

from django.db import migrations
from django.core.management import call_command

from core import models
from utils import install


def forwards_func(apps, schema_editor):
    try:
        install.load_permissions()
    except models.Setting.DoesNotExist:
        # This data migration can be ignored on a first load,
        # permissions will be added during the load_default_settings
        # command. See utils/install.py for more information.
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_auto_20230124_1430'),
    ]

    operations = [
        migrations.RunPython(
            forwards_func,
            migrations.RunPython.noop,
        ),
    ]
