# Generated by Django 3.2.19 on 2023-05-24 07:50

from django.db import migrations, models
import django.db.models.deletion

def upgrade(apps, schema_editor):
    Galley = apps.get_model("core", "Galley")
    Galley.objects.filter(file__isnull=True).delete()

class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('core', '0081_alter_account_preferred_timezone'),
    ]

    operations = [
        migrations.RunPython(upgrade, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='galley',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.file'),
        ),
    ]
