# Generated by Django 3.2.18 on 2023-12-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_alter_account_preferred_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='name_prefix',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
