# Generated by Django 3.2.19 on 2023-06-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_galley_file_not_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(default='', max_length=300, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Middle name'),
        ),
    ]
