# Generated by Django 3.2.19 on 2023-08-15 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_galley_file_not_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='scrubs',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scrubbed', to='core.file'),
        ),
    ]
