# Generated by Django 3.2.19 on 2023-08-31 20:17

from django.db import migrations
from django.conf import settings
from django.utils import translation

SETTING_TEXTS_TO_REMOVE = [
    ' Details of the changes required are below:<br><br>{{ revision.editor_note }}',
    ' Details of the changes required are below:<br/><br/>{{ revision.editor_note }}'
]


def update_revision_email_template(apps, schema):
    SettingValue = apps.get_model('core', 'SettingValue')
    setting_values = SettingValue.objects.filter(
        setting__group__name='email',
        setting__name='request_revisions',
    )
    for setting_value in setting_values:
        for language in settings.LANGUAGES:

            lang = language[0].replace('-', '_')

            with translation.override(lang):

                value = getattr(
                    setting_value,
                    f"value_{lang}",
                )

                if value:
                    for text_to_remove in SETTING_TEXTS_TO_REMOVE:
                        value = value.replace(
                            text_to_remove,
                            ''
                        )
                    setattr(
                        setting_value,
                        f"value_{lang}",
                        value
                    )
        setting_value.save()


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0082_galley_file_not_nullable'),
    ]

    operations = [
        migrations.RunPython(
            update_revision_email_template,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
