# Generated by Django 3.2.20 on 2024-02-01 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_press_editorial_team_20240116'),
        ('core', '0084_xslt_1-5-1'),
    ]

    operations = [
    ]
