# Generated by Django 3.2.20 on 2024-03-07 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_auto_20240207_1654'),
        ('core', '0085_merge_20240201_1108'),
    ]

    operations = [
    ]
