# Generated by Django 3.2.20 on 2024-03-15 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_merge_20240201_1108'),
        ('core', '0086_auto_20240312_0922'),
    ]

    operations = [
    ]
