# Generated by Django 3.2.20 on 2024-03-27 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_merge_20240307_1832'),
        ('core', '0087_merge_20240315_1649'),
    ]

    operations = [
    ]
