# Generated by Django 3.2.20 on 2024-05-22 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0062_journal_display_issues_grouped_by_decade'),
        ('core', '0087_auto_20240506_0904'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pretty_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.journal')),
            ],
            options={
                'verbose_name_plural': 'study topic groups for articles and accounts',
            },
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pretty_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.topicgroup')),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.journal')),
            ],
            options={
                'verbose_name_plural': 'study topics for articles and accounts',
            },
        ),
        migrations.CreateModel(
            name='AccountTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_type', models.CharField(choices=[('PR', 'Primary'), ('SE', 'Secondary')], default='PR', max_length=2)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.topics')),
            ],
            options={
                'unique_together': {('account', 'topic')},
            },
        ),
        migrations.AddField(
            model_name='account',
            name='study_topic',
            field=models.ManyToManyField(blank=True, null=True, through='core.AccountTopic', to='core.Topics'),
        ),
    ]
