# Generated by Django 3.2.20 on 2024-03-28 12:13

from django.db import migrations, models


def set_editorial_group_image_dispay(apps, schema):
    EditorialGroup = apps.get_model("core", "EditorialGroup")
    SettingValue = apps.get_model("core", "SettingValue")

    setting_values = SettingValue.objects.filter(
        setting__name='enable_editorial_images',
    )
    for sv in setting_values:
        if sv.journal and sv.value in ['on', 'On']:
            EditorialGroup.objects.filter(
                journal=sv.journal,
            ).update(
                display_profile_images=True,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_merge_20240327_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorialgroup',
            name='display_profile_images',
            field=models.BooleanField(default=False, help_text='Enable to display profile images for this group.'),
        ),
        migrations.RunPython(
            set_editorial_group_image_dispay,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
