# Generated by Django 4.2.11 on 2024-04-30 17:04

from django.db import migrations
from utils.migration_utils import update_setting_types

SETTINGS_WITH_OLD_AND_NEW_TYPES = [
    ('general', 'publisher_name', 'char', 'mini-html'),
    ('general', 'collection_name', 'char', 'mini-html'),
    ('general', 'collection_name_plural', 'char', 'mini-html'),
    ('general', 'journal_name', 'char', 'mini-html'),
    ('email_subject', 'subject_unassign_editor', 'text', 'char'),
    ('email_subject', 'subject_author_copyedit_complete', 'text', 'char'),
    ('email_subject', 'subject_copyediting_decision', 'text', 'char'),
    ('email_subject', 'subject_author_publication', 'text', 'char'),
    ('email_subject', 'subject_copyeditor_ack', 'text', 'char'),
    ('email_subject', 'subject_copyeditor_assignment_notification', 'text', 'char'),
    ('email_subject', 'subject_copyeditor_notify_author', 'text', 'char'),
    ('email_subject', 'subject_copyeditor_notify_editor', 'text', 'char'),
    ('email_subject', 'subject_copyeditor_reopen_task', 'text', 'char'),
    ('email_subject', 'subject_copyedit_deleted', 'text', 'char'),
    ('email_subject', 'subject_copyedit_updated', 'text', 'char'),
    ('email_subject', 'subject_draft_editor_message', 'text', 'char'),
    ('email_subject', 'subject_draft_message', 'text', 'char'),
    ('email_subject', 'subject_editor_assignment', 'text', 'char'),
    ('email_subject', 'subject_editor_digest', 'text', 'char'),
    ('email_subject', 'subject_editor_new_submission', 'text', 'char'),
    ('email_subject', 'subject_new_user_registration', 'text', 'char'),
    ('email_subject', 'subject_notification_acceptance', 'text', 'char'),
    ('email_subject', 'subject_notification_submission', 'text', 'char'),
    ('email_subject', 'subject_notify_editor_proofing_complete', 'text', 'char'),
    ('email_subject', 'subject_notify_proofing_manager', 'text', 'char'),
    ('email_subject', 'subject_notify_proofreader_assignment', 'text', 'char'),
    ('email_subject', 'subject_notify_proofreader_cancelled', 'text', 'char'),
    ('email_subject', 'subject_notify_proofreader_complete', 'text', 'char'),
    ('email_subject', 'subject_notify_proofreader_edited', 'text', 'char'),
    ('email_subject', 'subject_notify_typesetter_proofing_changes', 'text', 'char'),
    ('email_subject', 'subject_password_reset', 'text', 'char'),
    ('email_subject', 'subject_peer_reviewer_pub_notification', 'text', 'char'),
    ('email_subject', 'subject_production_assign_article', 'text', 'char'),
    ('email_subject', 'subject_production_complete', 'text', 'char'),
    ('email_subject', 'subject_production_manager_notification', 'text', 'char'),
    ('email_subject', 'subject_request_revisions', 'text', 'char'),
    ('email_subject', 'subject_reviewer_digest', 'text', 'char'),
    ('email_subject', 'subject_review_accept_acknowledgement', 'text', 'char'),
    ('email_subject', 'subject_reviewer_acknowledgement', 'text', 'char'),
    ('email_subject', 'subject_review_assignment', 'text', 'char'),
    ('email_subject', 'subject_review_complete_acknowledgement', 'text', 'char'),
    ('email_subject', 'subject_review_complete_reviewer_acknowledgement', 'text', 'char'),
    ('email_subject', 'subject_review_decision_accept', 'text', 'char'),
    ('email_subject', 'subject_review_decision_decline', 'text', 'char'),
    ('email_subject', 'subject_review_decision_undecline', 'text', 'char'),
    ('email_subject', 'subject_review_decline_acknowledgement', 'text', 'char'),
    ('email_subject', 'subject_review_request_sent', 'text', 'char'),
    ('email_subject', 'subject_review_withdrawl', 'text', 'char'),
    ('email_subject', 'subject_revision_digest', 'text', 'char'),
    ('email_subject', 'subject_section_editor_pub_notification', 'text', 'char'),
    ('email_subject', 'subject_submission_acknowledgement', 'text', 'char'),
    ('email_subject', 'subject_thank_proofreaders_and_typesetters', 'text', 'char'),
    ('email_subject', 'subject_typesetter_complete_notification', 'text', 'char'),
    ('email_subject', 'subject_typesetter_corrections_complete', 'text', 'char'),
    ('email_subject', 'subject_typesetter_notification', 'text', 'char'),
    ('email_subject', 'subject_typeset_ack', 'text', 'char'),
    ('email_subject', 'subject_typeset_deleted', 'text', 'char'),
    ('email_subject', 'subject_typeset_reopened', 'text', 'char'),
    ('email_subject', 'subject_user_email_change', 'text', 'char'),
    ('general', 'matromo_tracking_code', 'text', 'char'),
    ('email_subject', 'subject_notify_correction_cancelled', 'text', 'char'),
    ('general', 'copyright_submission_label', 'char', 'mini-html'),
    ('email_subject', 'subject_accepted_review_reminder', 'text', 'char'),
    ('email_subject', 'subject_default_review_reminder', 'text', 'char'),
    ('email_subject', 'subject_notify_se_draft_declined', 'rich-text', 'char'),
    ('news', 'news_title', 'char', 'mini-html'),
    ('crossref', 'crossref_date_suffix', 'text', 'char'),
    ('general', 'default_journal_language', 'text', 'char'),
    ('email_subject', 'subject_revisions_complete_receipt', 'text', 'char'),
    ('email_subject', 'subject_author_copyedit_deleted', 'text', 'char'),
]

def update_text_and_char_setting_types(apps, schema_editor):
    """ Standardizes use of text and char setting types"""

    Setting = apps.get_model('core', 'Setting')
    for group, name, old_type, new_type in SETTINGS_WITH_OLD_AND_NEW_TYPES:
        update_setting_types(Setting, group, name, old_type, new_type)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_fix_untyped_galleys'),
    ]

    operations = [
        migrations.RunPython(
            update_text_and_char_setting_types,
            reverse_code=migrations.RunPython.noop
        ),
    ]
