# Generated by Django 3.2.20 on 2024-05-22 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0062_journal_display_issues_grouped_by_decade'),
        ('core', '0088_auto_20240522_0701'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='topicgroup',
            unique_together={('name', 'journal')},
        ),
        migrations.AlterUniqueTogether(
            name='topics',
            unique_together={('name', 'journal')},
        ),
    ]
