# Generated by Django 4.2.11 on 2024-04-25 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_auto_20240424_1005'),
        ('core', '0090_editorial_team_page_i18n'),
    ]

    operations = [
    ]
