# Generated by Django 3.2.20 on 2024-06-02 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_alter_accounttopic_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accounttopic',
            unique_together={('account', 'topic')},
        ),
    ]
