# Generated by Django 4.2.11 on 2024-05-01 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_fix_untyped_galleys'),
        ('core', '0092_xslt_1-6-0'),
    ]

    operations = [
    ]
