# Generated by Django 3.2.20 on 2024-06-12 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_alter_accounttopic_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDomainCI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='competing_interest_domains',
            field=models.ManyToManyField(blank=True, null=True, to='core.EmailDomainCI'),
        ),
    ]
