# Generated by Django 4.2.11 on 2024-05-01 16:15

import core.model_utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_merge_0088_fix_untyped_galleys_0092_xslt_1-6-0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='preferred_timezone',
            field=core.model_utils.DynamicChoiceField(blank=True, choices=[], max_length=300, null=True, verbose_name='Preferred Timezone'),
        ),
    ]
