# Generated by Django 4.2.11 on 2024-06-05 08:13

import core.model_utils
from django.db import migrations, models
from utils import migration_utils


def migrate_null_values(apps, schema_editor):
    model = apps.get_model('core', 'Account')
    fields = [
        'biography',
        'department',
        'first_name',
        'middle_name',
        'last_name',
        'institution',
        'salutation',
        'signature',
        'suffix',
    ]
    migration_utils.store_empty_strings(model, fields)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_alter_account_preferred_timezone'),
    ]

    operations = [
        migrations.RunPython(
            migrate_null_values,
            reverse_code=migrations.RunPython.noop
        ),
    ]
