# Generated by Django 4.2.11 on 2024-06-21 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_fix_journal_name_amp'),
        ('core', '0094_alter_account_preferred_timezone'),
    ]

    operations = [
    ]
