# Generated by Django 4.2.11 on 2024-06-13 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_auto_20240612_0103'),
        ('core', '0094_alter_account_preferred_timezone'),
    ]

    operations = [
    ]
