# Generated by Django 4.2.11 on 2024-06-13 22:11

import core.model_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_merge_20240613_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='preferred_timezone',
            field=core.model_utils.DynamicChoiceField(blank=True, choices=[], max_length=300, null=True, verbose_name='Preferred Timezone'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='recipient',
            field=models.EmailField(max_length=200, verbose_name='Who would you like to contact?'),
        ),
    ]
