# Generated by Django 4.2.11 on 2024-06-05 08:13

import core.model_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_account_fields_null_to_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='biography',
            field=core.model_utils.JanewayBleachField(blank=True, verbose_name='Biography'),
        ),
        migrations.AlterField(
            model_name='account',
            name='department',
            field=core.model_utils.JanewayBleachCharField(blank=True, max_length=300, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=core.model_utils.JanewayBleachCharField(max_length=300, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='institution',
            field=core.model_utils.JanewayBleachCharField(blank=True, max_length=1000, verbose_name='Institution'),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=core.model_utils.JanewayBleachCharField(max_length=300, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='middle_name',
            field=core.model_utils.JanewayBleachCharField(blank=True, max_length=300, verbose_name='Middle name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='salutation',
            field=core.model_utils.JanewayBleachCharField(blank=True, choices=[('Miss', 'Miss'), ('Ms', 'Ms'), ('Mrs', 'Mrs'), ('Mr', 'Mr'), ('Mx', 'Mx'), ('Dr', 'Dr'), ('Prof.', 'Prof.')], max_length=10, verbose_name='Salutation'),
        ),
        migrations.AlterField(
            model_name='account',
            name='signature',
            field=core.model_utils.JanewayBleachField(blank=True, verbose_name='Signature'),
        ),
        migrations.AlterField(
            model_name='account',
            name='suffix',
            field=core.model_utils.JanewayBleachCharField(blank=True, max_length=300, verbose_name='Name suffix'),
        ),
    ]
