# Generated by Django 4.2.11 on 2024-06-26 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_auto_20240605_1024'),
        ('core', '0095_merge_20240621_0722'),
    ]

    operations = [
    ]
