# Generated by Django 3.2.20 on 2024-08-19 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_alter_account_activation_code_and_more'),
        ('core', '0096_update_review_ack_email'),
    ]

    operations = [
    ]
