# Generated by Django 4.2 on 2024-08-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_update_review_ack_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='enable_datatables_save_state',
            field=models.BooleanField(default=False, help_text='Enable this option to allow searchable and sortable tables in the back office to retain their current state. This ensures that your search results and sorting preferences are preserved when you navigate away from the page and return later.', verbose_name='Preserve searchable/sortable table state'),
        ),
    ]
