# Generated by Django 4.2.15 on 2024-09-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_merge_20240819_1617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountrole',
            options={'ordering': ('journal', 'role')},
        ),
        migrations.AddField(
            model_name='account',
            name='orcid_token',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='orcid_token_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orcidtoken',
            name='access_token',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='orcidtoken',
            name='access_token_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
