# Generated by Django 4.2.11 on 2024-09-27 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_add_pii_filter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountrole',
            options={'ordering': ('journal', 'role')},
        ),
    ]
