# Generated by Django 4.2.15 on 2024-11-28 10:27

import core.model_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_alter_accountrole_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='name_es',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='role_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='editorialgroup',
            name='description_es',
            field=core.model_utils.JanewayBleachField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='editorialgroup',
            name='name_es',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='settingvalue',
            name='value_es',
            field=models.TextField(blank=True, null=True),
        ),
    ]
