# Generated by Django 4.2.16 on 2024-12-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_alter_accountrole_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDomainCI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='competing_interest_domains',
            field=models.ManyToManyField(blank=True, null=True, to='core.emaildomainci'),
        ),
    ]
