# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-11-28 10:28
from __future__ import unicode_literals

from django.db import migrations, models


def delete_blank_interests(apps, schema_editor):
    Interest = apps.get_model("core", "Interest")
    Interest.objects.filter(name="").delete()
    Interest.objects.filter(name=" ").delete()


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('core', '0100_contacts_name_es_contacts_role_es_and_more'),
    ]
    operations = [
        migrations.RunPython(
            delete_blank_interests, migrations.RunPython.noop
        ),
    ]
