# Generated by Django 4.2.18 on 2025-02-17 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_contact_ip_address_null'),
        ('core', '0101_delete_blank_keywords'),
    ]

    operations = [
    ]
