# Generated by Django 4.2.15 on 2025-02-04 12:18

from django.db import migrations


def update_typesetting_workflow_element(apps, schema_editor):
    WorkflowElement = apps.get_model("core", "WorkflowElement")
    WorkflowElement.objects.filter(
        element_name="Typesetting Plugin",
    ).update(
        element_name="typesetting",
    )


def reset_typesetting_workflow_element(apps, schema_editor):
    WorkflowElement = apps.get_model("core", "WorkflowElement")
    WorkflowElement.objects.filter(
        element_name="typesetting",
    ).update(
        element_name="Typesetting Plugin",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_contact_ip_address_null'),
    ]

    operations = [
        migrations.RunPython(
            update_typesetting_workflow_element,
            reverse_code=reset_typesetting_workflow_element,
        )
    ]
