# Generated by Django 4.2.20 on 2025-05-01 14:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0106_remove_account_country_affiliation_organization"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="controlledaffiliation",
            options={"ordering": ["-is_primary", "-end", "-start", "-pk"]},
        ),
        migrations.AlterModelOptions(
            name="organization",
            options={},
        ),
    ]
