# Generated by Django 4.2.18 on 2025-02-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_remove_account_country_affiliation_organization'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='affiliation',
            name='exclusive_fields_constraint',
        ),
        migrations.AddConstraint(
            model_name='affiliation',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('account__isnull', False), ('frozen_author__isnull', True), ('preprint_author__isnull', True)), models.Q(('frozen_author__isnull', False), ('account__isnull', True), ('preprint_author__isnull', True)), models.Q(('preprint_author__isnull', False), ('account__isnull', True), ('frozen_author__isnull', True)), ('account__isnull', True), models.Q(('account__isnull', True), ('frozen_author__isnull', True)), models.Q(('account__isnull', True), ('frozen_author__isnull', True), ('preprint_author__isnull', True)), _connector='OR'), name='exclusive_fields_constraint'),
        ),
    ]
