# Generated by Django 4.2.20 on 2025-05-06 09:49

from django.db import migrations, models
import utils.forms


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_remove_account_country_affiliation_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='display_initials',
            field=models.CharField(blank=True, help_text="Use this field to override the default initials generated from the user's full name.", max_length=6, validators=[utils.forms.plain_text_validator], verbose_name='Display initials'),
        ),
    ]
