# Generated by Django 4.2.21 on 2025-07-07 16:18

from django.conf import settings
from django.db import migrations, models
from django.utils import translation
import django.db.models.deletion


def connect_contact_person_to_account(apps, schema_editor):
    ContactPerson = apps.get_model("core", "ContactPerson")
    Account = apps.get_model("core", "Account")
    languages = ['cy', 'de', 'en', 'en-us', 'en_us', 'es', 'fr', 'it', 'nl']
    for contact_person in ContactPerson.objects.all():
        account, created = Account.objects.get_or_create(
            username=contact_person.email.lower(),
            defaults={
                'first_name': ' '.join(contact_person.name.split()[:-1]),
                'last_name': contact_person.name.split()[-1],
                'email': contact_person.email,
            }
        )
        contact_person.account = account
        for language in languages:
            with translation.override(language):
                language_var = "name_{}".format(language)
                setattr(contact_person, language_var, '')
        contact_person.email = ''
        contact_person.save()


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0107_alter_controlledaffiliation_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactMessage',
        ),
        migrations.RenameModel(
            old_name='Contacts',
            new_name='ContactPerson',
        ),
        migrations.AddField(
            model_name='contactperson',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='email',
            field=models.EmailField(blank=True, help_text="The 'email' field is deprecated. Use 'account.email'.", max_length=254),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='name',
            field=models.CharField(blank=True, help_text="The 'name' field is deprecated. Use 'account.full_name'.", max_length=300),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='name_cy',
            field=models.CharField(blank=True, help_text="The 'name' field is deprecated. Use 'account.full_name'.", max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='name_de',
            field=models.CharField(blank=True, help_text="The 'name' field is deprecated. Use 'account.full_name'.", max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='name_en',
            field=models.CharField(blank=True, help_text="The 'name' field is deprecated. Use 'account.full_name'.", max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='name_en_us',
            field=models.CharField(blank=True, help_text="The 'name' field is deprecated. Use 'account.full_name'.", max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='name_es',
            field=models.CharField(blank=True, help_text="The 'name' field is deprecated. Use 'account.full_name'.", max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='name_fr',
            field=models.CharField(blank=True, help_text="The 'name' field is deprecated. Use 'account.full_name'.", max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='name_nl',
            field=models.CharField(blank=True, help_text="The 'name' field is deprecated. Use 'account.full_name'.", max_length=300, null=True),
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='contactperson',
            options={'ordering': ('sequence',)},
        ),
        migrations.RunPython(
            connect_contact_person_to_account,
            reverse_code=migrations.RunPython.noop,
        )
    ]
