# Generated by Django 4.2.20 on 2025-06-24 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0107_alter_controlledaffiliation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowlog',
            name='user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
