# Generated by Django 4.2.21 on 2025-07-07 13:20

from django.db import migrations
from utils.migration_utils import replace_strings_in_setting_values


SETTINGS_TO_FIX = [
    [
        'editor_assignment',
        'Dear {{ editor.full_name',
        'Dear {{ editor.salutation_name',
    ],
    [
        'submission_acknowledgement',
        'Dear {{ article.correspondence_author.full_name',
        'Dear {{ article.correspondence_author.salutation_name',
    ],
    [
        'reviewer_acknowledgement',
        'Dear {{ review_assignment.editor.full_name',
        'Dear {{ review_assignment.editor.salutation_name',
    ],
    [
        'request_revisions',
        'Dear {{ article.correspondence_author.full_name',
        'Dear {{ article.correspondence_author.salutation_name',
    ],
    [
        'review_accept_acknowledgement',
        'Dear {{ review_assignment.reviewer.full_name',
        'Dear {{ review_assignment.reviewer.salutation_name',
    ],
    [
        'review_complete_reviewer_acknowledgement',
        'Dear {{ review_assignment.reviewer.full_name',
        'Dear {{ review_assignment.reviewer.salutation_name',
    ],
    [
        'review_request_sent',
        'Dear {{ review_assignment.editor.full_name',
        'Dear {{ review_assignment.editor.salutation_name',
    ],
    [
        'review_complete_acknowledgement',
        'Dear {{ review_assignment.editor.full_name',
        'Dear {{ review_assignment.editor.salutation_name',
    ],
    [
        'review_decline_acknowledgement',
        'Dear {{ review_assignment.reviewer.full_name',
        'Dear {{ review_assignment.reviewer.salutation_name',
    ],
    [
        'review_assignment',
        'Dear {{ review_assignment.reviewer.full_name',
        'Dear {{ review_assignment.reviewer.salutation_name',
    ],
    [
        'default_review_reminder',
        'Dear {{ review_assignment.reviewer.full_name',
        'Dear {{ review_assignment.reviewer.salutation_name',
    ],
    [
        'accepted_review_reminder',
        'Dear {{ review_assignment.reviewer.full_name',
        'Dear {{ review_assignment.reviewer.salutation_name',
    ],
    [
        'review_decision_accept',
        'Dear {{ article.correspondence_author.full_name',
        'Dear {{ article.correspondence_author.salutation_name',
    ],
    [
        'review_decision_decline',
        'Dear {{ article.correspondence_author.full_name',
        'Dear {{ article.correspondence_author.salutation_name',
    ],
    [
        'review_decision_undecline',
        'Dear {{ article.correspondence_author.full_name',
        'Dear {{ article.correspondence_author.salutation_name',
    ],
    [
        'unassign_editor',
        'Dear {{ assignment.editor.full_name',
        'Dear {{ assignment.editor.salutation_name',
    ],
    [
        'review_withdrawl',
        'Dear {{ review_assignment.reviewer.full_name',
        'Dear {{ review_assignment.reviewer.salutation_name',
    ],
    [
        'copyeditor_assignment_notification',
        'Dear {{ assignment.copyeditor.full_name',
        'Dear {{ assignment.copyeditor.salutation_name',
    ],
    [
        'copyeditor_notify_editor',
        'Dear {{ assignment.editor.full_name',
        'Dear {{ assignment.editor.salutation_name',
    ],
    [
        'copyeditor_notify_author',
        'Dear {{ assignment.article.correspondence_author.full_name',
        'Dear {{ assignment.article.correspondence_author.salutation_name',
    ],
    [
        'copyeditor_reopen_task',
        'Dear {{ assignment.copyeditor.full_name',
        'Dear {{ assignment.copyeditor.salutation_name',
    ],
    [
        'copyeditor_ack',
        'Dear {{ assignment.copyeditor.full_name',
        'Dear {{ assignment.copyeditor.salutation_name',
    ],
    [
        'author_copyedit_complete',
        'Dear {{ copyedit.editor.full_name',
        'Dear {{ copyedit.editor.salutation_name',
    ],
    [
        'production_manager_notification',
        'Dear {{ production_assignment.production_manager.full_name',
        'Dear {{ production_assignment.production_manager.salutation_name',
    ],
    [
        'typesetter_notification',
        'Dear {{ typeset_task.typesetter.full_name',
        'Dear {{ typeset_task.typesetter.salutation_name',
    ],
    [
        'typeset_ack',
        'Dear {{ production_assignment.editor.full_name',
        'Dear {{ production_assignment.editor.salutation_name',
    ],
    [
        'typeset_reopened',
        'Dear {{ typeset_task.typesetter.full_name',
        'Dear {{ typeset_task.typesetter.salutation_name',
    ],
    [
        'notify_proofing_manager',
        'Dear {{ proofing_assignment.proofing_manager.full_name',
        'Dear {{ proofing_assignment.proofing_manager.salutation_name',
    ],
    [
        'notify_proofreader_complete',
        'Dear {{ proofing_task.round.assignment.proofing_manager.full_name',
        'Dear {{ proofing_task.round.assignment.proofing_manager.salutation_name',
    ],
    [
        'notify_proofreader_assignment',
        'Dear {{ proofing_task.proofreader.full_name',
        'Dear {{ proofing_task.proofreader.salutation_name',
    ],
    [
        'notify_typesetter_proofing_changes',
        'Dear {{ typesetter_proofing_task.typesetter.full_name',
        'Dear {{ typesetter_proofing_task.typesetter.salutation_name',
    ],
    [
        'thank_proofreaders_and_typesetters',
        'Dear {{ user.full_name',
        'Dear {{ user.salutation_name',
    ],
    [
        'notify_editor_proofing_complete',
        'Dear {{ proofing_assignment.editor.full_name',
        'Dear {{ proofing_assignment.editor.salutation_name',
    ],
    [
        'notify_proofreader_cancelled',
        'Dear {{ proofing_task.proofreader.full_name',
        'Dear {{ proofing_task.proofreader.salutation_name',
    ],
    [
        'typesetter_corrections_complete',
        'Dear {{ article.proofingassignment.proofing_manager.full_name',
        'Dear {{ article.proofingassignment.proofing_manager.salutation_name',
    ],
    [
        'author_publication',
        'Dear {{ article.correspondence_author.full_name',
        'Dear {{ article.correspondence_author.salutation_name',
    ],
    [
        'password_reset',
        'Dear {{ reset_token.account.full_name',
        'Dear {{ reset_token.account.salutation_name',
    ],
    [
        'section_editor_pub_notification',
        'Dear {{ editor.full_name',
        'Dear {{ editor.salutation_name',
    ],
    [
        'production_assign_article',
        'Dear {{ user.full_name',
        'Dear {{ user.salutation_name',
    ],
    [
        'notification_submission',
        'Dear {{ notification.user.full_name',
        'Dear {{ notification.user.salutation_name',
    ],
    [
        'user_email_change',
        'Dear {{ user.full_name',
        'Dear {{ user.salutation_name',
    ],
    [
        'copyedit_updated',
        'Dear {{ copyedit_assignment.copyeditor.full_name',
        'Dear {{ copyedit_assignment.copyeditor.salutation_name',
    ],
    [
        'copyedit_deleted',
        'Dear {{ copyedit_assignment.copyeditor.full_name',
        'Dear {{ copyedit_assignment.copyeditor.salutation_name',
    ],
    [
        'typeset_deleted',
        'Dear {{ typeset_task.typesetter.full_name',
        'Dear {{ typeset_task.typesetter.salutation_name',
    ],
    [
        'notify_proofreader_edited',
        'Dear {{ proofing_task.proofreader.full_name',
        'Dear {{ proofing_task.proofreader.salutation_name',
    ],
    [
        'notify_correction_cancelled',
        'Dear {{ correction.typesetter.full_name',
        'Dear {{ correction.typesetter.salutation_name',
    ],
    [
        'notify_se_draft_declined',
        'Dear {{ draft_decision.section_editor.full_name',
        'Dear {{ draft_decision.section_editor.salutation_name',
    ],
    [
        'revisions_complete_receipt',
        'Dear {{ revision.article.correspondence_author.full_name',
        'Dear {{ revision.article.correspondence_author.salutation_name',
    ],
    [
        'submission_access_request_complete',
        'Dear {{ access_request.user.full_name',
        'Dear {{ access_request.user.salutation_name',
    ],
    [
        'author_copyedit_deleted',
        'Dear {{ author_review.assignment.article.correspondence_author.full_name',
        'Dear {{ author_review.assignment.article.correspondence_author.salutation_name',
    ],
    [
        'share_reviews_notification',
        'Dear {{ review.reviewer.full_name',
        'Dear {{ review.reviewer.salutation_name',
    ],
    [
        'typesetting_notify_typesetter',
        'Dear {{ assignment.typesetter.full_name',
        'Dear {{ assignment.typesetter.salutation_name',
    ],
    [
        'typsetting_typesetter_decision_accept',
        'Dear {{ assignment.manager.full_name',
        'Dear {{ assignment.manager.salutation_name',
    ],
    [
        'typsetting_typesetter_decision_decline',
        'Dear {{ assignment.manager.full_name',
        'Dear {{ assignment.manager.salutation_name',
    ],
    [
        'typesetting_typesetter_complete',
        'Dear {{ assignment.manager.full_name',
        'Dear {{ assignment.manager.salutation_name',
    ],
    [
        'typesetting_proofreader_completed',
        'Dear {{assignment.manager.full_name',
        'Dear {{assignment.manager.salutation_name',
    ],
    [
        'typesetting_proofreader_cancelled',
        'Dear {{assignment.proofreader.full_name',
        'Dear {{assignment.proofreader.salutation_name',
    ],
    [
        'typesetting_proofreader_reset',
        'Dear {{assignment.proofreader.full_name',
        'Dear {{assignment.proofreader.salutation_name',
    ],
    [
        'typesetting_typesetter_cancelled',
        'Dear {{assignment.proofreader.full_name',
        'Dear {{assignment.proofreader.salutation_name',
    ],
    [
        'typesetting_typesetter_deleted',
        'Dear {{assignment.proofreader.full_name',
        'Dear {{assignment.proofreader.salutation_name',
    ],
]

def use_salutation_name_in_email_salutations(apps, schema_editor):
    languages = ['en', 'en-us', 'en_us']
    for setting_name, old, new in SETTINGS_TO_FIX:
        replace_strings_in_setting_values(
            apps,
            setting_name,
            'email',
            [(old, new)],
            languages=languages,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0107_alter_controlledaffiliation_options_and_more'),
    ]

    operations = [
        migrations.RunPython(
            use_salutation_name_in_email_salutations,
            reverse_code=migrations.RunPython.noop
        ),
    ]
