# Generated by Django 4.2.22 on 2025-09-09 13:21

from django.db import migrations


def remove_empty_affiliations(apps, schema_editor):
    """
    Some legacy data has values of " " in the old institution field,
    so we remove the ControlledAffiliation records erroneously created from those values.
    """
    ControlledAffiliation = apps.get_model("core", "ControlledAffiliation")
    whitespace_affils = ControlledAffiliation.objects.filter(
        organization__custom_label__value=" ",
        organization__locations__isnull=True,
        organization__ror_id="",
        start__isnull=True,
        end__isnull=True,
        title="",
        department="",
    )
    whitespace_affils.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0108_workflowlog_user"),
    ]

    operations = [
        migrations.RunPython(
            remove_empty_affiliations,
            reverse_code=migrations.RunPython.noop,
        )
    ]
