# Generated by Django 4.2.20 on 2025-09-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0109_salutation_name_20250707_1420"),
    ]

    operations = [
        migrations.AddField(
            model_name="setting",
            name="depends_on_press_field",
            field=models.CharField(
                blank=True,
                help_text="If set, this setting is only available when the specified press setting is enabled.",
                max_length=100,
            ),
        ),
    ]
