# Generated by Django 4.2.20 on 2026-03-17 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0089_merge_20260226_1524'),
        ('core', '0109_salutation_name_20250707_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorPublicComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('public', models.BooleanField(default=True, help_text='Uncheck to hide this comment from public view.')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editor_public_comments', to='submission.article')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editor_public_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('date_posted',),
            },
        ),
    ]
