# Generated by Django 4.2.22 on 2025-12-12 13:49

import core.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0112_add_account_accessibility_mode"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="account",
            managers=[
                ("objects", core.models.AccountManager()),
            ],
        ),
    ]
