# Generated by Django 4.2.21 on 2025-07-07 16:18

from django.conf import settings
from django.db import migrations, models
from django.utils import translation
import django.db.models.deletion


def connect_contact_person_to_account(apps, schema_editor):
    ContactPerson = apps.get_model("core", "ContactPerson")
    Account = apps.get_model("core", "Account")
    languages = ["cy", "de", "en", "en-us", "en_us", "es", "fr", "it", "nl"]
    for contact_person in ContactPerson.objects.all():
        account, created = Account.objects.get_or_create(
            username=contact_person.email.lower(),
            defaults={
                "first_name": " ".join(contact_person.name.split()[:-1]),
                "last_name": contact_person.name.split()[-1],
                "email": contact_person.email,
            },
        )
        contact_person.account = account
        for language in languages:
            with translation.override(language):
                language_var = "name_{}".format(language)
                setattr(contact_person, language_var, "")
        contact_person.email = ""
        contact_person.save()


def connect_contact_message_to_account(apps, schema_editor):
    ContactMessage = apps.get_model("core", "ContactMessage")
    Account = apps.get_model("core", "Account")
    for contact_message in ContactMessage.objects.all():
        account, created = Account.objects.get_or_create(
            username=contact_message.recipient.lower(),
            defaults={
                "email": contact_message.recipient,
            },
        )
        contact_message.account = account
        contact_message.recipient = ""
        contact_message.client_ip = ""
        contact_message.save()


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0109_salutation_name_20250707_1420"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Contact",
            new_name="ContactMessage",
        ),
        migrations.RenameModel(
            old_name="Contacts",
            new_name="ContactPerson",
        ),
        migrations.AddField(
            model_name="contactperson",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="contactperson",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="The 'email' field is deprecated. Use 'account.email'.",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="contactperson",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="The 'name' field is deprecated. Use 'account.full_name'.",
                max_length=300,
            ),
        ),
        migrations.AlterField(
            model_name="contactperson",
            name="name_cy",
            field=models.CharField(
                blank=True,
                help_text="The 'name' field is deprecated. Use 'account.full_name'.",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contactperson",
            name="name_de",
            field=models.CharField(
                blank=True,
                help_text="The 'name' field is deprecated. Use 'account.full_name'.",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contactperson",
            name="name_en",
            field=models.CharField(
                blank=True,
                help_text="The 'name' field is deprecated. Use 'account.full_name'.",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contactperson",
            name="name_en_us",
            field=models.CharField(
                blank=True,
                help_text="The 'name' field is deprecated. Use 'account.full_name'.",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contactperson",
            name="name_es",
            field=models.CharField(
                blank=True,
                help_text="The 'name' field is deprecated. Use 'account.full_name'.",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contactperson",
            name="name_fr",
            field=models.CharField(
                blank=True,
                help_text="The 'name' field is deprecated. Use 'account.full_name'.",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contactperson",
            name="name_nl",
            field=models.CharField(
                blank=True,
                help_text="The 'name' field is deprecated. Use 'account.full_name'.",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contactperson",
            name="sequence",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Who would you like to contact?",
            ),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="client_ip",
            field=models.GenericIPAddressField(
                blank=True, help_text="The 'client_ip' field is deprecated.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="recipient",
            field=models.EmailField(
                help_text="The 'recipient' field is deprecated. Use 'account'.",
                max_length=200,
                blank=True,
            ),
        ),
        migrations.AlterModelOptions(
            name="contactmessage",
            options={},
        ),
        migrations.AlterModelOptions(
            name="contactperson",
            options={
                "ordering": ("sequence",),
                "verbose_name_plural": "contact people",
            },
        ),
        migrations.RunPython(
            connect_contact_person_to_account,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            connect_contact_message_to_account,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
