# Generated by Django 4.2.26 on 2026-01-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0109_salutation_name_20250707_1420"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="orcid_token",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="orcid_token_expiration",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orcidtoken",
            name="access_token",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="orcidtoken",
            name="access_token_expiration",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
