# Generated by Django 4.2.29 on 2026-06-03 22:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0110_alttext"),
        ("core", "0110_one_click_review_on_by_default"),
    ]

    operations = []
