# Generated by Django 4.2.26 on 2026-02-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_account_orcid_token_account_orcid_token_expiration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='date_orcid_requested',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
