# Generated by Django 4.2.21 on 2025-07-07 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0110_alter_account_managers"),
        ("utils", "0043_logentry_actor_email_alter_logentry_ip_address"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Contacts",
            new_name="ContactPerson",
        ),
        migrations.AddField(
            model_name="contactperson",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="contactperson",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="The 'email' field is deprecated. Use 'account.email'.",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="contactperson",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="The 'name' field is deprecated. Use 'account.full_name'.",
                max_length=300,
            ),
        ),
        migrations.AlterField(
            model_name="contactperson",
            name="name_cy",
            field=models.CharField(
                blank=True,
                help_text="The 'name' field is deprecated. Use 'account.full_name'.",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contactperson",
            name="name_de",
            field=models.CharField(
                blank=True,
                help_text="The 'name' field is deprecated. Use 'account.full_name'.",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contactperson",
            name="name_en",
            field=models.CharField(
                blank=True,
                help_text="The 'name' field is deprecated. Use 'account.full_name'.",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contactperson",
            name="name_en_us",
            field=models.CharField(
                blank=True,
                help_text="The 'name' field is deprecated. Use 'account.full_name'.",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contactperson",
            name="name_es",
            field=models.CharField(
                blank=True,
                help_text="The 'name' field is deprecated. Use 'account.full_name'.",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contactperson",
            name="name_fr",
            field=models.CharField(
                blank=True,
                help_text="The 'name' field is deprecated. Use 'account.full_name'.",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contactperson",
            name="name_nl",
            field=models.CharField(
                blank=True,
                help_text="The 'name' field is deprecated. Use 'account.full_name'.",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contactperson",
            name="sequence",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterModelOptions(
            name="contactperson",
            options={
                "ordering": ("sequence",),
                "verbose_name_plural": "contact people",
            },
        ),
    ]
