# Generated by Django 4.2.21 on 2025-07-07 16:18

from tqdm import tqdm

from django.conf import settings
from django.db import migrations, models, IntegrityError
import django.db.models.deletion
from utils.logger import get_logger

logger = get_logger(__name__)

ACCOUNT_CACHE = {}
TARGET_CACHE = {}


def get_account(apps, contact_email, contact_name):
    if contact_email in ACCOUNT_CACHE:
        return ACCOUNT_CACHE[contact_email]

    Account = apps.get_model("core", "Account")

    # Do the same preparation as Account.clean()
    email = Account.objects.normalize_email(contact_email)
    username = contact_email.lower()

    matching_accounts = Account.objects.filter(
        models.Q(email__iexact=email) | models.Q(username__iexact=username),
    )
    if matching_accounts.exists():
        account = matching_accounts.first()
    else:
        try:
            account = Account.objects.create(
                email=email,
                username=username,
                first_name=" ".join(contact_name.split()[:-1]) if contact_name else "",
                last_name=contact_name.split()[-1] if contact_name else "",
            )
        except IntegrityError:
            account = None

    if contact_email not in ACCOUNT_CACHE:
        ACCOUNT_CACHE[contact_email] = account

    return account


def connect_contact_person_to_account(apps, schema_editor):
    ContactPerson = apps.get_model("core", "ContactPerson")
    Journal = apps.get_model("journal", "Journal")
    Role = apps.get_model("core", "Role")
    AccountRole = apps.get_model("core", "AccountRole")
    for contact_person in ContactPerson.objects.all():
        account = get_account(apps, contact_person.email, contact_person.name)
        if contact_person.content_type.model == "journal":
            journal = Journal.objects.get(pk=contact_person.object_id)
            role = Role.objects.get(slug="author")
            AccountRole.objects.get_or_create(role=role, user=account, journal=journal)
        if account:
            contact_person.account = account
            contact_person.email = ""
            contact_person.save()


def infer_contact_message_target(apps, account):
    if account.pk in TARGET_CACHE:
        return TARGET_CACHE[account.pk]

    Journal = apps.get_model("journal", "Journal")
    Press = apps.get_model("press", "Press")
    ContactPerson = apps.get_model("core", "ContactPerson")
    ContentType = apps.get_model("contenttypes", "ContentType")

    contact_person_records = ContactPerson.objects.filter(account__pk=account.pk)
    is_staff = account.is_staff
    journals_where_editor = Journal.objects.filter(
        accountrole__user__pk=account.pk,
        accountrole__role__slug="editor",
    )

    if contact_person_records.count() == 1:
        # This person must have been contacted on the same site as their ContactPerson record.
        contact_person = contact_person_records.first()

        target_pieces = (contact_person.content_type, contact_person.object_id)
    elif is_staff and journals_where_editor.count() == 0:
        # This person must have been contacted in their press staff capacity.
        press = Press.objects.first()
        target_pieces = (ContentType.objects.get_for_model(press), press.pk)
    elif not is_staff and journals_where_editor.count() == 1:
        # This person must have been contacted in their journal editor capacity.
        journal = journals_where_editor[0]
        target_pieces = (ContentType.objects.get_for_model(journal), journal.pk)
    else:
        # This person has multiple roles, so we cannot infer the site where the
        # contact form was submitted.
        target_pieces = (None, None)
    if account.pk not in TARGET_CACHE:
        TARGET_CACHE[account.pk] = target_pieces

    return target_pieces


def move_contact_message_to_log_entry(apps, schema_editor):
    Contact = apps.get_model("core", "Contact")
    LogEntry = apps.get_model("utils", "LogEntry")
    Addressee = apps.get_model("utils", "Addressee")
    log_entries_to_create = []
    addressees_to_link_up = []

    for contact_message in Contact.objects.all():
        account = get_account(apps, contact_message.recipient, "")

        new_entry = LogEntry()
        new_entry.types = "Contact Message"
        new_entry.date = contact_message.date_sent
        new_entry.subject = contact_message.subject
        new_entry.description = contact_message.body
        new_entry.level = "Info"
        new_entry.actor = None
        new_entry.actor_email = contact_message.sender
        new_entry.request = None

        if contact_message.content_type and contact_message.object_id:
            # We set LogEntry.target explicitly, so it works with bulk_create.
            new_entry.content_type = contact_message.content_type
            new_entry.object_id = contact_message.object_id
        elif account:
            # The Contact was supposed store the journal or press in a field called `object`,
            # but due to a bug, it was not typically populated before this migration.
            # So we anticipate that in most cases, LogEntry.target will need to be inferred.
            content_type, object_id = infer_contact_message_target(apps, account)
            if content_type and object_id:
                new_entry.content_type = content_type
                new_entry.object_id = object_id

        new_entry.is_email = True
        new_entry.email_subject = contact_message.subject
        log_entries_to_create.append(new_entry)

        if account:
            addressee = Addressee()
            addressee.email = account.email
            addressee.field = "to"
            addressees_to_link_up.append(addressee)

    batch_size = 500
    log_entries = LogEntry.objects.bulk_create(log_entries_to_create, batch_size)

    if addressees_to_link_up:
        # Link up the addressees with their log entries
        addressees_to_create = []
        for i, addressee in enumerate(addressees_to_link_up):
            addressee.log_entry = log_entries[i]
            addressees_to_create.append(addressee)

        Addressee.objects.bulk_create(addressees_to_create, batch_size)

    Contact.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0110_alter_account_managers"),
        ("utils", "0043_logentry_actor_email_alter_logentry_ip_address"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Contacts",
            new_name="ContactPerson",
        ),
        migrations.AddField(
            model_name="contactperson",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="contactperson",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="The 'email' field is deprecated. Use 'account.email'.",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="contactperson",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="The 'name' field is deprecated. Use 'account.full_name'.",
                max_length=300,
            ),
        ),
        migrations.AlterField(
            model_name="contactperson",
            name="name_cy",
            field=models.CharField(
                blank=True,
                help_text="The 'name' field is deprecated. Use 'account.full_name'.",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contactperson",
            name="name_de",
            field=models.CharField(
                blank=True,
                help_text="The 'name' field is deprecated. Use 'account.full_name'.",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contactperson",
            name="name_en",
            field=models.CharField(
                blank=True,
                help_text="The 'name' field is deprecated. Use 'account.full_name'.",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contactperson",
            name="name_en_us",
            field=models.CharField(
                blank=True,
                help_text="The 'name' field is deprecated. Use 'account.full_name'.",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contactperson",
            name="name_es",
            field=models.CharField(
                blank=True,
                help_text="The 'name' field is deprecated. Use 'account.full_name'.",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contactperson",
            name="name_fr",
            field=models.CharField(
                blank=True,
                help_text="The 'name' field is deprecated. Use 'account.full_name'.",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contactperson",
            name="name_nl",
            field=models.CharField(
                blank=True,
                help_text="The 'name' field is deprecated. Use 'account.full_name'.",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contactperson",
            name="sequence",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterModelOptions(
            name="contactperson",
            options={
                "ordering": ("sequence",),
                "verbose_name_plural": "contact people",
            },
        ),
        migrations.RunPython(
            connect_contact_person_to_account,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            move_contact_message_to_log_entry,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
