# Generated by Django 4.2.20 on 2026-04-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0110_alttext"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="accessibility_mode",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, the site is presented using the Clarity accessibility-focused theme.",
                verbose_name="Accessibility mode",
            ),
        ),
    ]
