# Generated by Django 4.2.30 on 2026-09-03 17:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0110_account_date_orcid_requested_account_orcid_token_and_more"),
        ("core", "0111_merge_20260603_2206"),
    ]

    operations = []
