# Generated by Django 4.2.21 on 2025-07-07 16:18

from more_itertools import chunked
from hashlib import md5
import datetime

from django.db import migrations, models, IntegrityError, transaction
from django.utils import timezone
from utils.logger import get_logger

logger = get_logger(__name__)

ACCOUNT_CACHE = {}
TARGET_CACHE = {}


def get_or_create_account(apps, contact_email, contact_name):
    if not contact_email:
        return None

    if contact_email in ACCOUNT_CACHE:
        return ACCOUNT_CACHE[contact_email]

    Account = apps.get_model("core", "Account")

    # Do the same preparation as Account.clean()
    email = Account.objects.normalize_email(contact_email)
    username = contact_email.lower()

    matching_accounts = Account.objects.filter(
        models.Q(email__iexact=email) | models.Q(username__iexact=username),
    )
    if matching_accounts.exists():
        account = matching_accounts.first()
    else:
        try:
            account = Account.objects.create(
                email=email,
                username=username,
                first_name=" ".join(contact_name.split()[:-1]) if contact_name else "",
                last_name=contact_name.split()[-1] if contact_name else "",
            )
        except IntegrityError:
            print("integrity error")
            account = None

    if contact_email not in ACCOUNT_CACHE:
        ACCOUNT_CACHE[contact_email] = account

    return account


def connect_contact_person_to_account(apps, schema_editor):
    ContactPerson = apps.get_model("core", "ContactPerson")
    Journal = apps.get_model("journal", "Journal")
    Role = apps.get_model("core", "Role")
    AccountRole = apps.get_model("core", "AccountRole")
    unmigrated_contact_people = ContactPerson.objects.filter(
        account__isnull=True,
    ).exclude(
        email="",
    )
    for contact_person in unmigrated_contact_people:
        account = get_or_create_account(apps, contact_person.email, contact_person.name)
        if not account:
            continue

        contact_person.account = account
        contact_person.email = ""
        contact_person.save()

        if contact_person.content_type.model == "journal":
            journal = Journal.objects.get(pk=contact_person.object_id)
            role = Role.objects.get(slug="author")
            AccountRole.objects.get_or_create(role=role, user=account, journal=journal)


def infer_contact_message_target(apps, account):
    if account.pk in TARGET_CACHE:
        return TARGET_CACHE[account.pk]

    Journal = apps.get_model("journal", "Journal")
    Press = apps.get_model("press", "Press")
    ContactPerson = apps.get_model("core", "ContactPerson")
    ContentType = apps.get_model("contenttypes", "ContentType")

    contact_person_records = ContactPerson.objects.filter(account__pk=account.pk)
    is_staff = account.is_staff
    journals_where_editor = Journal.objects.filter(
        accountrole__user__pk=account.pk,
        accountrole__role__slug="editor",
    )

    if contact_person_records.count() == 1:
        # This person must have been contacted on the same site as their ContactPerson record.
        contact_person = contact_person_records.first()

        target_pieces = (contact_person.content_type, contact_person.object_id)
    elif is_staff and journals_where_editor.count() == 0:
        # This person must have been contacted in their press staff capacity.
        press = Press.objects.first()
        target_pieces = (ContentType.objects.get_for_model(press), press.pk)
    elif not is_staff and journals_where_editor.count() == 1:
        # This person must have been contacted in their journal editor capacity.
        journal = journals_where_editor[0]
        target_pieces = (ContentType.objects.get_for_model(journal), journal.pk)
    else:
        # This person has multiple roles, so we cannot infer the site where the
        # contact form was submitted.
        target_pieces = (None, None)
    if account.pk not in TARGET_CACHE:
        TARGET_CACHE[account.pk] = target_pieces

    return target_pieces


def hash_contact_message(*args):
    seed = "".join([str(arg) for arg in args])
    return md5(str(seed).encode("utf-8")).hexdigest()


def get_datetime_sent(date):
    datetime_sent = datetime.datetime.combine(date, datetime.time(12))
    return timezone.make_aware(datetime_sent)


def create_log_entry(apps, contact_message):
    LogEntry = apps.get_model("utils", "LogEntry")
    Addressee = apps.get_model("utils", "Addressee")

    account = get_or_create_account(apps, contact_message.recipient, "")
    if contact_message.content_type and contact_message.object_id:
        # We set LogEntry.target explicitly, so it works with bulk_create.
        content_type = contact_message.content_type
        object_id = contact_message.object_id
    elif account:
        # The Contact was supposed store the journal or press in a field called `object`,
        # but due to a bug, it was not typically populated before this migration.
        # So we anticipate that in most cases, LogEntry.target will need to be inferred.
        content_type, object_id = infer_contact_message_target(apps, account)
    else:
        content_type = None
        object_id = None

    datetime_sent = get_datetime_sent(contact_message.date_sent)

    new_entry = LogEntry.objects.create(
        types="Contact Message",
        date=datetime_sent,
        subject=contact_message.subject,
        description=contact_message.body,
        level="Info",
        actor=None,
        actor_email=contact_message.sender,
        content_type=content_type,
        object_id=object_id,
        is_email=True,
        email_subject=contact_message.subject,
    )

    if account:
        Addressee.objects.create(
            email=account.email,
            field="to",
            log_entry=new_entry,
        )


def move_contact_message_to_log_entry(apps, schema_editor):
    Contact = apps.get_model("core", "Contact")
    LogEntry = apps.get_model("utils", "LogEntry")

    # To avoid creating duplicates if the migration needs to be run multiple
    # times, we manually create a set of existing log entries to check against.
    # We do not use bulk_create in order to support MySQL with the
    # Addressee -> LogEntry relationship.
    # We also avoid get_or_create for performance, since there are usually
    # a lot of contact messages.
    entry_check_set = set()
    for entry in LogEntry.objects.filter(types="Contact Message"):
        datetime_sent = get_datetime_sent(entry.date)
        message_hash = hash_contact_message(
            entry.addressee_set.first().email,
            entry.actor_email,
            datetime_sent,
            entry.subject,
            entry.description,
        )
        entry_check_set.add(message_hash)

    batch_size = 500
    contact_messages = Contact.objects.all()

    for chunk in chunked(contact_messages, batch_size):
        with transaction.atomic():
            for contact_message in chunk:
                datetime_sent = get_datetime_sent(contact_message.date_sent)
                message_hash = hash_contact_message(
                    contact_message.recipient,
                    contact_message.sender,
                    datetime_sent,
                    contact_message.subject,
                    contact_message.body,
                )
                if message_hash in entry_check_set:
                    # Do not create duplicate log entries
                    continue

                create_log_entry(apps, contact_message)

    Contact.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0111_rename_contacts_contactperson_and_more"),
    ]

    operations = [
        migrations.RunPython(
            connect_contact_person_to_account,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            move_contact_message_to_log_entry,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
