# Generated by Django 4.2.29 on 2026-06-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0113_account_text_format_preferences"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="text_format_preferences",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Reading options (e.g. font, colour scheme,) chosen via the reading options bar, stored so they persist between visits.",
                verbose_name="Reading options preferences",
            ),
        ),
    ]
