# Generated by Django 4.2.29 on 2026-07-10 15:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0112_connect_contactperson_to_account_and_move_contact_to_logentry"),
        ("core", "0114_alter_account_text_format_preferences"),
    ]

    operations = []
