# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 13:02
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pluginsettingvalue',
            options={'base_manager_name': '_plain_manager'},
        ),
        migrations.AlterModelManagers(
            name='pluginsettingvalue',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
