# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_auto_20171113_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='subject',
            field=models.TextField(blank=True, null=True),
        ),
    ]
