# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_logentry_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='message_status',
            field=models.CharField(choices=[('no_information', 'No Information'), ('accepted', 'Accepted'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='no_information', max_length=255),
        ),
    ]
