# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0005_logentry_message_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='number_status_checks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='logentry',
            name='status_checks_complete',
            field=models.BooleanField(default=False),
        ),
    ]
