# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-08 15:14
from __future__ import unicode_literals

from django.db import migrations


def create_version(apps, schema_editor):
    Version = apps.get_model('utils', 'Version')

    versions = Version.objects.all()

    print(versions)

    if not versions:
        print('hi')
        Version.objects.create(number='1.2')


def delete_version(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0008_version'),
    ]

    operations = [
        migrations.RunPython(create_version, reverse_code=delete_version)
    ]
