# Generated by Django 2.2 on 2019-05-08 10:03

from django.db import migrations
import django.db.models.deletion
import hvad.fields


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0009_auto_20180808_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginsettingvalue',
            name='_hvad_query',
            field=hvad.fields.SingleTranslationObject('utils.PluginSettingValue', 'utils.PluginSettingValueTranslation'),
        ),
        migrations.AlterField(
            model_name='pluginsettingvaluetranslation',
            name='master',
            field=hvad.fields.MasterKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='utils.PluginSettingValue'),
        ),
    ]
