# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-23 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0009_auto_20180808_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='rollback',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
