# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-21 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0015_upgrade_1_3_8'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='toaddress',
            name='log_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.LogEntry'),
        ),
    ]
