# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-21 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0017_auto_20200721_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logentry',
            name='to',
        ),
    ]
