# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-22 16:35
from __future__ import unicode_literals

from django.db import migrations


def migrate_plugin_settings(apps, schema_editor):
    PluginSetting = apps.get_model('utils', 'PluginSetting')
    PluginSettingValue = apps.get_model('utils', 'PluginSettingValue')
    PluginSettingValueTranslation = apps.get_model('utils', 'PluginSettingValueTranslation')
    SettingGroup = apps.get_model('core', 'SettingGroup')
    Setting = apps.get_model('core', 'Setting')
    SettingValue = apps.get_model('core', 'SettingValue')

    plugin_settings = PluginSetting.objects.all()


    translations = PluginSettingValueTranslation.objects.all()

    for translation in translations:
        plugin_setting_value = PluginSettingValue.objects.get(
            pk=translation.master_id,
        )
        plugin_setting = plugin_setting_value.setting

        plugin_group_name = 'plugin:{plugin_name}'.format(
            plugin_name=plugin_setting.plugin.name,
        )
        setting_group, c = SettingGroup.objects.get_or_create(
            name=plugin_group_name,
            defaults={
                'enabled': True,
            }
        )
        setting, c = Setting.objects.get_or_create(
            name=plugin_setting.name,
            group=setting_group,
            types=plugin_setting.types,
            description=plugin_setting.description,
            is_translatable=plugin_setting.is_translatable,
        )
        setting_value, c = SettingValue.objects.get_or_create(
            journal=plugin_setting_value.journal,
            setting=setting,
        )
        setattr(setting_value, 'value_{}'.format(translation.language_code), translation.value)


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0019_upgrade_1_3_9'),
    ]

    operations = [
        migrations.RunPython(migrate_plugin_settings, reverse_code=migrations.RunPython.noop),
    ]
