# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-17 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0019_upgrade_1_3_9'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pluginsettingvaluetranslation',
            old_name='value',
            new_name='hvad_value',
        ),
    ]
