# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-03 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0019_upgrade_1_3_9'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pluginsettingvalue',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pluginsettingvaluetranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'plugin setting value Translation'},
        ),
        migrations.AlterModelManagers(
            name='pluginsettingvalue',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='pluginsettingvaluetranslation',
            name='language_code',
            field=models.CharField(db_index=True, max_length=15, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='pluginsettingvaluetranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='utils.PluginSettingValue'),
        ),
    ]
