# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-17 15:50
from __future__ import unicode_literals

from django.db import migrations, models


def migrate_plugin_settings(apps, schema_editor):
    PluginSettingValue = apps.get_model('utils', 'PluginSettingValue')
    PluginSettingValueTranslation = apps.get_model('utils', 'PluginSettingValueTranslation')

    translations = PluginSettingValueTranslation.objects.all()

    for translation in translations:
        setting = PluginSettingValue.objects.get(pk=translation.master_id)
        setattr(setting, 'value_{}'.format(translation.language_code), translation.hvad_value)
        setting.save()


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0019_upgrade_1_3_9'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pluginsettingvaluetranslation',
            old_name='value',
            new_name='hvad_value',
        ),

        migrations.AddField(
            model_name='pluginsettingvalue',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),

        migrations.AddField(
            model_name='pluginsettingvalue',
            name='value_cy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pluginsettingvalue',
            name='value_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pluginsettingvalue',
            name='value_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pluginsettingvalue',
            name='value_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RunPython(migrate_plugin_settings, reverse_code=migrations.RunPython.noop),
    ]
