# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-22 19:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0020_auto_20210222_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pluginsetting',
            name='plugin',
        ),
        migrations.RemoveField(
            model_name='pluginsettingvalue',
            name='journal',
        ),
        migrations.RemoveField(
            model_name='pluginsettingvalue',
            name='setting',
        ),
        migrations.AlterUniqueTogether(
            name='pluginsettingvaluetranslation',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='pluginsettingvaluetranslation',
            name='master',
        ),
        migrations.DeleteModel(
            name='PluginSetting',
        ),
        migrations.DeleteModel(
            name='PluginSettingValue',
        ),
        migrations.DeleteModel(
            name='PluginSettingValueTranslation',
        ),
    ]
