# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-17 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0021_pluginsettingvalue_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginsettingvalue',
            name='value_cy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pluginsettingvalue',
            name='value_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pluginsettingvalue',
            name='value_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pluginsettingvalue',
            name='value_fr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
