# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-24 09:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0020_upgrade_1_3_10'),
        ('utils', '0021_auto_20210222_1903'),
    ]

    operations = [
    ]
