# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-17 16:16
from __future__ import unicode_literals

from django.db import migrations


def migrate_plugin_settings(apps, schema_editor):
    PluginSettingValue = apps.get_model('utils', 'PluginSettingValue')
    PluginSettingValueTranslation = apps.get_model('utils', 'PluginSettingValueTranslation')

    translations = PluginSettingValueTranslation.objects.all()

    for translation in translations:
        setting = PluginSettingValue.objects.get(pk=translation.master_id)
        setattr(setting, 'value_{}'.format(translation.language_code), translation.hvad_value)
        setting.save()


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0022_auto_20210217_1602'),
    ]

    operations = [
        # noop for reverse as we're not actually deleting the data from SectionTranslation
        migrations.RunPython(migrate_plugin_settings, reverse_code=migrations.RunPython.noop),
    ]
