# Generated by Django 3.2.16 on 2023-03-17 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0028_upgrade_1_4_4'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toaddress',
            options={'verbose_name_plural': 'to addresses'},
        ),
    ]
