# Generated by Django 3.2.20 on 2024-05-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0033_upgrade_1_6_0'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToAddress',
            new_name='Addressee',
        ),
        migrations.AlterModelOptions(
            name='addressee',
            options={},
        ),
        migrations.AddField(
            model_name='addressee',
            name='field',
            field=models.CharField(blank=True, choices=[('to', 'To'), ('cc', 'CC'), ('bcc', 'BCC')], max_length=3),
        ),
    ]
