# Generated by Django 4.2.11 on 2024-06-13 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0034_rename_toaddress_addressee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addressee',
            options={},
        ),
    ]
