# Generated by Django 4.2.15 on 2024-10-25 14:18

from django.db import migrations, models
from django.utils import timezone

VERSION = "1.7.1"


def rollback(apps, schema_editor):
    version_model = apps.get_model("utils", "Version")
    latest_version = version_model.objects.get(number=VERSION, rollback=None)
    latest_version.rollback = timezone.now()
    latest_version.save()


def upgrade(apps, schema_editor):
    version_model = apps.get_model("utils", "Version")
    new_version = version_model.objects.create(number=VERSION)
    new_version.save()


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0036_typesetting_guide'),
    ]

    operations = [
        migrations.RunPython(upgrade, reverse_code=rollback),
    ]
