# Generated by Django 4.2.20 on 2025-06-27 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0040_upgrade_1_7_5'),
        ('utils', '0041_rorimport_rorimporterror'),
    ]

    operations = [
    ]
