# Generated by Django 4.2.22 on 2025-09-17 17:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("utils", "0042_merge_20250627_0840"),
    ]

    def disable_typesetting_plugin(apps, schema_editor):
        Plugin = apps.get_model("utils", "Plugin")
        Plugin.objects.filter(name="typesetting").update(enabled=False)

    def enable_typesetting_plugin(apps, schema_editor):
        Plugin = apps.get_model("utils", "Plugin")
        Plugin.objects.filter(name="typesetting").update(enabled=True)

    operations = [
        migrations.RunPython(
            disable_typesetting_plugin, reverse_code=enable_typesetting_plugin
        ),
    ]
