# Generated by Django 4.2.22 on 2025-12-03 13:18

from django.db import migrations, models


def delete_log_entry_ip_addresses(apps, schema_editor):
    LogEntry = apps.get_model("utils", "LogEntry")
    LogEntry.objects.update(ip_address=None)


class Migration(migrations.Migration):
    dependencies = [
        ("utils", "0042_merge_20250627_0840"),
    ]

    operations = [
        migrations.AddField(
            model_name="logentry",
            name="actor_email",
            field=models.EmailField(
                blank=True,
                help_text="The email address of an unauthenticated actor.",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="logentry",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True, help_text="Deprecated field", null=True
            ),
        ),
        migrations.RunPython(
            delete_log_entry_ip_addresses, reverse_code=migrations.RunPython.noop
        ),
    ]
