# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-16 10:52
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.postgres.operations import CITextExtension


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [CITextExtension()]
