# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('preprint', '0005_auto_20171010_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='preprintversion',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
