# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preprint', '0007_auto_20171013_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
