# Generated by Django 3.2.16 on 2023-03-22 14:12

from django.db import migrations, models


def preserve_old_formatting(apps, schema_editor):
    """
    The new support_copy_paste field has a default value of True,
    because we want bleach to work on all new content by default.
    However, we don't want it to wipe out custom styling in existing
    fields, so the default for existing objects should be False.
    """
    NewsItem = apps.get_model('comms', 'NewsItem')
    objs = NewsItem.objects.all()
    for obj in objs:
        obj.support_copy_paste = False
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0003_newsitem_custom_byline'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='support_copy_paste',
            field=models.BooleanField(default=True, help_text='Turn this on if copy-pasting content into rich-text fields from a word processor or using the toolbar to format text. Turn it off only if you are editing HTML and CSS using the code view.'),
        ),
        migrations.RunPython(preserve_old_formatting, reverse_code=migrations.RunPython.noop),
    ]
