# Generated by Django 3.2.20 on 2024-02-01 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0004_auto_20230223_1328'),
        ('comms', '0005_historicalnewsitem'),
    ]

    operations = [
    ]
