# Generated by Django 3.2.20 on 2024-03-12 09:22

import core.model_utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0005_historicalnewsitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalnewsitem',
            name='support_copy_paste',
        ),
        migrations.RemoveField(
            model_name='newsitem',
            name='support_copy_paste',
        ),
        migrations.AlterField(
            model_name='historicalnewsitem',
            name='body',
            field=core.model_utils.JanewayBleachField(),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='body',
            field=core.model_utils.JanewayBleachField(),
        ),
    ]
