# Generated by Django 3.2.18 on 2024-02-06 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0006_merge_0004_auto_20230223_1328_0005_historicalnewsitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnewsitem',
            name='pinned',
            field=models.BooleanField(
                default=False,
                help_text='Pinned news items will appear at the top of the news '
                          'list',
            ),
        ),
    ]
