# Generated by Django 3.2.20 on 2024-03-15 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0006_auto_20240312_0922'),
        ('comms', '0007_news_item_pinned_20240206_0855'),
    ]

    operations = [
    ]
