# Generated by Django 3.2.20 on 2024-04-15 12:02

import core.model_utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0008_merge_20240315_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnewsitem',
            name='title',
            field=core.model_utils.JanewayBleachCharField(),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='title',
            field=core.model_utils.JanewayBleachCharField(),
        ),
    ]
