# Generated by Django 4.2.20 on 2026-03-31 19:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comms", "0010_historicalnewsitem_body_cy_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newsitem",
            options={"ordering": ("-pinned", "sequence", "-start_display", "title")},
        ),
    ]
