# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 13:02
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django.db.models.manager
import submission.models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='section',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='meta_image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/Users/ajrbyers/Code/janeway/src/media'), upload_to=submission.models.article_media_upload),
        ),
    ]
