# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0003_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission.Article')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission.Field')),
            ],
        ),
    ]
