# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0004_fieldanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='width',
            field=models.CharField(choices=[('third', 'Third'), ('half', 'Half'), ('full,', 'Full')], default='full', max_length=50),
        ),
    ]
