# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_auto_20170813_1302'),
        ('submission', '0005_field_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='journal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='journal.Journal'),
        ),
    ]
