# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0008_auto_20170907_1652'),
        ('submission', '0008_auto_20170907_1159'),
    ]

    operations = [
    ]
