# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0009_merge_20170907_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='licence',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='submission.Licence'),
        ),
    ]
