# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 09:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0010_auto_20170915_1146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licence',
            options={'ordering': ('order', 'name')},
        ),
    ]
