# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0012_auto_20170929_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='journal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.Journal'),
        ),
    ]
