# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0012_presssetting_is_boolean'),
        ('submission', '0016_auto_20171106_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='press',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='press.Press'),
        ),
        migrations.AlterField(
            model_name='field',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.Journal'),
        ),
    ]
