# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0017_auto_20171114_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='preprint_journal_article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='submission.Article'),
        ),
    ]
