# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-22 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0019_auto_20171130_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='non_specialist_summary',
            field=models.TextField(blank=True, help_text='A summary of the article for non specialists.', null=True),
        ),
    ]
