# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-17 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_supplementaryfile'),
        ('submission', '0020_article_non_specialist_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='supplementary_files',
            field=models.ManyToManyField(blank=True, null=True, related_name='supp', to='core.SupplementaryFile'),
        ),
    ]
