# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-03 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0010_auto_20180412_1544'),
        ('submission', '0021_article_supplementary_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_fees', models.BooleanField(default=True)),
                ('submission_check', models.BooleanField(default=True)),
                ('copyright_notice', models.BooleanField(default=True)),
                ('competing_interests', models.BooleanField(default=True)),
                ('comments_to_the_editor', models.BooleanField(default=True)),
                ('subtitle', models.BooleanField(default=True)),
                ('abstract', models.BooleanField(default=True)),
                ('language', models.BooleanField(default=True)),
                ('license', models.BooleanField(default=True)),
                ('keywords', models.BooleanField(default=True)),
                ('figures_data', models.BooleanField(default=True)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Journal')),
            ],
        ),
    ]
