# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-03 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0023_auto_20180503_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionconfiguration',
            name='journal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='journal.Journal'),
        ),
    ]
