# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-10 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0025_auto_20180508_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionconfiguration',
            name='section',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='submissionconfiguration',
            name='figures_data',
            field=models.BooleanField(default=True, verbose_name='Figures and Data Files'),
        ),
    ]
