# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-06 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0026_auto_20180510_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.TextField(blank=True, null=True),
        ),
    ]
