# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-16 11:44
from __future__ import unicode_literals

import core.file_system
from django.db import migrations, models
import submission.models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0027_auto_20180806_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='meta_image',
            field=models.ImageField(blank=True, null=True, storage=core.file_system.JanewayFileSystemStorage(), upload_to=submission.models.article_media_upload),
        ),
    ]
