# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-25 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0029_auto_20181128_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionconfiguration',
            name='keywords',
            field=models.BooleanField(default=False),
        ),
    ]
