# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-13 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0030_rename_readable_stages'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='display',
            field=models.BooleanField(default=False, help_text='Whether or not display this field in the article page'),
        ),
    ]
