# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-02 00:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0030_auto_20190225_1449'),
        ('submission', '0031_field_display'),
    ]

    operations = [
    ]
