# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-26 22:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0032_merge_20190301_1650'),
        ('submission', '0032_auto_20190304_0916'),
    ]

    operations = [
    ]
