# Generated by Django 2.2 on 2019-05-08 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hvad.fields


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0033_frozenauthor_is_corporate'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='_hvad_query',
            field=hvad.fields.SingleTranslationObject('submission.Section', 'submission.SectionTranslation'),
        ),
        migrations.AlterField(
            model_name='article',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='journal.Journal'),
        ),
        migrations.AlterField(
            model_name='article',
            name='preprint_journal_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='submission.Article'),
        ),
        migrations.AlterField(
            model_name='frozenauthor',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='submission.Article'),
        ),
        migrations.AlterField(
            model_name='frozenauthor',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='frozenauthor',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Country'),
        ),
        migrations.AlterField(
            model_name='sectiontranslation',
            name='master',
            field=hvad.fields.MasterKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='submission.Section'),
        ),
        migrations.AlterField(
            model_name='submissionconfiguration',
            name='default_license',
            field=models.ForeignKey(help_text='The default license applied when no option is presented', null=True, on_delete=django.db.models.deletion.SET_NULL, to='submission.Licence'),
        ),
        migrations.AlterField(
            model_name='submissionconfiguration',
            name='default_section',
            field=models.ForeignKey(help_text='The default section of articles when no option is presented', null=True, on_delete=django.db.models.deletion.SET_NULL, to='submission.Section'),
        ),
    ]
