# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-08 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_merge_20190405_1549'),
        ('submission', '0035_auto_20190712_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='source_Files',
            field=models.ManyToManyField(blank=True, related_name='source_files', to='core.File'),
        ),
    ]
