# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-08 12:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0036_article_source_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='source_Files',
            new_name='source_files',
        ),
    ]
