# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-12 16:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0037_auto_20190808_1326'),
        ('submission', '0035_auto_20190712_2015'),
    ]

    operations = [
    ]
