# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-20 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0040_article_projected_issue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('fundref_id', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='funders',
            field=models.ManyToManyField(blank=True, to='submission.Funder'),
        ),
    ]
