# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-23 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0041_submission_stage_dynamic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='primary_issue',
            field=models.ForeignKey(blank=True, help_text='You can only assign an Issue that this Article is part of.You can add this article to and Issue from the Issue Manager.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='journal.Issue'),
        ),
    ]
