# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-20 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0041_auto_20200220_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='funder',
            name='funding_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
