# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-23 10:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0042_auto_20200423_1534'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='article',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='is_preprint',
        ),
        migrations.RemoveField(
            model_name='article',
            name='preprint_decision_notification',
        ),
    ]
