# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-14 13:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0041_auto_20200203_1547'),
        ('submission', '0042_auto_20200227_1051'),
    ]

    operations = [
    ]
