# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-04 10:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0045_auto_20200528_1204'),
        ('submission', '0045_auto_20200529_1415'),
    ]

    operations = [
    ]
