# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-20 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0046_merge_20200604_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Subtitle of the article display format; Title: Subtitle', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(help_text='Your article title', max_length=999),
        ),
    ]
