# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-26 13:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0043_auto_20200523_1158'),
        ('submission', '0046_merge_20200604_1040'),
    ]

    operations = [
    ]
