# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-01 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0047_auto_20200720_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionconfiguration',
            name='submission_file_text',
            field=models.CharField(default='Manuscript File', help_text='During submission the author will be asked to upload a filethat is considered the main text of the article. You can usethis field to change the label for that file in submission.', max_length=255),
        ),
    ]
