# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-17 15:52
from __future__ import unicode_literals

from django.db import migrations, models


def migrate_sections(apps, schema_editor):
    Section = apps.get_model('submission', 'Section')
    SectionTranslation = apps.get_model('submission', 'SectionTranslation')

    translations = SectionTranslation.objects.all()

    for translation in translations:
        section = Section.objects.get(pk=translation.master_id)
        setattr(section, 'name_{}'.format(translation.language_code), translation.hvad_name)
        setattr(section, 'plural_{}'.format(translation.language_code), translation.hvad_plural)
        section.save()


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0050_support_ordered_keywords'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectiontranslation',
            old_name='name',
            new_name='hvad_name',
        ),
        migrations.RenameField(
            model_name='sectiontranslation',
            old_name='plural',
            new_name='hvad_plural',
        ),
        migrations.AddField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='plural',
            field=models.CharField(blank=True, help_text='Pluralised name for the section (e.g: Article -> Articles)',
                                   max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='name_cy',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='name_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='name_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='plural_cy',
            field=models.CharField(blank=True, help_text='Pluralised name for the section (e.g: Article -> Articles)',
                                   max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='plural_de',
            field=models.CharField(blank=True, help_text='Pluralised name for the section (e.g: Article -> Articles)',
                                   max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='plural_en',
            field=models.CharField(blank=True, help_text='Pluralised name for the section (e.g: Article -> Articles)',
                                   max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='plural_fr',
            field=models.CharField(blank=True, help_text='Pluralised name for the section (e.g: Article -> Articles)',
                                   max_length=200, null=True),
        ),
    ]
