# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-22 14:52
from __future__ import unicode_literals

import core.model_utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0050_support_ordered_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='keywords',
            field=core.model_utils.M2MOrderedThroughField(blank=True, null=True, through='submission.KeywordArticle', to='submission.Keyword'),
        ),
    ]
