# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-25 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0051_auto_20210222_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='frozenauthor',
            name='name_prefix',
            field=models.CharField(blank=True, help_text='Optional name prefix (e.g: Prof or Dr)', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='frozenauthor',
            name='name_suffix',
            field=models.CharField(blank=True, help_text='Optional name suffix (e.g.: Jr or III)', max_length=300, null=True),
        ),
    ]
