# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-17 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0052_auto_20210217_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='name_cy',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='name_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='name_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='plural_cy',
            field=models.CharField(blank=True, help_text='Pluralised name for the section (e.g: Article -> Articles)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='plural_de',
            field=models.CharField(blank=True, help_text='Pluralised name for the section (e.g: Article -> Articles)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='plural_en',
            field=models.CharField(blank=True, help_text='Pluralised name for the section (e.g: Article -> Articles)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='plural_fr',
            field=models.CharField(blank=True, help_text='Pluralised name for the section (e.g: Article -> Articles)', max_length=200, null=True),
        ),
    ]
