# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-24 09:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0052_auto_20210525_1743'),
        ('submission', '0053_auto_20210222_1849'),
    ]

    operations = [
    ]
