# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-29 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0054_merge_20210624_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='name_nl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='plural_nl',
            field=models.CharField(blank=True, help_text='Pluralised name for the section (e.g: Article -> Articles)', max_length=200, null=True),
        ),
    ]
