# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-11 15:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0047_merge_20200626_1336'),
        ('submission', '0056_auto_20210803_0906'),
    ]

    operations = [
    ]
