# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-27 08:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0057_unique_keywords'),
        ('submission', '0057_frozen_email_and_orcid'),
    ]

    operations = [
    ]
