# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-09-23 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager
import submission.models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0059_better_page_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='frozenauthor',
            name='display_email',
            field=models.BooleanField(default=False, help_text='If checked, this authors email address link will be displayed on the article page.'),
        ),
    ]
