# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-11 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0058_auto_20210812_1254'),
        ('submission', '0061_auto_20210923_1615'),
    ]

    operations = [
    ]
