# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-13 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager
import submission.models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0061_auto_20210923_1615'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='article',
            managers=[
                ('allarticles', django.db.models.manager.Manager()),
                ('objects', submission.models.ArticleManager()),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='publication_title',
            field=models.CharField(blank=True, help_text='Name of the publisher who published this article Only relevant to migrated articles from a different publisher', max_length=999, null=True),
        ),
    ]
