# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-07 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0062_auto_20211013_1133'),
        ('submission', '0062_merge_20211011_0906'),
    ]

    operations = [
    ]
