# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-15 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0063_merge_20211207_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='frozenauthor',
            name='frozen_biography',
            field=models.TextField(blank=True, null=True, verbose_name='Frozen Biography'),
        ),
    ]
