# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-01 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0065_auto_20211221_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frozenauthor',
            name='institution',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
