# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-27 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0067_auto_20220321_1306'),
        ('submission', '0066_auto_20220201_1042'),
    ]

    operations = [
    ]
