# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-26 10:28
from __future__ import unicode_literals

from django.db import migrations, models


def delete_blank_keywords(apps, schema_editor):
    Keyword = apps.get_model("submission", "Keyword")
    Keyword.objects.filter(word="").delete()
    Keyword.objects.filter(word=" ").delete()


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('submission', '0068_merge_20220427_1042'),
    ]
    operations = [
        migrations.RunPython(
            delete_blank_keywords, migrations.RunPython.noop
        ),
    ]
