# Generated by Django 3.2.16 on 2023-03-17 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0070_auto_20230120_1546'),
        ('submission', '0070_auto_20230208_1233'),
    ]

    operations = [
    ]
