# Generated by Django 3.2.16 on 2023-06-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0071_merge_0070_auto_20230120_1546_0070_auto_20230208_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='reviews_shared',
            field=models.BooleanField(default=False, help_text='Marked true when an editor manually shares reviews with other reviewers using the decision helper page.'),
        ),
    ]
