# Generated by Django 3.2.19 on 2023-05-24 15:17

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0071_merge_0070_auto_20230120_1546_0070_auto_20230208_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frozenauthor',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
