# Generated by Django 3.2.20 on 2023-11-10 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0073_bleach_title_20230523_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionconfiguration',
            name='open_peer_review_license',
            field=models.ForeignKey(blank=True, help_text='The license that is applied to open peer reviews.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='open_peer_review_license', to='submission.licence'),
        ),
    ]
