# Generated by Django 3.2.20 on 2024-05-22 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_auto_20240522_0701'),
        ('submission', '0075_auto_20240506_0904'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_type', models.CharField(choices=[('PR', 'Primary'), ('SE', 'Secondary')], default='PR', max_length=2)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission.article')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.topics')),
            ],
            options={
                'unique_together': {('article', 'topic')},
            },
        ),
        migrations.AddField(
            model_name='article',
            name='study_topic',
            field=models.ManyToManyField(blank=True, null=True, related_name='study_topics', through='submission.ArticleTopic', to='core.Topics'),
        ),
    ]
