# Generated by Django 3.2.20 on 2024-05-24 17:29

import core.model_utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0075_auto_20240312_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_published',
            field=core.model_utils.DateTimePickerModelField(blank=True, null=True),
        ),
    ]
