# Generated by Django 3.2.20 on 2024-05-28 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_alter_accounttopic_unique_together'),
        ('submission', '0076_auto_20240522_0701'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='articletopic',
            unique_together={('article', 'topic', 'topic_type')},
        ),
    ]
