# Generated by Django 3.2.20 on 2024-06-02 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_alter_accounttopic_unique_together'),
        ('submission', '0077_alter_articletopic_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='articletopic',
            unique_together={('article', 'topic')},
        ),
    ]
