# Generated by Django 3.2.20 on 2024-04-16 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0075_auto_20240312_0922'),
        ('submission', '0077_auto_20240402_1326'),
    ]

    operations = [
    ]
