# Generated by Django 3.2.20 on 2024-05-01 14:32

import core.model_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0078_merge_0075_auto_20240312_0922_0077_auto_20240402_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frozenauthor',
            name='department',
            field=core.model_utils.JanewayBleachCharField(blank=True, default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='frozenauthor',
            name='first_name',
            field=core.model_utils.JanewayBleachCharField(blank=True, default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='frozenauthor',
            name='frozen_biography',
            field=core.model_utils.JanewayBleachField(blank=True, default='', help_text="The author's biography at the time they published the linked article. For this article only, it overrides any main biography attached to the author's account. If Frozen Biography is left blank, any main biography for the account will be populated instead.", verbose_name='Frozen Biography'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='frozenauthor',
            name='institution',
            field=core.model_utils.JanewayBleachCharField(blank=True, default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='frozenauthor',
            name='last_name',
            field=core.model_utils.JanewayBleachCharField(blank=True, default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='frozenauthor',
            name='middle_name',
            field=core.model_utils.JanewayBleachCharField(blank=True, default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='frozenauthor',
            name='name_prefix',
            field=core.model_utils.JanewayBleachCharField(blank=True, default='', help_text='Optional name prefix (e.g: Prof or Dr)', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='frozenauthor',
            name='name_suffix',
            field=core.model_utils.JanewayBleachCharField(blank=True, default='', help_text='Optional name suffix (e.g.: Jr or III)', max_length=300),
            preserve_default=False,
        ),
    ]
