# Generated by Django 4.2.11 on 2024-06-02 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0076_alter_article_date_published'),
        ('submission', '0078_merge_0075_auto_20240312_0922_0077_auto_20240402_1326'),
    ]

    operations = [
    ]
