# Generated by Django 3.2.20 on 2024-06-04 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('submission', '0078_alter_articletopic_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleAccountCompetingInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission.article')),
            ],
            options={
                'unique_together': {('article', 'account')},
            },
        ),
    ]
