# Generated by Django 4.2.11 on 2024-06-13 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0079_auto_20240605_0105'),
        ('submission', '0079_merge_20240602_1739'),
    ]

    operations = [
    ]
