# Generated by Django 4.2.11 on 2024-08-21 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0066_topic_topicordering'),
        ('submission', '0079_merge_20240602_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='journal.topic'),
        ),
    ]
