# Generated by Django 3.2.20 on 2024-06-04 19:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('submission', '0079_articleaccountcompetinginterest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleAccountCompetingInterest',
            new_name='ArticleAccountCI',
        ),
        migrations.AddField(
            model_name='article',
            name='account_competing_interests',
            field=models.ManyToManyField(blank=True, null=True, related_name='account_competing_interests', through='submission.ArticleAccountCI', to=settings.AUTH_USER_MODEL),
        ),
    ]
