# Generated by Django 4.2.14 on 2024-07-26 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0079_merge_20240602_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frozenauthor',
            name='country',
        ),
        migrations.RemoveField(
            model_name='frozenauthor',
            name='department',
        ),
        migrations.RemoveField(
            model_name='frozenauthor',
            name='institution',
        ),
    ]
