# Generated by Django 3.2.20 on 2024-06-04 19:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('submission', '0080_auto_20240604_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='account_competing_interests',
        ),
        migrations.AddField(
            model_name='article',
            name='competing_interest_accounts',
            field=models.ManyToManyField(blank=True, null=True, related_name='competing_interest_accounts', through='submission.ArticleAccountCI', to=settings.AUTH_USER_MODEL),
        ),
    ]
