# Generated by Django 4.2.16 on 2024-11-21 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('submission', '0081_auto_20240927_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(blank=True, choices=[('conceptualization', 'Conceptualization'), ('data-curation', 'Data Curation'), ('formal-analysis', 'Formal Analysis'), ('funding-acquisition', 'Funding Acquisition'), ('investigation', 'Investigation'), ('methodology', 'Methodology'), ('project-administration', 'Project Administration'), ('resources', 'Resources'), ('software', 'Software'), ('supervision', 'Supervision'), ('validation', 'Validation'), ('visualization', 'Visualization'), ('writing-original-draft', 'Writing - Original Draft'), ('writing-review-editing', 'Writing - Review & Editing')], max_length=100, null=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='submission.article')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('frozen_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='submission.frozenauthor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
