# Generated by Django 4.2.16 on 2024-11-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0081_auto_20240927_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='jats_article_type',
            field=models.CharField(blank=True, choices=[('abstract', 'Abstract'), ('addendum', 'Addendum'), ('announcement', 'Announcement'), ('article-commentary', 'Article Commentary'), ('back-matter', 'Back Matter'), ('bibliography', 'Bibliography'), ('book-review', 'Book Review'), ('brief-report', 'Brief Report'), ('calendar', 'Calendar'), ('case-report', 'Case Report'), ('collection', 'Collection'), ('comment', 'Comment'), ('correction', 'Correction'), ('data-note', 'Data Note'), ('discussion', 'Discussion'), ('dissertation', 'Dissertation'), ('editorial', 'Editorial'), ('essay', 'Essay'), ('exhibition', 'Exhibition'), ('expression-of-concern', 'Expression of Concern'), ('fictional-work', 'Fictional Work'), ('front-matter', 'Front Matter'), ('interview', 'Interview'), ('introduction', 'Introduction'), ('legal-case', 'Legal Case'), ('letter-to-the-editor', 'Letter to the Editor'), ('meeting-report', 'Meeting Report'), ('media-review', 'Media Review'), ('method', 'Method'), ('multimedia-article', 'Multimedia Article'), ('note', 'Note'), ('obituary', 'Obituary'), ('oration', 'Oration'), ('pictorial-work', 'Pictorial Work'), ('plain-language-summary', 'Plain Language Summary'), ('poetry', 'Poetry'), ('product-review', 'Product Review'), ('rapid-communication', 'Rapid Communication'), ('registered-report', 'Registered Report'), ('reply', 'Reply'), ('report', 'Report'), ('research-article', 'Research Article'), ('research-letter', 'Research Letter'), ('retraction', 'Retraction'), ('review-article', 'Review Article'), ('target-article', 'Target Article'), ('other', 'Other')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='jats_article_type',
            field=models.CharField(blank=True, choices=[('abstract', 'Abstract'), ('addendum', 'Addendum'), ('announcement', 'Announcement'), ('article-commentary', 'Article Commentary'), ('back-matter', 'Back Matter'), ('bibliography', 'Bibliography'), ('book-review', 'Book Review'), ('brief-report', 'Brief Report'), ('calendar', 'Calendar'), ('case-report', 'Case Report'), ('collection', 'Collection'), ('comment', 'Comment'), ('correction', 'Correction'), ('data-note', 'Data Note'), ('discussion', 'Discussion'), ('dissertation', 'Dissertation'), ('editorial', 'Editorial'), ('essay', 'Essay'), ('exhibition', 'Exhibition'), ('expression-of-concern', 'Expression of Concern'), ('fictional-work', 'Fictional Work'), ('front-matter', 'Front Matter'), ('interview', 'Interview'), ('introduction', 'Introduction'), ('legal-case', 'Legal Case'), ('letter-to-the-editor', 'Letter to the Editor'), ('meeting-report', 'Meeting Report'), ('media-review', 'Media Review'), ('method', 'Method'), ('multimedia-article', 'Multimedia Article'), ('note', 'Note'), ('obituary', 'Obituary'), ('oration', 'Oration'), ('pictorial-work', 'Pictorial Work'), ('plain-language-summary', 'Plain Language Summary'), ('poetry', 'Poetry'), ('product-review', 'Product Review'), ('rapid-communication', 'Rapid Communication'), ('registered-report', 'Registered Report'), ('reply', 'Reply'), ('report', 'Report'), ('research-article', 'Research Article'), ('research-letter', 'Research Letter'), ('retraction', 'Retraction'), ('review-article', 'Review Article'), ('target-article', 'Target Article'), ('other', 'Other')], max_length=255, null=True),
        ),
    ]
