# Generated by Django 4.2.16 on 2024-11-21 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0045_historicalrepository_display_public_metrics_and_more'),
        ('submission', '0082_creditrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditrecord',
            name='preprint_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='repository.preprintauthor'),
        ),
    ]
