# Generated by Django 4.2.16 on 2024-11-26 16:32

import core.model_utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0082_article_jats_article_type_section_jats_article_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='jats_article_type',
            field=core.model_utils.DynamicChoiceField(blank=True, choices=[], help_text="The type of article as per the JATS standard. The initial state of this field is set by the submission section's article type.", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='jats_article_type',
            field=core.model_utils.DynamicChoiceField(blank=True, choices=[], help_text="The default JATS article type for articles in this section. This can be overridden on a per-article basis. Changing this will not change any existing article's type.", max_length=255, null=True, verbose_name='JATS default article type'),
        ),
    ]
