# Generated by Django 4.2.16 on 2024-11-27 10:21

import core.model_utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0083_alter_article_jats_article_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='jats_article_type',
        ),
        migrations.AddField(
            model_name='article',
            name='jats_article_type_override',
            field=core.model_utils.DynamicChoiceField(blank=True, choices=[], default=None, help_text="The type of article as per the JATS standard. This field allows you to override the default for the section.", max_length=255, null=True),
        ),
    ]
