# Generated by Django 4.2.16 on 2025-05-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0083_keyword_created_keyword_deactivated_keyword_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionconfiguration',
            name='hierarchical_keywords',
            field=models.BooleanField(default=False),
        ),
    ]
