# Generated by Django 4.2.20 on 2025-03-18 09:31

import core.model_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0083_article_jats_article_type_override_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitationStyleLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalized_name', models.CharField(blank=True, help_text='The name of the CSL XML document', max_length=200)),
                ('display_name', models.CharField(blank=True, help_text='The title from the CSL XML document', max_length=200)),
                ('csl_id', models.CharField(blank=True, help_text='The URI ID from the CSL XML document', max_length=200)),
            ],
        ),
    ]
