# Generated by Django 4.2.18 on 2025-02-20 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0045_historicalrepository_display_public_metrics_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('submission', '0084_remove_frozenauthor_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(blank=True, choices=[('conceptualization', 'Conceptualization'), ('data-curation', 'Data Curation'), ('formal-analysis', 'Formal Analysis'), ('funding-acquisition', 'Funding Acquisition'), ('investigation', 'Investigation'), ('methodology', 'Methodology'), ('project-administration', 'Project Administration'), ('resources', 'Resources'), ('software', 'Software'), ('supervision', 'Supervision'), ('validation', 'Validation'), ('visualization', 'Visualization'), ('writing-original-draft', 'Writing - Original Draft'), ('writing-review-editing', 'Writing - Review & Editing')], max_length=100, null=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='submission.article')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('frozen_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='submission.frozenauthor')),
                ('preprint_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repository.preprintauthor')),
            ],
            options={
                'verbose_name': 'CRediT record',
                'verbose_name_plural': 'CRediT records',
                'ordering': ['role'],
            },
        ),
        migrations.AddConstraint(
            model_name='creditrecord',
            constraint=models.CheckConstraint(
                check=models.Q(models.Q(('author__isnull', False), ('frozen_author__isnull', True), ('preprint_author__isnull', True)), models.Q(('frozen_author__isnull', False), ('author__isnull', True), ('preprint_author__isnull', True)), models.Q(('preprint_author__isnull', False), ('author__isnull', True), ('frozen_author__isnull', True)), ('author__isnull', True), models.Q(('author__isnull', True), ('frozen_author__isnull', True)), models.Q(('author__isnull', True), ('frozen_author__isnull', True), ('preprint_author__isnull', True)), _connector='OR'),
                name='exclusive_fields_credit_record_author_frozen_author_preprintb7fd',
            ),
        ),
    ]
