# Generated by Django 4.2.18 on 2025-02-17 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0082_article_abstract_es_article_title_es_section_name_es_and_more'),
        ('submission', '0084_remove_article_jats_article_type_and_more'),
    ]

    operations = [
    ]
