# Generated by Django 4.2.16 on 2024-12-04 15:55

import core.model_utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('repository', '0045_historicalrepository_display_public_metrics_and_more'),
        ('submission', '0084_remove_article_jats_article_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='jats_article_type_override',
            field=core.model_utils.DynamicChoiceField(blank=True, choices=[], default=None, help_text='The type of article as per the JATS standard. This field allows you to override the default for the section.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='jats_article_type',
            field=core.model_utils.DynamicChoiceField(blank=True, choices=[], help_text='The default JATS article type for articles in this section. This can be overridden on a per-article basis.', max_length=255, null=True, verbose_name='JATS default article type'),
        ),
        migrations.CreateModel(
            name='CreditRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(blank=True, choices=[('Conceptualization', 'Conceptualization'), ('Data Curation', 'Data Curation'), ('Formal Analysis', 'Formal Analysis'), ('Funding Acquisition', 'Funding Acquisition'), ('Investigation', 'Investigation'), ('Methodology', 'Methodology'), ('Project Administration', 'Project Administration'), ('Resources', 'Resources'), ('Software', 'Software'), ('Supervision', 'Supervision'), ('Validation', 'Validation'), ('Visualization', 'Visualization'), ('Writing - Original Draft', 'Writing - Original Draft'), ('Writing - Review & Editing', 'Writing - Review & Editing')], max_length=100, null=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='submission.article')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('frozen_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='submission.frozenauthor')),
                ('preprint_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='repository.preprintauthor')),
            ],
            options={
                'verbose_name': 'CRediT record',
                'verbose_name_plural': 'CRediT records',
            },
        ),
    ]
