# Generated by Django 4.2.16 on 2025-06-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0084_submissionconfiguration_hierarchical_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionconfiguration',
            name='autocomplete_keywords',
            field=models.BooleanField(default=False),
        ),
    ]
