# Generated by Django 4.2.16 on 2024-12-10 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_topicgroup_topics_accounttopic'),
        ('submission', '0084_remove_article_jats_article_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_type', models.CharField(choices=[('PR', 'Primary'), ('SE', 'Secondary')], default='PR', max_length=2)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission.article')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.topics')),
            ],
            options={
                'unique_together': {('article', 'topic')},
            },
        ),
    ]
