# Generated by Django 4.2.16 on 2024-12-15 10:41

import core.model_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_account_study_topic'),
        ('submission', '0085_articletopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='study_topic',
            field=models.ManyToManyField(blank=True, null=True, related_name='study_topics', through='submission.ArticleTopic', to='core.topics'),
        ),
    ]
