# Generated by Django 4.2.20 on 2025-04-03 16:32

from django.db import migrations

from utils.migration_utils import update_default_setting_values


def handle_update(apps, schema_editor):
    # The setting user_automatically_author was removed
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0085_creditrecord_and_more"),
    ]

    operations = [
        migrations.RunPython(
            handle_update,
            reverse_code=migrations.RunPython.noop,
        )
    ]
