# Generated by Django 4.2.20 on 2025-05-01 14:17

import core.model_utils
from django.db import migrations, models
import utils.orcid


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0086_auto_20250403_1732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frozenauthor',
            options={'ordering': ('order', 'pk'), 'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
        migrations.AlterField(
            model_name='frozenauthor',
            name='display_email',
            field=models.BooleanField(default=False, help_text="Whether to display this author's email address on the published article."),
        ),
        migrations.AlterField(
            model_name='frozenauthor',
            name='frozen_biography',
            field=core.model_utils.JanewayBleachField(blank=True, verbose_name='Biography'),
        ),
        migrations.AlterField(
            model_name='frozenauthor',
            name='frozen_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='frozenauthor',
            name='frozen_orcid',
            field=models.CharField(blank=True, help_text='ORCID to be displayed when no account is associated with this author.', max_length=40, validators=[utils.orcid.validate_orcid], verbose_name='ORCID'),
        ),
        migrations.AlterField(
            model_name='frozenauthor',
            name='is_corporate',
            field=models.BooleanField(default=False, help_text='Whether the author is an organization. The display name will be formed from the affiliation.'),
        ),
        migrations.AlterUniqueTogether(
            name='creditrecord',
            unique_together={('frozen_author', 'role')},
        ),
    ]
