# Generated by Django 4.2.20 on 2025-07-29 12:50

import core.model_utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0088_auto_20250506_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission.field')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission.section')),
            ],
            options={
                'ordering': ('order',),
                'unique_together': {('field', 'section')},
            },
        ),
        migrations.AddField(
            model_name='field',
            name='sections',
            field=core.model_utils.M2MOrderedThroughField(blank=True, related_name='fields', through='submission.FieldSection', to='submission.section'),
        ),
    ]
