# Generated by Django 4.2.29 on 2026-07-21 12:56

import core.model_utils
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0089_merge_20260226_1524"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="custom_how_to_cite_cy",
            field=core.model_utils.JanewayBleachField(
                blank=True,
                help_text="Custom 'how to cite' text. To be used only if the block generated by Janeway is not suitable.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="custom_how_to_cite_de",
            field=core.model_utils.JanewayBleachField(
                blank=True,
                help_text="Custom 'how to cite' text. To be used only if the block generated by Janeway is not suitable.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="custom_how_to_cite_en",
            field=core.model_utils.JanewayBleachField(
                blank=True,
                help_text="Custom 'how to cite' text. To be used only if the block generated by Janeway is not suitable.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="custom_how_to_cite_en_us",
            field=core.model_utils.JanewayBleachField(
                blank=True,
                help_text="Custom 'how to cite' text. To be used only if the block generated by Janeway is not suitable.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="custom_how_to_cite_es",
            field=core.model_utils.JanewayBleachField(
                blank=True,
                help_text="Custom 'how to cite' text. To be used only if the block generated by Janeway is not suitable.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="custom_how_to_cite_fr",
            field=core.model_utils.JanewayBleachField(
                blank=True,
                help_text="Custom 'how to cite' text. To be used only if the block generated by Janeway is not suitable.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="custom_how_to_cite_nl",
            field=core.model_utils.JanewayBleachField(
                blank=True,
                help_text="Custom 'how to cite' text. To be used only if the block generated by Janeway is not suitable.",
                null=True,
            ),
        ),
    ]
