# Generated by Django 4.2.29 on 2026-05-14 07:11

import core.model_utils
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0089_merge_20260226_1524"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="stage",
            field=core.model_utils.DynamicChoiceField(
                blank=True,
                choices=[
                    ("Unsubmitted", "Unsubmitted"),
                    ("Unassigned", "Unassigned"),
                    ("Screening", "Screening"),
                    ("Assigned", "Assigned to Editor"),
                    ("Under Review", "Peer Review"),
                    ("Under Revision", "Revision"),
                    ("Rejected", "Rejected"),
                    ("Accepted", "Accepted"),
                    ("Editor Copyediting", "Editor Copyediting"),
                    ("Author Copyediting", "Author Copyediting"),
                    ("Final Copyediting", "Final Copyediting"),
                    ("Typesetting", "Typesetting"),
                    ("typesetting_plugin", "typesetting_plugin"),
                    ("Proofing", "Proofing"),
                    ("pre_publication", "Pre Publication"),
                    ("Published", "Published"),
                    ("preprint_review", "Preprint Review"),
                    ("preprint_published", "Preprint Published"),
                    ("Archived", "Archived"),
                ],
                default="Unsubmitted",
                help_text="<strong>WARNING</strong>: Manually changing the stage of a submission             overrides Janeway's workflow. It should only be changed to a value             which is know to be safe such as a stage an article has already             been a part of before.",
                max_length=200,
            ),
        ),
    ]
