# Generated by Django 4.2.29 on 2026-09-24 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0071_journal_issue_article_grouping_topic_topicordering"),
        ("submission", "0089_merge_20260226_1524"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                help_text="The thematic group this article belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="journal.topic",
            ),
        ),
        migrations.AddField(
            model_name="submissionconfiguration",
            name="topic",
            field=models.BooleanField(
                default=False,
                help_text="Lets authors select a topic for their article. Only topics that are open for submissions are presented to authors.",
            ),
        ),
    ]
