# Generated by Django 4.2.29 on 2026-04-27 11:51

from django.db import migrations, models
import django.db.models.deletion
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0089_merge_20260226_1524"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genealogy",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "children",
                    sortedm2m.fields.SortedManyToManyField(
                        help_text=None,
                        related_name="ancestors",
                        to="submission.article",
                    ),
                ),
                (
                    "parent",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="genealogy",
                        to="submission.article",
                        verbose_name="Original or main paper",
                    ),
                ),
            ],
        ),
    ]
