# Generated by Django 4.2.29 on 2026-09-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0089_merge_20260226_1524"),
    ]

    operations = [
        migrations.AddField(
            model_name="fieldanswer",
            name="field_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="A snapshot of the field's name, retained if the field is deleted.",
                max_length=200,
            ),
        ),
    ]
