# Generated by Django 4.2.29 on 2026-09-03 14:47

import core.model_utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0090_article_custom_how_to_cite_cy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="field",
            name="description",
            field=core.model_utils.JanewayBleachField(
                blank=True,
                help_text="Description of the field to show to the user.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="FieldChoice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "real_value",
                    models.CharField(
                        blank=True,
                        help_text="Value used for exports and internal processing",
                        max_length=200,
                    ),
                ),
                (
                    "display_value",
                    models.CharField(
                        help_text="Value displayed to users", max_length=200
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_choices",
                        related_query_name="field_choices",
                        to="submission.field",
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
                "unique_together": {("field", "real_value")},
            },
        ),
        migrations.AddField(
            model_name="fieldanswer",
            name="choice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="submission.fieldchoice",
            ),
        ),
        migrations.CreateModel(
            name="FieldSection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="submission.field",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="submission.section",
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
                "unique_together": {("field", "section")},
            },
        ),
    ]
