# Generated by Django 4.2.30 on 2026-09-03 17:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0089_frozenauthor_is_frozen_orcid_valid"),
        ("submission", "0090_article_custom_how_to_cite_cy_and_more"),
    ]

    operations = []
