# Generated by Django 4.2.29 on 2026-10-07 11:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0090_article_topic_submissionconfiguration_topic"),
        ("submission", "0091_populate_fieldanswer_field_name"),
    ]

    operations = []
