# Generated by Django 4.2.29 on 2026-08-27 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0090_article_custom_how_to_cite_cy_and_more"),
        ("submission", "0092_merge_0089_merge_20260226_1524_0091_alter_field_slug"),
    ]

    operations = []
