# Generated by Django 4.2.29 on 2026-09-01 10:16

import core.model_utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0094_fieldchoice_fieldanswer_choice"),
    ]

    operations = [
        migrations.AddField(
            model_name="field",
            name="description",
            field=core.model_utils.JanewayBleachField(
                blank=True,
                help_text="Description of the field to show to the user.",
                null=True,
            ),
        ),
    ]
