# Generated by Django 4.2.18 on 2025-02-27 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0083_article_jats_article_type_override_and_more'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customarticleactiondate',
            name='article',
            field=models.OneToOneField(help_text='A custom date for the editorial team to know when to act next onan article.', on_delete=django.db.models.deletion.CASCADE, related_name='custom_next_date', to='submission.article'),
        ),
        migrations.AlterField(
            model_name='customarticlelabel',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_label', to='submission.article'),
        ),
    ]
