from django.urls import path
from django.urls import re_path

from typesetting import views

urlpatterns = [
    path("manager/", views.typesetting_manager, name="typesetting_manager"),
    path("", views.typesetting_articles, name="typesetting_articles"),
    path(
        "article/<int:article_id>/makegalley/file/<int:file_id>/",
        views.article_file_make_galley,
        name="typesetting_article_file_make_galley",
    ),
    path(
        "article/<int:article_id>/",
        views.typesetting_article,
        name="typesetting_article",
    ),
    path(
        "article/<int:article_id>/typesetter/<int:assignment_id>/review/",
        views.typesetting_review_assignment,
        name="typesetting_review_assignment",
    ),
    re_path(
        r"^article/(?P<article_id>\d+)/action/(?P<action>claim|unclaim)$",
        views.typesetting_claim_article,
        name="typesetting_claim_article",
    ),
    path(
        "article/<int:article_id>/galley/<int:galley_id>/edit/",
        views.typesetting_edit_galley,
        name="typesetting_edit_galley",
    ),
    path(
        "article/<int:article_id>/galley/upload/",
        views.typesetting_upload_galley,
        name="typesetting_upload_galley",
    ),
    path(
        "correction/<int:correction_id>/delete/",
        views.typesetting_delete_correction,
        name="typesetting_delete_correction",
    ),
    path(
        "article/<int:article_id>/galley/upload/",
        views.typesetting_upload_galley,
        name="typesetting_upload_galley",
    ),
    path(
        "article/<int:article_id>/assign/typesetter/",
        views.typesetting_assign_typesetter,
        name="typesetting_assign_typesetter",
    ),
    path(
        "article/<int:article_id>/typesetter/<int:assignment_id>/notify/",
        views.typesetting_notify_typesetter,
        name="typesetting_notify_typesetter",
    ),
    path("assignments/", views.typesetting_assignments, name="typesetting_assignments"),
    path(
        "assignments/typesetting/<int:assignment_id>/",
        views.typesetting_assignment,
        name="typesetting_assignment",
    ),
    path(
        "assignments/typesetting/<int:assignment_id>/download/<int:file_id>/",
        views.typesetting_typesetter_download_file,
        name="typesetting_typesetter_download_file",
    ),
    path(
        "article/<int:article_id>/assignment/<int:assignment_id>/galley/upload/",
        views.typesetting_upload_galley,
        name="typesetting_assignment_upload_galley",
    ),
    path(
        "article/<int:article_id>/assign/proofreader/",
        views.typesetting_assign_proofreader,
        name="typesetting_assign_proofreader",
    ),
    path(
        "article/<int:article_id>/assign/proofreader/<int:assignment_id>/notify/",
        views.typesetting_notify_proofreader,
        name="typesetting_notify_proofreader",
    ),
    path(
        "article/<int:article_id>/proofreader/<int:assignment_id>/review/",
        views.typesetting_manage_proofing_assignment,
        name="typesetting_manage_proofing_assignment",
    ),
    path(
        "assignments/proofreading/",
        views.typesetting_proofreading_assignments,
        name="typesetting_proofreading_assignments",
    ),
    path(
        "assignments/proofreading/<int:assignment_id>/",
        views.typesetting_proofreading_assignment,
        name="typesetting_proofreading_assignment",
    ),
    path(
        "preview_galley/article/<int:article_id>/galley/<int:galley_id>/assignment/<int:assignment_id>/",
        views.typesetting_preview_galley,
        name="typesetting_preview_galley",
    ),
    path(
        "preview_galley/article/<int:article_id>/galley/<int:galley_id>/",
        views.typesetting_preview_galley,
        name="editor_preview_galley",
    ),
    path(
        "preview/article/<int:article_id>/assignment/<int:assignment_id>/file/<int:file_id>/",
        views.typesetting_proofing_download,
        name="typesetting_proofing_download",
    ),
    re_path(
        r"^preview_galley/article/(?P<article_id>\d+)/galley/(?P<galley_id>\d+)/assignment/(?P<assignment_id>\d+)/figures/(?P<file_name>.*)$",
        views.preview_figure,
        name="proofreader_preview_figure",
    ),
    re_path(
        r"^preview_galley/article/(?P<article_id>\d+)/galley/(?P<galley_id>\d+)/assignment/(?P<assignment_id>\d+)/(?P<file_name>.*)$",
        views.preview_figure,
        name="proofreader_preview_figure_b",
    ),
    re_path(
        r"^preview_galley/article/(?P<article_id>\d+)/galley/(?P<galley_id>\d+)/figures/(?P<file_name>.*)$",
        views.preview_figure,
        name="typesetter_preview_figure",
    ),
    re_path(
        r"^preview_galley/article/(?P<article_id>\d+)/galley/(?P<galley_id>\d+)/(?P<file_name>.*)$",
        views.preview_figure,
        name="typesetter_preview_figure_b",
    ),
    path(
        "article/<int:article_id>/file/<int:file_id>/download/",
        views.typesetting_download_file,
        name="typesetting_download_file",
    ),
    path(
        "galley/<int:galley_id>/delete/",
        views.typesetting_delete_galley,
        name="typesetting_delete_galley",
    ),
    path(
        "supp-file/<int:supp_file_id>/doi/",
        views.mint_supp_doi,
        name="typesetting_mint_supp_doi",
    ),
]
