# Generated by Django 2.2 on 2019-05-08 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationitem',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.Page'),
        ),
        migrations.AlterField(
            model_name='navigationitem',
            name='top_level_nav',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.NavigationItem', verbose_name='Top Level Nav Item'),
        ),
    ]
