# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-10 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_migrate_issue_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationitem',
            name='link_name_cy',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='navigationitem',
            name='link_name_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='navigationitem',
            name='link_name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='navigationitem',
            name='link_name_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='content_cy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='content_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='content_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='content_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='display_name_cy',
            field=models.CharField(help_text='Name of the page, max 100 chars, displayed in the nav and on the header of the page eg. About or Contact', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='display_name_de',
            field=models.CharField(help_text='Name of the page, max 100 chars, displayed in the nav and on the header of the page eg. About or Contact', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='display_name_en',
            field=models.CharField(help_text='Name of the page, max 100 chars, displayed in the nav and on the header of the page eg. About or Contact', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='display_name_fr',
            field=models.CharField(help_text='Name of the page, max 100 chars, displayed in the nav and on the header of the page eg. About or Contact', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(help_text='Page name displayed in the URL bar eg. about or contact', max_length=300, verbose_name='URL Name'),
        ),
    ]
