# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-18 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_auto_20210513_1206'),
        ('journal', '0043_auto_20210518_1616'),
        ('cms', '0003_auto_20210510_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_fr', models.CharField(max_length=255, null=True)),
                ('title_de', models.CharField(max_length=255, null=True)),
                ('title_cy', models.CharField(max_length=255, null=True)),
                ('text', models.TextField()),
                ('text_en', models.TextField(null=True)),
                ('text_fr', models.TextField(null=True)),
                ('text_de', models.TextField(null=True)),
                ('text_cy', models.TextField(null=True)),
                ('order', models.IntegerField(default=99)),
                ('existing_setting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Setting')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Journal')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='submissionitem',
            unique_together=set([('journal', 'title'), ('journal', 'existing_setting')]),
        ),
    ]
