# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-18 16:19
from __future__ import unicode_literals

from django.db import migrations


def setup_submission_items(apps, schema_editor):
    SubmissionItem = apps.get_model('cms', 'SubmissionItem')


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_submissionitem'),
    ]

    operations = [
    ]
