# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-18 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20210518_1619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submissionitem',
            options={'ordering': ('order', 'title')},
        ),
        migrations.AlterField(
            model_name='submissionitem',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submissionitem',
            name='text_cy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submissionitem',
            name='text_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submissionitem',
            name='text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submissionitem',
            name='text_fr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
