# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-25 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_auto_20210629_0641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navigationitem',
            options={'ordering': ('sequence',)},
        ),
        migrations.AlterField(
            model_name='navigationitem',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
