# Generated by Django 3.2.18 on 2023-04-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_auto_20230317_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationitem',
            name='for_footer',
            field=models.BooleanField(
                default=False,
                help_text='Whether this item should appear in the footer. '
                          'Not implemented for all themes.',
            ),
        ),
    ]
