# Generated by Django 3.2.20 on 2024-02-01 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_page_template'),
        ('cms', '0015_historicalpage'),
    ]

    operations = [
    ]
