# Generated by Django 3.2.18 on 2024-02-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_merge_0013_page_template_0015_historicalpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpage',
            name='template',
            field=models.CharField(
                blank=True,
                help_text='The custom template to use instead of the content '
                          'field.',
                max_length=100,
            ),
        ),
    ]
