# Generated by Django 3.2.20 on 2024-03-15 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20240312_0922'),
        ('cms', '0017_historicalpage_template'),
    ]

    operations = [
    ]
