# Generated by Django 4.2.21 on 2025-06-25 15:34

from django.db import migrations


def split_links_from_top_level_navs(apps, schema_editor):
    NavigationItem = apps.get_model('cms.NavigationItem')
    for nav_item in NavigationItem.objects.filter(
        link__isnull=False,
        has_sub_nav=True,
    ):
        # Remove the link from the top level nav item
        link = nav_item.link
        top_level_pk = nav_item.pk
        nav_item.link = None
        nav_item.save()

        # Add it back to a version of the nav item
        # that will be saved separately
        new_sub_nav_item = NavigationItem.objects.get(pk=top_level_pk)
        new_sub_nav_item.pk = None
        new_sub_nav_item.has_sub_nav = False
        new_sub_nav_item.top_level_nav = nav_item
        new_sub_nav_item.link = link
        new_sub_nav_item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_historicalpage_content_es_and_more'),
    ]

    operations = [
        migrations.RunPython(
            split_links_from_top_level_navs,
            reverse_code=migrations.RunPython.noop,
        )
    ]
