# Generated by Django 5.2.17 on 2026-08-30 17:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0023_page_draft_preview"),
        ("core", "0115_merge_20260710_1655"),
        ("journal", "0070_move_journal_is_archived_to_journal_status"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="submissionitem",
            unique_together={
                ("journal", "existing_setting"),
                ("journal", "title"),
                ("journal", "title_cy"),
                ("journal", "title_de"),
                ("journal", "title_en"),
                ("journal", "title_en_us"),
                ("journal", "title_es"),
                ("journal", "title_fr"),
                ("journal", "title_nl"),
            },
        ),
    ]
