# Generated by Django 4.2.29 on 2026-06-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0024_historicalpage_draft_preview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpage",
            name="is_draft",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="page",
            name="is_draft",
            field=models.BooleanField(default=False),
        ),
    ]
