# Generated by Django 4.2.29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0026_data_migration_set_existing_pages_draft_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpage",
            name="is_draft",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="page",
            name="is_draft",
            field=models.BooleanField(default=True),
        ),
    ]
