# Generated by Django 4.2.29 on 2026-05-15 15:46

import core.model_utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0112_editor_assignment_primary_urls"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("journal", "0068_issue_cached_display_title_a11y_and_more"),
        ("submission", "0090_alter_article_stage"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScreeningAssignment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recommendation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("accept_for_peer_review", "Accept for Peer Review"),
                            ("revisions_required", "Revisions Required"),
                            ("decline", "Decline"),
                            ("no_recommendation", "No Recommendation"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        max_length=40,
                        null=True,
                        verbose_name="Recommendation",
                    ),
                ),
                (
                    "suggested_reviewers",
                    models.TextField(
                        blank=True,
                        help_text="If recommending the article for peer review, the screener may suggest reviewers here. Hidden from the author.",
                        null=True,
                    ),
                ),
                (
                    "anonymous_to_author",
                    models.BooleanField(
                        default=True,
                        help_text="Hide the screener's name from the corresponding author.",
                    ),
                ),
                (
                    "anonymous_to_coscreeners",
                    models.BooleanField(
                        default=False,
                        help_text="Hide the screener's name from other screeners on this round.",
                    ),
                ),
                (
                    "comments_for_editor",
                    core.model_utils.JanewayBleachField(
                        blank=True,
                        help_text="Comments visible only to the managing editor; will not be shared with the author.",
                        null=True,
                        verbose_name="Comments for the Editor",
                    ),
                ),
                ("date_requested", models.DateTimeField(auto_now_add=True)),
                ("date_due", models.DateField()),
                ("date_accepted", models.DateTimeField(blank=True, null=True)),
                ("date_declined", models.DateTimeField(blank=True, null=True)),
                ("date_complete", models.DateTimeField(blank=True, null=True)),
                ("is_complete", models.BooleanField(default=False)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="submission.article",
                    ),
                ),
                (
                    "editor",
                    models.ForeignKey(
                        help_text="Editor requesting the screening report",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="editor_screening_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScreeningFormElement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("text", "Text Field"),
                            ("textarea", "Text Area"),
                            ("check", "Check Box"),
                            ("select", "Select"),
                            ("email", "Email"),
                            ("upload", "Upload"),
                            ("date", "Date"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "choices",
                    models.CharField(
                        blank=True,
                        help_text="Separate choices with the bar | character.",
                        max_length=1000,
                        null=True,
                    ),
                ),
                ("required", models.BooleanField(default=True)),
                ("order", models.IntegerField()),
                (
                    "help_text",
                    core.model_utils.JanewayBleachField(blank=True, null=True),
                ),
                (
                    "default_visibility",
                    models.BooleanField(
                        default=True,
                        help_text="If true, this answer will be available to the author by default; if false, it will be hidden from the author.",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "name"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TechnicalChecklist",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technical_checklist",
                        to="submission.article",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TechnicalChecklistTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("is_default", models.BooleanField(default=False)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="journal.journal",
                    ),
                ),
            ],
            options={
                "ordering": ("-is_default", "name"),
            },
        ),
        migrations.CreateModel(
            name="TechnicalChecklistTemplateItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("help_text", models.CharField(blank=True, default="", max_length=500)),
                ("order", models.IntegerField(default=0)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="screening.technicalchecklisttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "label"),
            },
        ),
        migrations.CreateModel(
            name="TechnicalChecklistItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("is_complete", models.BooleanField(default=False)),
                ("comment", models.TextField(blank=True, default="")),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "checklist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="screening.technicalchecklist",
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template_item",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="screening.technicalchecklisttemplateitem",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "label"),
            },
        ),
        migrations.AddField(
            model_name="technicalchecklist",
            name="template",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="screening.technicalchecklisttemplate",
            ),
        ),
        migrations.CreateModel(
            name="ScreeningRound",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round_number", models.IntegerField()),
                ("date_started", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="submission.article",
                    ),
                ),
            ],
            options={
                "ordering": ("-round_number",),
                "unique_together": {("article", "round_number")},
            },
        ),
        migrations.CreateModel(
            name="ScreeningRevisionRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "editor_note",
                    core.model_utils.JanewayBleachField(
                        blank=True,
                        help_text="Description of the changes the author should make. Shown to the author on the revision page.",
                        null=True,
                        verbose_name="Note to Author",
                    ),
                ),
                (
                    "author_note",
                    core.model_utils.JanewayBleachField(
                        blank=True,
                        help_text="Optional covering letter from the author describing the changes they made.",
                        null=True,
                        verbose_name="Covering Letter",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("minor_revisions", "Minor Revisions"),
                            ("major_revisions", "Major Revisions"),
                        ],
                        default="minor_revisions",
                        max_length=40,
                    ),
                ),
                (
                    "date_requested",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("date_due", models.DateField()),
                ("date_completed", models.DateTimeField(blank=True, null=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="submission.article",
                    ),
                ),
                (
                    "editor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScreeningPool",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Editorial groups whose members appear in the screener selection list. Leave empty to fall back to the journal's editor / section-editor role-holders.",
                        to="core.editorialgroup",
                    ),
                ),
                (
                    "journal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screening_pool",
                        to="journal.journal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScreeningForm",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "intro",
                    core.model_utils.JanewayBleachField(
                        help_text="Message displayed at the start of the screening form."
                    ),
                ),
                (
                    "thanks",
                    core.model_utils.JanewayBleachField(
                        help_text="Message displayed after the screener is finished."
                    ),
                ),
                ("deleted", models.BooleanField(default=False)),
                (
                    "elements",
                    models.ManyToManyField(to="screening.screeningformelement"),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="journal.journal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScreeningAssignmentAnswer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", core.model_utils.JanewayBleachField(blank=True, null=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="screening.screeningassignment",
                    ),
                ),
                (
                    "original_element",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="screening.screeningformelement",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="screeningassignment",
            name="form",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="screening.screeningform",
            ),
        ),
        migrations.AddField(
            model_name="screeningassignment",
            name="screener",
            field=models.ForeignKey(
                help_text="User to undertake the screening report",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="screener_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="screeningassignment",
            name="screening_round",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="screening.screeninground",
            ),
        ),
        migrations.CreateModel(
            name="FrozenScreeningFormElement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("text", "Text Field"),
                            ("textarea", "Text Area"),
                            ("check", "Check Box"),
                            ("select", "Select"),
                            ("email", "Email"),
                            ("upload", "Upload"),
                            ("date", "Date"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "choices",
                    models.CharField(
                        blank=True,
                        help_text="Separate choices with the bar | character.",
                        max_length=1000,
                        null=True,
                    ),
                ),
                ("required", models.BooleanField(default=True)),
                ("order", models.IntegerField()),
                (
                    "help_text",
                    core.model_utils.JanewayBleachField(blank=True, null=True),
                ),
                (
                    "default_visibility",
                    models.BooleanField(
                        default=True,
                        help_text="If true, this answer will be available to the author by default; if false, it will be hidden from the author.",
                    ),
                ),
                (
                    "answer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frozen_element",
                        to="screening.screeningassignmentanswer",
                    ),
                ),
                (
                    "form_element",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="screening.screeningformelement",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "name"),
                "abstract": False,
            },
        ),
    ]
