# Generated by Django 4.2.29 on 2026-05-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("screening", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="screeningrevisionrequest",
            name="date_cancelled",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
