# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-17 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_preprintversion_moderated_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='accept_version',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='decline_version',
            field=models.TextField(blank=True, null=True),
        ),
    ]
