# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-23 12:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20200523_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preprint',
            name='submission_file',
        ),
    ]
