# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-23 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_remove_preprint_submission_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preprint',
            name='curent_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curent_version', to='repository.PreprintVersion'),
        ),
        migrations.AlterField(
            model_name='preprint',
            name='doi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
