# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-18 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_auto_20200718_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='new_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
