# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-23 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_auto_20200523_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='preprint',
            name='submission_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission_file', to='repository.PreprintFile'),
        ),
    ]
