# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-10 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0005_repository_new_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preprint',
            name='curent_version',
        ),
        migrations.AlterField(
            model_name='subject',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='repository.Subject'),
        ),
    ]
