# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-28 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0005_preprint_submission_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='custom_js_code',
            field=models.TextField(blank=True, help_text='The contents of this field are output into the JS areaat the foot of every Repository page.', null=True),
        ),
    ]
