# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-13 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0006_auto_20200810_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preprint',
            name='subject',
        ),
        migrations.AddField(
            model_name='preprint',
            name='subject',
            field=models.ManyToManyField(to='repository.Subject'),
        ),
    ]
