# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-29 10:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0006_repository_custom_js_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('input_type', models.CharField(choices=[('text', 'Text'), ('select', 'Dropdown'), ('checkbox', 'Checkbox'), ('number', 'Number'), ('date', 'Date')], max_length=255)),
                ('width', models.CharField(choices=[(3, '3'), (6, '6'), (9, '9'), (12, '12')], max_length=2)),
                ('choices', models.CharField(blank=True, help_text='Separate choices with the bar | character.', max_length=1000, null=True)),
                ('required', models.BooleanField(default=True)),
                ('order', models.IntegerField()),
                ('display', models.BooleanField(default=False, help_text='Whether or not display this field in the article page')),
                ('dc_metadata_type', models.CharField(help_text='If this field is to be output as a dc metadata field you can addthe type here.', max_length=255)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Repository')),
            ],
        ),
        migrations.CreateModel(
            name='RepositoryFieldAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='repository.RepositoryField')),
            ],
        ),
        migrations.RemoveField(
            model_name='repositoryfields',
            name='repository',
        ),
        migrations.AddField(
            model_name='preprint',
            name='comments_editor',
            field=models.TextField(blank=True, help_text="Add any comments you'd like the editor to consider here.", null=True, verbose_name='Comments to the Editor'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='editors',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='RepositoryFields',
        ),
        migrations.AddField(
            model_name='repositoryfieldanswer',
            name='preprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Preprint'),
        ),
    ]
