# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-29 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0008_auto_20200529_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreprintAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ('last_name',)},
        ),
        migrations.RemoveField(
            model_name='author',
            name='order',
        ),
        migrations.RemoveField(
            model_name='author',
            name='preprint',
        ),
        migrations.AddField(
            model_name='preprintauthor',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Author'),
        ),
        migrations.AddField(
            model_name='preprintauthor',
            name='preprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Preprint'),
        ),
    ]
