# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-02 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0010_author_orcid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='email_address',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
