# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-02 10:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0011_auto_20200602_1122'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='preprintauthor',
            unique_together=set([('author', 'preprint')]),
        ),
    ]
