# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-25 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0011_auto_20200924_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='login_text',
            field=models.TextField(blank=True, help_text='If text is added it will display on the login page.', null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='footer',
            field=models.TextField(blank=True, default='<p>Powered by Janeway</p>', null=True),
        ),
    ]
