# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-04 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0013_auto_20200604_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='preprintfile',
            name='original_filename',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
