# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-30 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0014_auto_20200925_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='submission_agreement',
            field=models.TextField(default='<p>Authors grant us the right to publish, on this website, their uploaded manuscript, supplementary materials and any supplied metadata.</p>', help_text="Add any information that the author may need to know as part of their submission, eg. Copyright transfer etc.'", null=True),
        ),
    ]
