# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-05 15:04
from __future__ import unicode_literals

import core.file_system
from django.db import migrations, models
import repository.models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0015_auto_20200605_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preprint',
            name='meta_image',
            field=models.ImageField(blank=True, null=True, storage=core.file_system.JanewayFileSystemStorage(location='/home/ajrbyers/janeway/src/media'), upload_to=repository.models.preprint_file_upload),
        ),
        migrations.AlterField(
            model_name='preprintfile',
            name='file',
            field=models.FileField(storage=core.file_system.JanewayFileSystemStorage(location='files'), upload_to=repository.models.preprint_file_upload),
        ),
        migrations.AlterField(
            model_name='repository',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=core.file_system.JanewayFileSystemStorage(location='/home/ajrbyers/janeway/src/media'), upload_to=repository.models.repo_media_upload),
        ),
    ]
