# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-09 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0016_auto_20200605_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='preprint',
            name='stage',
            field=models.CharField(default='preprint_unsubmitted', max_length=25),
        ),
    ]
