# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-09 10:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0017_preprint_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repositoryfield',
            name='width',
        ),
    ]
