# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-09 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0018_remove_repositoryfield_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositoryfield',
            name='help_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
