# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-09 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0019_repositoryfield_help_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preprintaccess',
            old_name='dt',
            new_name='accessed',
        ),
    ]
