# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-09 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0020_auto_20200609_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
