# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-16 23:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0018_auto_20201109_1024'),
        ('repository', '0020_vq_title_abstracts'),
    ]

    operations = [
    ]
