# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-10 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0021_repository_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='preprintfile',
            name='uploaded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
