# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-11 13:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('repository', '0022_auto_20210303_1450'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='preprintauthor',
            unique_together=set([('account', 'preprint')]),
        ),
    ]
