# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-11 11:52
from __future__ import unicode_literals

import core.file_system
from django.db import migrations, models
import repository.models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0023_auto_20200610_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='preprintfile',
            name='size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='preprintfile',
            name='file',
            field=models.FileField(storage=core.file_system.JanewayFileSystemStorage(location='files/'), upload_to=repository.models.preprint_file_upload),
        ),
    ]
