# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-09-20 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0024_auto_20210812_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='use_domain_mode',
            field=models.BooleanField(default=False),
        ),
    ]
