# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-09-16 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0024_auto_20210812_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='preprint',
            name='preprint_decline_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
