# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-11 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0025_preprint_preprint_decline_note'),
        ('repository', '0025_create_keyword_preprint'),
    ]

    operations = [
    ]
