# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-01-07 12:13
from __future__ import unicode_literals

import core.model_utils
from django.db import migrations, models
from django.conf import settings


def remove_stale_domains(apps, schema_editor):
    if hasattr(settings, 'URL_CONFIG') and settings.URL_CONFIG == 'path':
        Repository = apps.get_model('repository', 'Respository')
        Repository.objects.all().update(domain=None)


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0026_merge_20211011_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='domain',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.RunPython(
            remove_stale_domains, reverse_code=migrations.RunPython.noop),
    ]
