# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-23 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0027_auto_20220107_1213'),
        ('repository', '0027_auto_20220209_1556'),
    ]

    operations = [
    ]
