# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-27 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0029_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='date_due',
            field=models.DateField(blank=True, null=True, verbose_name='Due date'),
        ),
    ]
