# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-13 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0029_preprint_article'),
        ('repository', '0029_auto_20220510_1053'),
    ]

    operations = [
    ]
