# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-27 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0030_review_date_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repository.Comment'),
        ),
    ]
