# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-02 18:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('repository', '0031_repository_active_licenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='submission_notification_recipients',
            field=models.ManyToManyField(blank=True, related_name='submission_notification_repositories', to=settings.AUTH_USER_MODEL),
        ),
    ]
