# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-28 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0031_auto_20220427_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='status_reason',
            field=models.TextField(blank=True, help_text='Information supplied by a reviewer when declining or completing a review or by staff withdrawing a review', null=True),
        ),
    ]
