# Generated by Django 3.2.16 on 2023-02-22 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [

        ('repository', '0032_repository_submission_notification_recipients'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='file_upload_help',
            field=models.TextField(blank=True, help_text='Add any information that the author may need to know as part of the file upload process.', null=True, verbose_name='File Upload Help'),
        ),
        migrations.AddField(
            model_name='repository',
            name='require_pdf_help',
            field=models.TextField(blank=True, default='requires that all author uploads be PDF files.', help_text='When a repository requires that all manuscripts be PDF this text is combined with the repository name and displayed with the default text it would diplay: RepositoryName requires that all author uploads be PDF files.', null=True, verbose_name='Limit Upload to PDF Help'),
        ),
    ]
