# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-04 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0032_review_status_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='review_invitation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
