# Generated by Django 3.2.16 on 2023-01-23 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0033_auto_20230120_1546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preprintaccess',
            options={},
        ),
    ]
