# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-05 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0034_review_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='review_helper',
            field=models.TextField(blank=True, null=True),
        ),
    ]
