# Generated by Django 3.2.16 on 2023-01-23 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0034_alter_preprintaccess_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preprintaccess',
            options={'verbose_name_plural': 'preprint access records'},
        ),
    ]
