# Generated by Django 3.2.16 on 2023-05-18 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0033_file_upload_texts'),
        ('repository', '0035_alter_preprintaccess_options'),
    ]

    operations = [
    ]
