# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-05 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0035_repository_review_helper'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='manager_review_status_change',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='reviewer_review_status_change',
            field=models.TextField(blank=True, null=True),
        ),
    ]
