# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-05 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0036_auto_20220505_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
