# Generated by Django 3.2.19 on 2023-05-24 15:17

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0036_merge_20230518_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preprintaccess',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
