# Generated by Django 3.2.20 on 2024-02-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0041_auto_20231207_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrepository',
            name='additional_version_help',
            field=models.TextField(blank=True, default='', help_text='This text allows repository managers to provide additional information to authors when they are uploading an update to their submission.'),
        ),
        migrations.AddField(
            model_name='repository',
            name='additional_version_help',
            field=models.TextField(blank=True, default='', help_text='This text allows repository managers to provide additional information to authors when they are uploading an update to their submission.'),
        ),
    ]
