# Generated by Django 3.2.20 on 2023-11-08 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0042_auto_20231107_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preprintversion',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='repository.preprintfile'),
        ),
    ]
