# Generated by Django 4.2.11 on 2024-06-13 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0042_alter_preprint_abstract'),
        ('repository', '0043_auto_20240402_1256'),
    ]

    operations = [
    ]
