# Generated by Django 4.2 on 2024-06-26 10:12

from django.db import migrations, models
from django.template.defaultfilters import striptags


def strip_html_tags_from_repo_field_help_text(apps, schema_editor):
    RepositoryField = apps.get_model('repository', 'RepositoryField')

    for field in RepositoryField.objects.all():
        field.help_text = striptags(field.help_text)
        field.save()


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0043_auto_20240402_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositoryfield',
            name='help_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RunPython(
            strip_html_tags_from_repo_field_help_text,
            reverse_code=migrations.RunPython.noop,
        )
    ]
