# Generated by Django 4.2.11 on 2024-06-13 22:11

import core.model_utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0044_merge_20240613_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preprint',
            name='abstract',
            field=core.model_utils.JanewayBleachField(blank=True, null=True),
        ),
    ]
