# Generated by Django 4.2 on 2024-08-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0044_historicalrepository_review_submission_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrepository',
            name='display_public_metrics',
            field=models.BooleanField(default=False, help_text='Enable this setting to display metrics publicly.'),
        ),
        migrations.AddField(
            model_name='repository',
            name='display_public_metrics',
            field=models.BooleanField(default=False, help_text='Enable this setting to display metrics publicly.'),
        ),
    ]
