# Generated by Django 4.2.14 on 2024-07-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_migrate_affiliation_institution'),
        ('repository', '0046_historicalrepository_enable_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preprintauthor',
            name='affiliation',
        ),
        migrations.AlterField(
            model_name='author',
            name='affiliation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
