# Generated by Django 4.2.20 on 2025-06-05 09:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


def create_preprint_submission_type(apps, schema_editor):
    RepositorySubmissionType = apps.get_model('repository', 'RepositorySubmissionType')
    Preprint = apps.get_model('repository', 'Preprint')
    Repository = apps.get_model('repository', 'Repository')

    for repo in Repository.objects.all():
        submission_type, _ = RepositorySubmissionType.objects.get_or_create(
            repository=repo,
            slug='preprint',
            defaults={
                'name': 'Preprint',
                'name_plural': 'Preprints',
            },
        )
        Preprint.objects.filter(repository=repo).update(submission_type=submission_type)


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0050_historicalrepository_rou_default_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositorySubmissionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_plural', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('pill_colour', models.CharField(default='#1e40af', help_text='Hex colour code for the pill border and text (e.g. #1e40af)', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex colour code (e.g. #1e40af or #fff).', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_types', to='repository.repository')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='preprint',
            name='submission_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='repository.repositorysubmissiontype'),
        ),
        migrations.RunPython(
            create_preprint_submission_type,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
