# Generated by Django 4.2.20 on 2026-02-26 15:28

import core.model_utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("repository", "0052_merge_20260226_1524"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalrepository",
            name="new_version_submitted",
            field=core.model_utils.JanewayBleachField(
                blank=True, help_text="Email sent when an author uploads a new version."
            ),
        ),
        migrations.AlterField(
            model_name="preprint",
            name="abstract",
            field=core.model_utils.JanewayBleachField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="repository",
            name="new_version_submitted",
            field=core.model_utils.JanewayBleachField(
                blank=True, help_text="Email sent when an author uploads a new version."
            ),
        ),
        migrations.AlterField(
            model_name="repositoryfield",
            name="submission_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional, allows you to tie this field to a specific submission type. Leave blank to tie this to all submission types.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="repository.repositorysubmissiontype",
            ),
        ),
    ]
