# Generated by Django 4.2.29 on 2026-03-26 17:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("repository", "0048_repository_comment_approved_comment_published"),
        (
            "repository",
            "0053_alter_historicalrepository_new_version_submitted_and_more",
        ),
    ]

    operations = []
