# Generated by Django 4.2.29 on 2026-03-26 18:15

import core.model_utils
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("repository", "0054_merge_20260326_1707"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalrepository",
            name="comment_approved",
            field=core.model_utils.JanewayBleachField(
                blank=True,
                help_text="Sent to the commenter when their comment is approved. Available variables: {{ preprint.title }}, {{ comment.author.full_name }}, {{ url }}.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalrepository",
            name="comment_published",
            field=core.model_utils.JanewayBleachField(
                blank=True,
                help_text="Sent to the submission author when a comment on their work is approved. Available variables: {{ preprint.title }}, {{ preprint.owner.full_name }}, {{ url }}.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalrepository",
            name="new_comment",
            field=core.model_utils.JanewayBleachField(
                blank=True,
                help_text="Sent to repository managers when a new comment is submitted and awaiting moderation. Available variables: {{ preprint.title }}, {{ manager.full_name }}, {{ url }}.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="repository",
            name="comment_approved",
            field=core.model_utils.JanewayBleachField(
                blank=True,
                help_text="Sent to the commenter when their comment is approved. Available variables: {{ preprint.title }}, {{ comment.author.full_name }}, {{ url }}.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="repository",
            name="comment_published",
            field=core.model_utils.JanewayBleachField(
                blank=True,
                help_text="Sent to the submission author when a comment on their work is approved. Available variables: {{ preprint.title }}, {{ preprint.owner.full_name }}, {{ url }}.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="repository",
            name="new_comment",
            field=core.model_utils.JanewayBleachField(
                blank=True,
                help_text="Sent to repository managers when a new comment is submitted and awaiting moderation. Available variables: {{ preprint.title }}, {{ manager.full_name }}, {{ url }}.",
                null=True,
            ),
        ),
    ]
