# Generated by Django 4.2.29 on 2026-04-01 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.CORE_FILETEXT_MODEL),
        ("repository", "0055_alter_historicalrepository_comment_approved_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="preprintfile",
            name="text",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="preprint_file",
                to=settings.CORE_FILETEXT_MODEL,
            ),
        ),
    ]
