# Generated by Django 4.2.29 on 2026-08-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("repository", "0056_preprintfile_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalrepository",
            name="identifier_management",
            field=models.BooleanField(
                default=True,
                help_text="When turned on, repository managers can manage identifiers, such as DOIs, for preprints.",
            ),
        ),
        migrations.AddField(
            model_name="repository",
            name="identifier_management",
            field=models.BooleanField(
                default=True,
                help_text="When turned on, repository managers can manage identifiers, such as DOIs, for preprints.",
            ),
        ),
    ]
