# Generated by Django 4.2.29 on 2026-08-17 10:57

from django.db import migrations, models


def check_no_duplicate_short_names(apps, schema_editor):
    """Fail with a readable message instead of a bare unique constraint error."""
    Repository = apps.get_model("repository", "Repository")
    duplicates = (
        Repository.objects.values("short_name")
        .annotate(count=models.Count("id"))
        .filter(count__gt=1)
    )
    if duplicates.exists():
        lines = []
        for row in duplicates:
            short_name = row["short_name"]
            matches = Repository.objects.filter(short_name=short_name).values_list(
                "pk", "name"
            )
            ids = ", ".join(f"#{pk} ({name})" for pk, name in matches)
            lines.append(f"  '{short_name}': {ids}")
        raise RuntimeError(
            "Cannot make Repository.short_name unique — the following "
            "short_name value(s) are shared by more than one repository "
            "and must be renamed before this migration can run:\n" + "\n".join(lines)
        )


class Migration(migrations.Migration):
    dependencies = [
        ("repository", "0056_preprintfile_text"),
    ]

    operations = [
        migrations.RunPython(
            check_no_duplicate_short_names, reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="historicalrepository",
            name="short_name",
            field=models.CharField(
                db_index=True,
                help_text="Unique, short version of the name eg. olh. Max 15 chars.",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="repository",
            name="short_name",
            field=models.CharField(
                help_text="Unique, short version of the name eg. olh. Max 15 chars.",
                max_length=15,
                unique=True,
            ),
        ),
    ]
