# Generated by Django 4.2.29 on 2026-05-27 12:25

import core.model_utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("repository", "0056_preprintfile_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalrepository",
            name="default_language",
            field=models.CharField(
                blank=True,
                default="en",
                help_text="The primary language of this repository.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="historicalrepository",
            name="languages",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of language codes accepted by this repository, sourced from settings.LANGUAGES.",
            ),
        ),
        migrations.AddField(
            model_name="preprint",
            name="abstract_cy",
            field=core.model_utils.JanewayBleachField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="preprint",
            name="abstract_de",
            field=core.model_utils.JanewayBleachField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="preprint",
            name="abstract_en",
            field=core.model_utils.JanewayBleachField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="preprint",
            name="abstract_en_us",
            field=core.model_utils.JanewayBleachField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="preprint",
            name="abstract_es",
            field=core.model_utils.JanewayBleachField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="preprint",
            name="abstract_fr",
            field=core.model_utils.JanewayBleachField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="preprint",
            name="abstract_nl",
            field=core.model_utils.JanewayBleachField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="preprint",
            name="title_cy",
            field=models.CharField(
                help_text="Your article title", max_length=300, null=True
            ),
        ),
        migrations.AddField(
            model_name="preprint",
            name="title_de",
            field=models.CharField(
                help_text="Your article title", max_length=300, null=True
            ),
        ),
        migrations.AddField(
            model_name="preprint",
            name="title_en",
            field=models.CharField(
                help_text="Your article title", max_length=300, null=True
            ),
        ),
        migrations.AddField(
            model_name="preprint",
            name="title_en_us",
            field=models.CharField(
                help_text="Your article title", max_length=300, null=True
            ),
        ),
        migrations.AddField(
            model_name="preprint",
            name="title_es",
            field=models.CharField(
                help_text="Your article title", max_length=300, null=True
            ),
        ),
        migrations.AddField(
            model_name="preprint",
            name="title_fr",
            field=models.CharField(
                help_text="Your article title", max_length=300, null=True
            ),
        ),
        migrations.AddField(
            model_name="preprint",
            name="title_nl",
            field=models.CharField(
                help_text="Your article title", max_length=300, null=True
            ),
        ),
        migrations.AddField(
            model_name="preprintversion",
            name="abstract_cy",
            field=core.model_utils.JanewayBleachField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="preprintversion",
            name="abstract_de",
            field=core.model_utils.JanewayBleachField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="preprintversion",
            name="abstract_en",
            field=core.model_utils.JanewayBleachField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="preprintversion",
            name="abstract_en_us",
            field=core.model_utils.JanewayBleachField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="preprintversion",
            name="abstract_es",
            field=core.model_utils.JanewayBleachField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="preprintversion",
            name="abstract_fr",
            field=core.model_utils.JanewayBleachField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="preprintversion",
            name="abstract_nl",
            field=core.model_utils.JanewayBleachField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="preprintversion",
            name="title_cy",
            field=models.CharField(
                blank=True, help_text="Your article title", max_length=300, null=True
            ),
        ),
        migrations.AddField(
            model_name="preprintversion",
            name="title_de",
            field=models.CharField(
                blank=True, help_text="Your article title", max_length=300, null=True
            ),
        ),
        migrations.AddField(
            model_name="preprintversion",
            name="title_en",
            field=models.CharField(
                blank=True, help_text="Your article title", max_length=300, null=True
            ),
        ),
        migrations.AddField(
            model_name="preprintversion",
            name="title_en_us",
            field=models.CharField(
                blank=True, help_text="Your article title", max_length=300, null=True
            ),
        ),
        migrations.AddField(
            model_name="preprintversion",
            name="title_es",
            field=models.CharField(
                blank=True, help_text="Your article title", max_length=300, null=True
            ),
        ),
        migrations.AddField(
            model_name="preprintversion",
            name="title_fr",
            field=models.CharField(
                blank=True, help_text="Your article title", max_length=300, null=True
            ),
        ),
        migrations.AddField(
            model_name="preprintversion",
            name="title_nl",
            field=models.CharField(
                blank=True, help_text="Your article title", max_length=300, null=True
            ),
        ),
        migrations.AddField(
            model_name="repository",
            name="default_language",
            field=models.CharField(
                blank=True,
                default="en",
                help_text="The primary language of this repository.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="repository",
            name="languages",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of language codes accepted by this repository, sourced from settings.LANGUAGES.",
            ),
        ),
        migrations.AddField(
            model_name="versionqueue",
            name="abstract_cy",
            field=core.model_utils.JanewayBleachField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="versionqueue",
            name="abstract_de",
            field=core.model_utils.JanewayBleachField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="versionqueue",
            name="abstract_en",
            field=core.model_utils.JanewayBleachField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="versionqueue",
            name="abstract_en_us",
            field=core.model_utils.JanewayBleachField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="versionqueue",
            name="abstract_es",
            field=core.model_utils.JanewayBleachField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="versionqueue",
            name="abstract_fr",
            field=core.model_utils.JanewayBleachField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="versionqueue",
            name="abstract_nl",
            field=core.model_utils.JanewayBleachField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="versionqueue",
            name="title_cy",
            field=models.CharField(
                help_text="Your article title", max_length=300, null=True
            ),
        ),
        migrations.AddField(
            model_name="versionqueue",
            name="title_de",
            field=models.CharField(
                help_text="Your article title", max_length=300, null=True
            ),
        ),
        migrations.AddField(
            model_name="versionqueue",
            name="title_en",
            field=models.CharField(
                help_text="Your article title", max_length=300, null=True
            ),
        ),
        migrations.AddField(
            model_name="versionqueue",
            name="title_en_us",
            field=models.CharField(
                help_text="Your article title", max_length=300, null=True
            ),
        ),
        migrations.AddField(
            model_name="versionqueue",
            name="title_es",
            field=models.CharField(
                help_text="Your article title", max_length=300, null=True
            ),
        ),
        migrations.AddField(
            model_name="versionqueue",
            name="title_fr",
            field=models.CharField(
                help_text="Your article title", max_length=300, null=True
            ),
        ),
        migrations.AddField(
            model_name="versionqueue",
            name="title_nl",
            field=models.CharField(
                help_text="Your article title", max_length=300, null=True
            ),
        ),
    ]
