# Generated by Django 4.2.29 on 2026-10-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("repository", "0057_historicalrepository_identifier_management_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalrepository",
            name="enable_organisation_units",
            field=models.BooleanField(
                default=True,
                help_text="Show organisational units on the public site and in the submission form. Turning this off hides them without deleting any units or their links to submissions.",
            ),
        ),
        migrations.AddField(
            model_name="repository",
            name="enable_organisation_units",
            field=models.BooleanField(
                default=True,
                help_text="Show organisational units on the public site and in the submission form. Turning this off hides them without deleting any units or their links to submissions.",
            ),
        ),
    ]
