# Generated by Django 4.2.29 on 2026-05-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("repository", "0057_add_multilingual_support"),
    ]

    operations = [
        migrations.AddField(
            model_name="preprint",
            name="language",
            field=models.CharField(
                blank=True,
                default="en",
                help_text="The primary language of this preprint.",
                max_length=20,
            ),
        ),
    ]
