# Generated by Django 4.2.29 on 2026-10-07 09:00

import core.model_utils
from django.db import migrations


def bleach_titles(apps, schema_editor):
    for model_name in ("Preprint", "PreprintVersion", "VersionQueue"):
        model = apps.get_model("repository", model_name)
        field = model._meta.get_field("title")
        for obj in model.objects.filter(title__contains="<").iterator():
            title = field.pre_save(obj, add=False)[: field.max_length]
            if title != obj.title:
                model.objects.filter(pk=obj.pk).update(title=title)


class Migration(migrations.Migration):
    dependencies = [
        ("repository", "0058_repository_enable_organisation_units"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preprint",
            name="title",
            field=core.model_utils.JanewayBleachCharField(
                help_text="Your article title", max_length=300
            ),
        ),
        migrations.AlterField(
            model_name="preprintversion",
            name="title",
            field=core.model_utils.JanewayBleachCharField(
                blank=True, help_text="Your article title", max_length=300
            ),
        ),
        migrations.AlterField(
            model_name="versionqueue",
            name="title",
            field=core.model_utils.JanewayBleachCharField(
                help_text="Your article title", max_length=300
            ),
        ),
        migrations.RunPython(bleach_titles, migrations.RunPython.noop),
    ]
