# Generated by Django 4.2.29 on 2026-10-06 14:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("repository", "0062_delete_preprintauthor"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="moderators",
            field=models.ManyToManyField(
                blank=True,
                help_text="Moderators handle submissions, updates, comments and reviews, but cannot configure the repository.",
                related_name="moderated_repositories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="repository",
            name="managers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Managers configure the repository and moderate it.",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
