# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-03 13:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypesettingClaim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed', models.DateTimeField(default=django.utils.timezone.now)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='submission.Article')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='typesettingclaim',
            unique_together=set([('editor', 'article')]),
        ),
    ]
