# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-16 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typesetting', '0006_auto_20200227_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='typesettingassignment',
            name='cancelled',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
