# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-05 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('typesetting', '0012_auto_20210121_1729'),
        ('typesetting', '0012_auto_20210126_1203'),
    ]

    operations = [
    ]
