# Generated by Django 3.2.20 on 2024-03-15 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('typesetting', '0013_merge_20210205_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleyproofing',
            name='manager',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='galley_manager',
                to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
