# Generated by Django 3.2.20 on 2024-07-08 16:27

import core.model_utils
from django.db import migrations, models


def store_empty_string(apps, schema_editor):
    TypesettingAssignment = apps.get_model('typesetting', 'TypesettingAssignment')
    TypesettingAssignment.objects.filter(task__isnull=True).update(task='')


class Migration(migrations.Migration):

    dependencies = [
        ('typesetting', '0015_article_title_safe'),
    ]

    operations = [
        migrations.RunPython(
            store_empty_string,
            reverse_code=migrations.RunPython.noop
        ),
    ]
