# Generated by Django 4.2.15 on 2025-02-21 10:23

from django.db import migrations


def update_typesetting_workflow_name(apps, schema_editor):
    WorkflowElement = apps.get_model('core', 'WorkflowElement')
    WorkflowElement.objects.filter(
        element_name='Typesetting Plugin',
    ).update(
        element_name='typesetting',
    )


def reset_typesetting_workflow_name(apps, schema_editor):
    WorkflowElement = apps.get_model('core', 'WorkflowElement')
    WorkflowElement.objects.filter(
        element_name='typesetting',
    ).update(
        element_name='Typesetting Plugin',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('typesetting', '0018_selected_files'),
    ]

    operations = [
        migrations.RunPython(
            update_typesetting_workflow_name,
            reverse_code=reset_typesetting_workflow_name,
        ),
    ]
